### PR TITLE
[NFR] RoleAware and ResourceAware Interfaces

### PR DESCRIPTION
**Pull request by Jurigag**
Need some more tests, i will commit it later.

refs #11235

### CODE REVIEW

**Comment by sergeyklay** [comment]
@andresgutierrez

**Comment by Jurigag** [comment]
@andresgutierrez 
Any chance about adding it in 2.1.0 ? Did i have something more to do here ?

**Comment by sergeyklay** [comment]
I'm not sure about Role**able** and Resource**able**. Mb Role**Aware** and Resource**Aware** ?

**Comment by Jurigag** [comment]
Yea that will be imho better. I will put new commit soon with it.

**Comment by sergeyklay** [comment]
<s>Now you can pass objects to `Phalcon\Acl\Adapter\Memory::isAllowed`</s>
Now you can pass objects to `Phalcon\Acl\AdapterInterface::isAllowed`

Your changes primarily relate to the interface and then to the implementation

**Comment by Jurigag** [comment]
Should i change only this all all Phalcon\Acl\Adapter\Memory to Phalcon\Acl\AdapterInterface ?

**Comment by sergeyklay** [comment]
Yes

**Comment by andresgutierrez** [comment]
Could you please rebase?

**Comment by sergeyklay** [comment]
@Jurigag This needs to be rebased onto 2.1.x. Also squash it into a single commit to keep the history clean.

**Comment by sergeyklay** [comment]
Looks good to me.

@andresgutierrez ?

**Comment by Jurigag** [comment]
Updated two more comments beacause they were old. Dont know why travis ci have problems. I hope now its final commit.

**Comment by sergeyklay** [comment]
Can you please rebase again?

**Pull request closed without merging**
