### PR TITLE
Iteration and array access feature on session bag like on 1.3.4 version

### PR DESCRIPTION
**Pull request by DestinyMKas**
Missing functionality in 2.0.0 version on session bag:
iteration
arrayaccess
count

### CODE REVIEW

**Comment by sergeyklay** [comment]
:+1:

**Comment by sergeyklay** [comment]
@phalcon If you close the PR - explain why please

**Comment by andresgutierrez** [comment]
Branch 2.0.0 was renamed to 2.0.x, could you please submit this change to that branch?

**Comment by DestinyMKas** [comment]
#10073

**Pull request closed without merging**
