### PR TITLE
Improved Phalcon\Cache\Backend\Apc

### PR DESCRIPTION
**Pull request by sergeyklay**
Hello!

* Type: new feature
* Link to issue: #12098, #11934

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

- Improved `Phalcon\Cache\Backend\Apc` by introducing support of APCu
- Improved `Phalcon\Annotations\Adapter\Apc` by introducing support of APCu

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
I don't like this. Why just not introduce new classes?

**Comment by sergeyklay** [comment]
Why don't like?

**Comment by Jurigag** [comment]
Cuz as i wrote - i would like much more just seperated classes. I don't like one class to be adapter for both apc and apcu.

**Comment by sergeyklay** [comment]
Yes, I'm understand. But could you please elaborate on that. In order to discuss something, we need a reason. "I don't like" not reason.

**Comment by Jurigag** [comment]
Well we will remove necessary to have checks, conditions etc, also code will be much cleaner. As i saw in other frameworks if they had support for both apc and apcu - it was done in seperated classes.

**Comment by andresgutierrez** [comment]
We can have this for BC reasons and fully deprecate apc in Phalcon 4, what do you think?

**Comment by Jurigag** [comment]
Not deprecate - just remove apc more likely, but then we would need imho change apc classes names to apcu cuz it will no longer work with apc obviously. That's why seperated classes seems more suitable - someone could just switch to apcu and he would need to do less stuff in phalcon 4.

**Comment by Jurigag** [comment]
Also notice that atm if someone is already using php7 + apcu + phallcon he needs to install apcu_bc. So this classes work for him anyway and he will not notice any difference, except those additional checks.

And if someone would like to use apcu + php7 + phalcon then he would need to change to new class in phalcon 4, cuz there is no point having it named as Apc when it will be working only with Apcu.

**Comment by dschissler** [comment]
I'd prefer if they were to be separate adapters but if this new code can properly check for all of the different possibilities (2^2 I think) then this should be good.  One thing that could be a complication is if someone is having issues and it is unclear which extension they are using.  Its not a really big issue but if something goes wrong it could make for some unhelpful bug reports.  So perhaps a solution to this would be to have the adapter save which extension it is using so that it can be logged on request.

**Comment by dschissler** [comment]
I think that it might be possible to have both `apc` and `apcu` installed on a supported PHP 5.5 or 5.6 system.  If this is the case then someone should at least manually test all of these combinations (or write a test if that is even possible).

**Comment by Jurigag** [comment]
Php apcu already have apc emulation builtin so apc_fetch function will just call apcu function for php 5 users this change will be totally useless

**Comment by Jurigag** [comment]
How this combined have advantage of being compatible in the next years like if someone who already wants to use apcu is already using old class and in phalcon 4 he would need needs to change name anyway? Just separated classes are way to go, new developers could use then new classes and have less things to care about when switch to phalcon 4, old would need to change anyway.

**Comment by dschissler** [comment]
> Php5 apcu already have apc emulation builtin so apc_fetch function will just call apcu function for php 5 users this change will be totally useless

It seems that it uses `apcu` before `apc` if its available.

> How this combined have advantage of being compatible in the next years like if someone who already wants to use apcu is already using old class and in phalcon 4 he would need needs to change name anyway? Just separated classes are way to go, new developers could use then new classes and have less things to care about when switch to phalcon 4, old would need to change anyway.

Couldn't we just keep the same name?  Do the class names really need to be changed from `...apc` to `...apcu`?  I don't think that there needs to be an exact mapping of extension name to class name.

**Comment by Jurigag** [comment]
I think yes - it needs to change, cuz it no longer will work in phalcon 4 with APC, just only with APCU, so why keep old APC name?

**Comment by dschissler** [comment]
@sergeyklay It seems that the argument is coming down to whether or not the Phalcon 4 class name can be left the same or if it will need to be changed from `...Apc` to  `...Apcu`.  I think that its ok not having the "u" in it and that it doesn't cause any confusion for Phalcon 4.  However, if this is an undesirable future situation then probably there shouldn't be a single Apc adapter.

**Comment by Jurigag** [comment]
I just don't see really why we can't have both adapters. In all known major frameworks they have apcu classes.

**Comment by niden** [comment]
I think we should have 2 adapters.

We can deprecate `Apc` at a later stage without having to touch the adapter to remove the apc related code from a common adapter.

My 2 cents

**Comment by dschissler** [comment]
I think that two adapters has overall less issues than a combined adapter.  But I'm not going to be the one writing the code and I'm also fine with the one adapter.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/pull/12788, https://github.com/phalcon/cphalcon/pull/12786

**Pull request closed without merging**
