### PR TITLE
Tag::getTitle shows a title depending on prependTitle and appendTitle

### PR DESCRIPTION
**Pull request by googlle**

### CODE REVIEW

**Comment by sergeyklay** [comment]
1. Could you please submit just the commits that belong to the PR?
2. Also update please CHANGELOG.md
3. As you can see tests fails

**Comment by googlle** [comment]
@sergeyklay Can you help me with it? I'm new in this

**Comment by Izopi4a** [comment]
1. save your changes
2. git checkout .
3. git pull origin 2.1.x ( from phalcon )
4. re apply your changes
5. Git commit - git push 
6. open the pull request

the problem is you are trying to commit already existing commits. If you cant make the local unit tests,  include [WIP] in your pull requests, and use the one here.

**Comment by googlle** [comment]
I will rework and re-send

**Pull request closed without merging**
