### PR TITLE
Flexible events handling

### PR DESCRIPTION
**Pull request by BeMySlaveDarlin**
Hello!

* Type: new feature, bug fix
* Issues: [#14861](https://github.com/phalcon/cphalcon/issues/14861),  [#14687](https://github.com/phalcon/cphalcon/issues/14687)
**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change (will be added if this gets all approves)

For #14861: now it is available attaching callable `[class|object, method]` to event manager:
```php
$eventsManager->attach("dispatcher:beforeException", [BeforeExceptionListener::class, "handle"]);
```

For #14861: now it is available attaching invokable objects to event manager, because now it is possible to pass callable (class with __invoke accepts as callable):
```php
namespace Listeners\Dispatcher;

use Phalcon\Events\Event;

class BeforeExceptionListener extends ListenerInterface
{
    public function __invoke(Event $event, $dispatcher);
}

$eventsManager->attach("dispatcher:beforeException", new  BeforeExceptionListener());
```

For #14861: possibility of using Event Providers.

`$listeners` property in Provider contains list of Listeners which will be attached to Events Manager in one loop (at current implementation there is no option to set each Listener call priority) as shown below.

For #14687: `$options` property contains list of events (namespace or full event name) with array of configurations.
There is option for events named `strict`. If set `true`, event loop breaks on first false Listener result.

```php
use Phalcon\Events\Provider as PhalconProvider;

class Provider extends PhalconProvider
{
    protected $listeners = [
          'router:notMatchedRoute' => NotMatchedRoute::class,
          'router:notMatchedRoute' => function($event, $router) { return true; }
          'router:notMatchedRoute' => [
              'class' => NotMatchedRoute::class,
              'method' => 'handle',
          ],
          'router:notMatchedRoute' => [
              NotMatchedRoute::class,
              function($event, $router) { return true; },
          ],
          'router:notMatchedRoute' => [
              [
                  'class' => NotMatchedRoute::class,
                  'method' => 'handle',
              ],
              function($event, $router) { return true; },
          ],
    ];

    protected $options = [
        'dispatch:beforeException' => [
            'strict' => true,
            'cancelable' => true,
        ],
        'dispatch' => [
            'strict' => true,
        ],
    ];
}

$eventsManager->registerProvider(new Provider());
```

Thanks

### CODE REVIEW

**Review by sergeyklay — DISMISSED** [review]
LGTM. But consider 4.1.x branch for this.

**Review by Jeckerson — DISMISSED** [review]

**Comment by BeMySlaveDarlin** [comment]
> LGTM. But consider 4.1.x branch for this.

The reason of requesting it on 4.0.x is just i want it asap, cos this blocks further logic of Event Provider feature development =)

**Comment by ruudboon** [comment]
> > LGTM. But consider 4.1.x branch for this.
> 
> The reason of requesting it on 4.0.x is just i want it asap, cos this blocks further logic of Event Provider feature development =)

We will break semver if we add this to 4.0 so if we accept this new feature we should add it to 4.1. Besides that we need a pull for docs as well.
Technically looks good to me. We need to investigate if this is a feature that will help a broad audience and aligns with our future plans.

**Comment by BeMySlaveDarlin** [comment]
> We will break semver if we add this to 4.0 so if we accept this new feature we should add it to 4.1. Besides that we need a pull for docs as well.
> Technically looks good to me. We need to investigate if this is a feature that will help a broad audience and aligns with our future plans.

No prob, will recreate pr to 4.1 after this one pass all approves

**Comment by ruudboon** [comment]
@BeMySlaveDarlin you can change the target branch in your pull. It’s on the top in github.

**Comment by BeMySlaveDarlin** [comment]
> @BeMySlaveDarlin you can change the target branch in your pull. It’s on the top in github.

Rebased and fixed.
I probably will add Event Provider part right in this PR while its going to 4.1

**Comment by niden** [comment]
A couple of points on this.

First of all, thank you for the contribution and enthusiasm. It is highly appreciated.

However, there is no issue attached to this PR. Also, the (missing) issue has not been requested by the community as something that is necessary etc. etc. That deviates from how NFRs are processed.

Putting that aside. The code looks solid but I have no idea why we even need this - at all. 

This PR introduces 3 ways of doing exactly the same thing. Why? 

It also increases the complexity of the framework which I do not think is necessary.

The goal for v4 was to simplify the framework not add more ways of doing the same thing.

**Comment by BeMySlaveDarlin** [comment]
Current behavior of attaching Listener to Events Manager expects a single class to handle all events of some namespace ('dispatch:*') or class with single method named as event type exactly ('dispatch:beforeException' => `class SomeListener { function beforeException(); }`). Adding listeners to eventsManager via attach is not enough flexible and smeared to all services and components/modules.
This addition gives possibility of using Event Providers or simple event listeners configurations:
```
class Provider implements EventsProviderInterface{
    protected $listeners = [
        'dispatch:beforeException' => [
                BeforeExceptionListener::class,
                AnotherListener::class,
                [
                        'class' => BeforeExceptionListener::class,
                        'method' => 'handle',
                ],
        ],
    ];
}
```

**Comment by niden** [comment]
Sorry but this does not get my blessing. Just because an issue was created after my comment does not mean that the community wants this or that it is necessary for the framework. It could very well be but there is a process we follow and this is not it.

I understand the problem you are trying to solve and this pretty much solves it but there was already a plan to rework and expand the events manager here:

https://github.com/phalcon/cphalcon/issues/14687

If the others are OK with it this - feel free to merge it.

**Comment by BeMySlaveDarlin** [comment]
> Sorry but this does not get my blessing. Just because an issue was created after my comment does not mean that the community wants this or that it is necessary for the framework. It could very well be but there is a process we follow and this is not it.
> 
> I understand the problem you are trying to solve and this pretty much solves it but there was already a plan to rework and expand the events manager here:
> 
> #14687
> 
> If the others are OK with it this - feel free to merge it.

Np. Can i at least get rid of **final** on `Phalcon\Events\Manager::fireQueue`?)

**Comment by sergeyklay** [comment]
> > Sorry but this does not get my blessing. Just because an issue was created after my comment does not mean that the community wants this or that it is necessary for the framework. It could very well be but there is a process we follow and this is not it.
> > I understand the problem you are trying to solve and this pretty much solves it but there was already a plan to rework and expand the events manager here:
> > #14687
> > If the others are OK with it this - feel free to merge it.
> 
> Np. Can i at least get rid of **final** on `Phalcon\Events\Manager::fireQueue`?)

Yes, if it will be declared in the interface Events Manager implements.

**Comment by BeMySlaveDarlin** [comment]
> Yes, if it will be declared in the interface Events Manager implements.
It can break backward compatibility, if i declare it in ManagerInterface.

**Comment by BeMySlaveDarlin** [comment]
@niden Concerning [14687](https://github.com/phalcon/cphalcon/issues/14687) and other expectations, made some update commits, can you please check it closely?

**Pull request closed without merging**
