### PR TITLE
[WIP]3.1.x firewall

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: this pr is adding Firewall component, way to protect routes against unauthorized roles to access certain routes. It's done using listener on dispatcher/micro on beforeExecute/afterBinding event.

In dispatcher you can either use Annotations or Acl based firewall. In micro there is only Acl based firewall. 

Would appreciate any comments etc.

This PR is commits/changes from other PRs etc stuff so don't bother them, i will rebase everything if all will be merged.
Thanks

Related:
https://github.com/phalcon/cphalcon/issues/11389
https://github.com/phalcon/cphalcon/issues/582

### CODE REVIEW

**Comment by ruudboon** [comment]
Could we reopen this issue? Looks like it didn't made it to 3.2.x branch.

**Comment by Jurigag** [comment]
I will make it for 3.3

**Comment by ruudboon** [comment]
Is this still on the map for 4.0?

**Comment by niden** [comment]
Implemented in https://github.com/phalcon/cphalcon/pull/14078

**Pull request closed without merging**
