### PR TITLE
Adjusting Persistent To Account For Non-Defined Session Bag

### PR DESCRIPTION
**Pull request by Fenikkusu**
Hello!

* Type: new feature

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Partially testing the waters here. Not sure I'll finish this unless the community thinks I should.

I was working on a personal zephir project that leverages phalcon and kept getting errors when trying to access the `persistent` object. After digging into it, I realized it was related to missing the 'sessionBag' element in the dependency injector. This is an attempt to bridge the gap, along with giving some additional functionality (initialization of persistent).

Note: I've not run any the QA tools yet. As I said, testing the waters.

Thanks

### CODE REVIEW

**Comment by Fenikkusu** [comment]
It occurs to me, Interestingly enough, I never received the 'service not defined' error from the DIC...may need to dig into that further...

**Comment by niden** [comment]
@Fenikkusu do you mind rebasing this with 4.0.x ? I cannot see in the current v4 code why this test would fail...

**Comment by Fenikkusu** [comment]
@niden , I've rebase the PR. Unfortunately I didn't see the e-mail come through on this or I would of done it sooner.

**Comment by niden** [comment]
@Fenikkusu Sorry to be a pain buddy, but can you change the base of this to point to v4.1.x please? 

Also we will need a clear view on what we will do with this, and an issue explaining what we are changing here. I know you wrote that you are testing the waters here so we need to figure this out :)

Also changelog entry :)

**Comment by zsilbi** [comment]
@Fenikkusu if you plan to complete this please let us know.
I have to close this for the time being.

**Pull request closed without merging**
