### PR TITLE
Tidied up Collection class.

### PR DESCRIPTION
**Pull request by SidRoberts**
Hello!

* Type: code quality
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [-] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [-] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

`cancelOperation()` previously did not return a value on success. It now returns `true`.

### CODE REVIEW

**Comment by CameronHall** [comment]
Can we please avoid merging this until after https://github.com/phalcon/cphalcon/pull/14230

**Comment by sergeyklay** [comment]
@CameronHall I would like to not merge #14230 into 4.0.x. What do you think about 4.1.x?

**Review by sergeyklay — APPROVED** [review]

**Comment by CameronHall** [comment]
Now that you mention it, it does seem more appropriate to hold off on #14230 given 4.0.x is already in beta.

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
