### PR TITLE
Phalcon/cache/backend/redis Fix issue with retuned keys by queryKeys

### PR DESCRIPTION
**Pull request by mbrostami**
Hello!
When you have a configuration for `prefix` and `statsKey` you can not retrieve keys correctly by `queryKeys`. It gives you keys with prefix and if you want to delete that key, you have to remove prefix first.

* Type: bug fix | backward incompatible

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
Remove prefix of keys which are storing in a list when using `statsKey` configuration

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
I will keep this open for some time to allow other contributors a chance to speak up, and to take a fresh look at it later. But at the moment it seems good to me.

**Review by sergeyklay — DISMISSED** [review]

**Comment by sergeyklay** [comment]
cc @phalcon/framework-team

**Comment by mbrostami** [comment]
@sergeyklay I forgot to add prefix length into `substr`, and I make some changes again.  
Changes:  
- Replaced `if keyName === null` with `if !keyName` (e.g. keyName='0000')  
- `let prefix = this->_prefix;` is unused, so I deleted them.
- `tt1` variable has typo, changed it to `ttl`

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
