### PR TITLE
Feature | GitHub actions only

### LINKED ISSUE #15390: [NFR]: Move out from Travis/AppVeyor to Github Actions
Move all things that left from this x2 CI's and make it all inside single Github Actions.

### PR DESCRIPTION
**Pull request by AlexNDRmac**
Hello!

* Type: new feature
* Link to issue: #15390

**In raising this pull request, I confirm the following:**

- [X] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [X] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [X] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

- Removed Travis CI build
- Removed AppVeyour CI builds
- Added Github Action for Releases creation

Thanks

### CODE REVIEW

**Comment by AlexNDRmac** [comment]
@niden needs to stop builds (close project) in AppVeyour account.

**Comment by Jeckerson** [comment]
@AlexNDRmac `appveyor` webhooks are now disabled.

**Comment by Jeckerson** [comment]
Also please add `x32` to matrix.

**Review by Jeckerson — APPROVED** [review]

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @AlexNDRmac

**Pull request merged**
