### PR TITLE
Removes unnecessary nested if

### PR DESCRIPTION
**Pull request by Green-Cat**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
It it was my decision we well never use elseif in phalcon :)

**Comment by Green-Cat** [comment]
@andresgutierrez There are several instances of it in the codebase already though.

**Comment by Green-Cat** [comment]
Even in the exact same file, https://github.com/phalcon/cphalcon/blob/c96782766cfe5852acb821af944140379125c1cb/phalcon/db/dialect.zep#L188

**Comment by andresgutierrez** [comment]
I'm not against it, just personal tastes :+1:

**Pull request closed without merging**
