### PR TITLE
[2.0.0] Add __isset magic method to view for view params

### PR DESCRIPTION
**Pull request by onshorechet**
Adds the magic isset method the the view object so that view params can be checked with isset().

ie:
echo isset($this->view->products);

### CODE REVIEW

**Comment by Timethor** [comment]
+1

**Comment by andresgutierrez** [comment]
Could you please rebase against 2.0.0?

**Comment by chet0xhenry** [comment]
With pleasure.

**Comment by chet0xhenry** [comment]
I added the boolean return type in the method declaration, but you don't want the @params and @return in the method comment.  It won't match the style of this file.  It doesn't bother me to do that, I just wanted confirmation.

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
