### PR TITLE
Fixed group overwriting by having

### PR DESCRIPTION
**Pull request by ashpumpkin**

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by ashpumpkin** [comment]
Please don't merge this PR. Group-having check is called 3 times and it does not depend on adapter, I need to remove 2 useless checks.

**Comment by ashpumpkin** [comment]
done

**Comment by sergeyklay** [comment]
:+1:

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
