### PR TITLE
4.0.x test manager construct

### LINKED ISSUE #14933: Phalcon 4, session manager broken with PHP 7.4 (works with PHP 7.2)
PHP version: 7.4.4
Phalcon version: 4.0.5
Installation method : PECL / from sources

Issue: Uncaught Phalcon\Session\Exception: The session adapter is not valid in phalcon/Session/Manager.zep:323

Phalcon\Session\Manager::getAdapter always returns null.

```
<?php

namespace Services;

use Phalcon\Session\Adapter\Libmemcached;
use Phalcon\Session\Manager;
use Phalcon\Storage\SerializerFactory;
use Phalcon\Storage\AdapterFactory;

class Session extends Manager {

	public function __construct() {
 		$serializerFactory = new SerializerFactory();
		$factory = new AdapterFactory($serializerFactory);
		$sessionAdapter = new Libmemcached($factory, [
			'servers' => [
				[
					'host' => 'memcached',
					'port' => 11211,
					'weight' => 1,
				],
			],
			'client' => [],
			'lifetime' => 3600,
		]);

		$this->setAdapter($sessionAdapter);
		// class_implements($sessionAdapter) => [ SessionHandlerInterface ]
		// $this->getAdapter() => null
	}

}
```

This code works with PHP 7.2

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: code quality
* Link to issue: https://github.com/phalcon/cphalcon/issues/14933

Small description of change: This just adds a test for this issue.

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
This looks like zephir issue, will try to add test later, any idea? @sergeyklay @AlexNDRmac @dreamsxin

**Comment by AlexNDRmac** [comment]
I'll try to check this with test in Zephir

**Comment by dreamsxin** [comment]
@sergeyklay In zephir_update_property_zval
```C
if (!ZEPHIR_PROPERTY_IS_PRIVATE(object, property_name)
#if PHP_VERSION_ID >= 70100
	old_scope = EG(fake_scope);
#else
	old_scope = EG(scope);
#endif
}
```

**Comment by ruudboon** [comment]
@Jurigag Can you target this to 4.1?

**Comment by Jurigag** [comment]
Sure, will do it later.

**Comment by zsilbi** [comment]
@Jurigag could you also check this one?
Thanks a lot.

**Comment by Jeckerson** [comment]
@AlexNDRmac any news?

**Comment by Jeckerson** [comment]
Need to check with latest Zephir version.

**Comment by Jeckerson** [comment]
Already fixed.

**Pull request closed without merging**
