### PR TITLE
2.0.x

### PR DESCRIPTION
**Pull request by andresgutierrez**

### CODE REVIEW

**Comment by KorsaR-ZN** [comment]
@andresgutierrez 
Please, NOT merge in `master`, see #10100 
Regression bug in `Phalcon\Paginator\Adapter\Model`, example:

```php
$robots = Robots::find();

$paginator= new Phalcon\Paginator\Adapter\Model([
   'data' => $robots,
   'limit' => 3,
   'page' => 1
]);

$paginate = $paginator->getPaginate();

foreach ($paginate->items as $item) {
   echo $item->id . ',';
}
// echo 1,1,1
```

**Comment by Green-Cat** [comment]
@KorsaR-ZN I think the paginator tests should be strengthened a little. First they didn't catch the last page bug and now this. I'll look into expanding the test suite for it during the weekend.

**Comment by andresgutierrez** [comment]
Probably introduced after: https://github.com/phalcon/cphalcon/pull/10100

**Comment by Green-Cat** [comment]
ping @patrick-zippenfenig

**Comment by KorsaR-ZN** [comment]
@Green-Cat I did improve Paginator tests. I will do the PR after fix #10100

**Comment by patrick-zippenfenig** [comment]
@Green-Cat I'll check #10100 in a few hours. I literally just put my phalcon project into production. Linked in my github profile if someone cares

**Comment by Green-Cat** [comment]
@KorsaR-ZN :+1: More tests is always great.
@patrick-zippenfenig thanks.

**Comment by SidRoberts** [comment]
*Possible* fix: #10251

**Comment by sergeyklay** [comment]
@andresgutierrez Give me an hour if it is possible. It seems I found another bug with model cache. Need test in new clean project.

**Comment by sergeyklay** [comment]
Please see this #10252. I'm not sure, but I think it's a bug

**Comment by SidRoberts** [comment]
Before merging, please see #10277.

**Pull request merged**
