### PR TITLE
#10646 improved translate replacePlaceHolders()

### PR DESCRIPTION
**Pull request by pauliuspetronis**

### CODE REVIEW

**Comment by sergeyklay** [comment]
@andresgutierrez Can you please fix travis config?

**Comment by andresgutierrez** [comment]
Looks much better, I would also change Replacer by Interpolator.

**Comment by sergeyklay** [comment]
@pauliuspetronis Can you please return back indents in `phalcon/translate/adapter/csv.zep` to tabs?

**Comment by pauliuspetronis** [comment]
Yes. I can. But I'm confused a little bit. In one my commit
>@andresgutierrez
>Could you please use PSR-2?

In PSR-2:

> Code MUST use 4 spaces for indenting, not tabs.

Follow PSR-2 or follow partly? :)

**Comment by andresgutierrez** [comment]
@pauliuspetronis Yeah, we need to publish the coding standard for Phalcon in Zephir. This one is based on PSR-2 but it has a couple of differences

**Comment by pauliuspetronis** [comment]
i will return back tabs morning.

**Comment by pauliuspetronis** [comment]
@sergeyklay, @andresgutierrez - done.

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
