### PR TITLE
Add metaDataFileMode option to Phalcon\Mvc\Model\Metadata\Files

### PR DESCRIPTION
**Pull request by ariarijp**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Can you please explain a bit more  what issue can be solved (or what feature can be introduced) with your PR?

**Comment by ariarijp** [comment]
In my case, I'm running Web Application and CLI Task in one server.

The Web server run as "www-data" user, but CLI Task run as other user(e.g. "ubuntu" user).

If Web App creates Metadata file, I guess CLI Task unable to overwrite Metadata file when Metadata is expired.

Thanks for asking.

**Comment by ariarijp** [comment]
@sergeyklay I think this issue is an edge-case.
Should I close this PR?

**Comment by sergeyklay** [comment]
The 2.0.x branch is not longer supported. Could you please resend PR to the 2.1.x

**Pull request closed without merging**
