### PR TITLE
[2.0.x] Fix undefined method call ::getConnectionService

### PR DESCRIPTION
**Pull request by AlexKomrakov**
- Fixed undefined method call `Phalcon\Mvc\Collection\Manager::getConnectionService`

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please check 2.1.0 also?

**Comment by AlexKomrakov** [comment]
Same behavior in 2.1.*. Do I have to create 1 more pull to 2.1.x?

**Comment by sergeyklay** [comment]
Create separated PR to the 2.1.x branch

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
