### PR TITLE
Updated security.zep with fixes and new functionality #10142

### PR DESCRIPTION
**Pull request by agim-a**
submitted #10142 to 2.0.x branch

checkToken function makes sure that tokenKey exists in session, if not provided

 Added a utility function destroyToken to be used when checkToken
returns true

Added a 3rd variable to checkToken
destroyIfValid, which removes token key and value from session

Moved token key and value session ids as protected properties

### CODE REVIEW

**Comment by agim-alb** [comment]
$2a$ means that it is not Legacy, right? Because it is current
So isLegacyHash will return *true* for hashes like md5,sha1 etc. and *false* if crypt hash that starts with $2a$
``` php
isLegacyHash(md5('password')); should return TRUE
```
while

``` php
isLegacyHash('$2a$.....')); should return FALSE
```

Thoughts?

**Comment by andresgutierrez** [comment]
No, it should returns true if the hash starts by $2a$

This is how it's implemented in 1.3.5 https://github.com/phalcon/cphalcon/blob/1.3.5/ext/security.c#L670-L672

**Comment by agim-alb** [comment]
Ok, updated it , so that isLegacyHash returns true, if hash starts with $2a$

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
