### PR TITLE
according to PSR, return camelCase style property [ add to the 2.0.x ]

### PR DESCRIPTION
**Pull request by r3jack**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please rebase?

**Comment by r3jack** [comment]
i rebased  the branch: 2.0.x, but too many conflicts. please give me a guide. thx.

**Comment by Green-Cat** [comment]
This is a BC break for the paginator.

**Comment by sergeyklay** [comment]
@r3jack

**Comment by r3jack** [comment]
Request new pull.

**Pull request closed without merging**
