### PR TITLE
Added Column::TYPE_TIMESTAMP

### LINKED ISSUE #2850: migration problem with TIMESTAMP columns
The command `phalcon migration generate` mapped TIMESTAMP (MySQL) columns to `TYPE_DATE`.
`phalcon migration run` creates a new table with those columns as DATE columns.
http://docs.phalconphp.com/en/latest/api/Phalcon_Db_Column.html
I think `TYPE_TIMESTAMP` may be needed

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/4894281-migration-problem-with-timestamp-columns?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sergeyklay**
Fixed #2850
Refs #10448

### CODE REVIEW

**Comment by andresgutierrez** [comment]
And SQLite?

**Comment by sergeyklay** [comment]
> SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in Date And Time Functions of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values:

> TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").

For example we can't use Column::TYPE_DATETIME and SQLite, nevertheless, we have this column type

**Comment by sergeyklay** [comment]
@andresgutierrez Added missed timestamp type to SQLite adapter

**Comment by Green-Cat** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
