### PR TITLE
Criteria - added new method createBuilder

### PR DESCRIPTION
**Pull request by ovr**
Hey!

Subject:

``` zep
/**
 * Creates a query builder from criteria
 *
 * @return BuilderInterface 
 */
public function createBuilder() {}
```

### CODE REVIEW

**Comment by ovr** [comment]
ping @andresgutierrez

**Comment by ovr** [comment]
Can you review this please?

**Comment by andresgutierrez** [comment]
The test is not testing if the condition passed to the where works or if the model itself is used in the from clause.

**Comment by Green-Cat** [comment]
That would be a nice feature to have.
The commit does currently need a rebase though.

**Comment by ovr** [comment]
Epic)

**Comment by sergeyklay** [comment]
Closing in favor of #12856

**Comment by ovr** [comment]
@sergeyklay Thank you 👍

**Pull request closed without merging**
