### PR TITLE
Update README.md requirement

### PR DESCRIPTION
**Pull request by natinosuke**
Hello!

* Type: documentation
* Link to issue:

Small description of change:
PHP 7.2 added as a README.md requirement.

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.3.x` branch?

**Comment by natinosuke** [comment]
I'm sorry.
It is unfamiliar because it is the first pull request in my life.

Is this OK?

**Comment by Jurigag** [comment]
No, you need to rebase now. Easier just select 3.3.x branch in git and do your changes again and create new pull request.

**Comment by natinosuke** [comment]
Thank you for telling me.
I am very thankful.

I tried again #13284.

**Comment by sergeyklay** [comment]
Closed in favor of #13284

**Pull request closed without merging**
