### PR TITLE
Changed Volt compiler options

### PR DESCRIPTION
**Pull request by dschissler**
Hello!

* Type: new feature
* Link to issue: #13815

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change: 

Changed Volt compiler options with to `compiled` or `compile` prefix to be deprecated. Now use the key without the prefix. I'm simplifying the API.

Thanks

### CODE REVIEW

**Comment by dschissler** [comment]
@niden I have at least two more coming after you take this one.

**Comment by niden** [comment]
@dschissler Changelog please and some tests at least to check for the exceptions :)

Thank you for this work!

**Review by niden — CHANGES_REQUESTED** [review]
Tests/Changelog

**Comment by dschissler** [comment]
@niden I didn't add the change log to the commit.  Also, I'm really puzzled why many lines were changed from starting with "--" to "-".  I don't recall doing anything that could cause that.

**Comment by dschissler** [comment]
I don't know what I would do to write that test.  I'm not that familiar with it.  I was able to get the config merge going since there was a stub there.  How to even detect the use of deprecation notices?  I'd prefer to just move on with my other changes rather than learning the ins and outs of that testing system.  I propose that I can put a bit of time into some of the tests later in the Phalcon cycle.  I have 2.5 PRs ready to go.  One is a cluster fuck of changing many existing tests and I'd prefer to jam on that.

**Comment by dschissler** [comment]
Never mind about the "--" in the change log.  Its a line ending thing.  Its Sunday and I'm still in bed.

**Comment by dschissler** [comment]
@sergeyklay Travis appears to be broken, maybe.  I'm not all that familiar with your whole statck:

```
WARNING: The following packages cannot be authenticated!
  mysql-common libmysqlclient20 libmysqlclient-dev mysql-community-client
  mysql-client mysql-community-server mysql-server
```

**Comment by sergeyklay** [comment]
@dschissler It is Travis' issue on Ubuntu 14.04. I fixed this in https://github.com/phalcon/cphalcon/pull/13835

**Comment by dschissler** [comment]
@sergeyklay I think that I already merged your changes.  Its difficult for me to see that change in this PR though.

@niden If everything is passing now then I'm done with this PR.  I'm not going to write a completely new  unit test for this when there wasn't already one there.  I was just trying to help out with the issues list and I just don't care about this PR al that much.  If you don't want to merge this then I'll set it aside so that I can push through things that I care about.

**Comment by niden** [comment]
I don't understand why you closed this. This is valid code. All we needed was a test or two. Yes there might not be tests in the framework currently covering that but that doesn't stop us from writing one or tow. And this particular functionality can be tested without any crazy setup features, since you only need to test the options themselves.

**Comment by dschissler** [comment]
I closed it because you want to spend more time on it right now than I do and I'm not going to let it clog up my one PR at a time.

**Comment by dschissler** [comment]
I'm working on upgrading my development flow so that I can continue on when I don't want to put more effort into something or I'm waiting for a response.  Another thing is that you can accept these less consequential changes early in an alpha release with the understand that there is plenty of time to write a test.  I personally don't like writing tests for everything and so I'm unmotivated to learn the ins and outs of your setup.  Also I don't have an easy way to run the tests from within my development environement. I have shit loads of other stuff to work on and I'm not interested in learning your docker based setup right this moment.  So I'm writing tests (some of which I simply don't want to write) in the dark with only a mind runtime and PR to test it.

**Comment by dschissler** [comment]
@niden I have the code done for three issues all with their own branches now.  It could be a bit difficult to keep track of them so I'll be adding a word after the issue number for future branches/issues.

https://github.com/dschissler/cphalcon/branches

**Pull request closed without merging**
