### PR TITLE
if no header defined should return null

### PR DESCRIPTION
**Pull request by WhatABigBottleOfPureWater**
isset($req->getHeaders()[ 'abc' ]) To null !== $req->getHeader('abc')

### CODE REVIEW

**Comment by tkaven** [comment]
@racklin what's wrong with AppVeyor? ..

**Comment by sergeyklay** [comment]
How about:
```php
if (!$req->getHeader('abc')) {
    // ...
}
```

Right now it works so. 
Also I think that introducing `hasHeader` is better than changing the current API.

**Comment by tkaven** [comment]
@sergeyklay  yes! introducing hasHeader is better than changing the current API :)  :+1:

**Comment by sergeyklay** [comment]
@tkaven Could you please rebase onto 3.1.x branch

**Comment by sergeyklay** [comment]
@tkaven ping

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/cphalcon/pull/13570

@tkaven Thank you very much for the contribution

**Pull request closed without merging**
