### PR TITLE
Simple credit card validation using luhn algorithm

### PR DESCRIPTION
**Pull request by caiofralmeida**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
There are many commits that don't belong to the PR

**Comment by caiofralmeida** [comment]
I'm sorry, I did the right pull request in phalcon: 2.0.x?

**Comment by andresgutierrez** [comment]
Yes, but it looks a merge origin was done in your fork causing this. I think you can create a new branch from the latest 2.0.x, made your changes there and then re-submit the PR

**Comment by caiofralmeida** [comment]
Ok, I will do that, thank you for your attention.

**Pull request closed without merging**
