### PR TITLE
3.4.x fix getRouteById and add test

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: bug fix | code quality
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
@michanismus @sergeyklay

**Comment by michanismus** [comment]
@Jurigag Why do you use the range() function? If there is no route the function will return an array with the elements [0, -1] what will end in an undefined index error again.
And again, you don't check for a route name in getRouteByName().

My suggestion, use my code I posted:

```
    protected _keyRouteNames = [] { get, set };

    protected _keyRouteIds = [] { get, set };

    /**
     * Returns a route object by its id
     */
    public function getRouteById(var id) -> <RouteInterface> | boolean
    {
        var route, routeId, key;

        if empty this->_routes {
            return false;
        }

        if fetch key, this->_keyRouteIds[id] {
            return this->_routes[key];
        }

        for key, route in this->_routes {
            let routeId = route->getRouteId();
            let this->_keyRouteIds[routeId] = key;

            if routeId == id {
                return route;
            }
        }

        return false;
    }

    /**
     * Returns a route object by its name
     */
    public function getRouteByName(string! name) -> <RouteInterface> | boolean
    {
        var route, routeName, key;

        if empty this->_routes {
            return false;
        }

        if fetch key, this->_keyRouteNames[name] {
            return this->_routes[key];
        }

        for key, route in this->_routes {
            let routeName = route->getName();
            if !empty routeName {
                let this->_keyRouteNames[routeName] = key;

                if routeName == name {
                    return route;
                }
            }
        }

        return false;
    }

```

**Comment by Jurigag** [comment]
Well, `Phalcon\Mvc\Router::getRouteById` is kind of pointless since `Phalcon\Mvc\Router\Route` doesn't have `getId()` method or i miss something?

**Comment by Jurigag** [comment]
@michanismus i guess it;'s okay now?

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you

**Comment by Jurigag** [comment]
Well actually you are right about range, i forgot about this.

**Pull request merged**
