### PR TITLE
[2.0.x] Fix for #10131

### PR DESCRIPTION
**Pull request by KorsaR-ZN**
see #10131

### CODE REVIEW

**Comment by sergeyklay** [comment]
:+1: 

but now we have  +1 dependence

**Comment by KorsaR-ZN** [comment]
@sergeyklay 
Maybe it is better?
```
...
let method = "get" . this->_camelize(property);
...
protected function _camelize(string! str) -> string
{
   return Text::camelize(str);
}
```

**Comment by sergeyklay** [comment]
yes  it is better?

**Comment by phalcon** [comment]
Why an extra method just to call a method?

**Comment by KorsaR-ZN** [comment]
@phalcon That's better, code becomes more flexible

```
....

protected function getGettersProperty(string! str) -> string
{
    return "get" . Text::camelize(str);
}

....

let method = this->getGettersProperty(property);

....
```

**Comment by andresgutierrez** [comment]
Why an extra method just to call a method???

**Comment by KorsaR-ZN** [comment]
@andresgutierrez So anyone can change logic create getters for property

**Comment by andresgutierrez** [comment]
How often do you change how getters look like? Most applications just have get + name field, what would be a different common case?

**Comment by KorsaR-ZN** [comment]
@andresgutierrez I agree with you. But I think better to leave the last option. So the code is improved.
An extra method is not slowing code.

Or do you think I should do reset?

**Comment by andresgutierrez** [comment]
@KorsaR-ZN Could you please remove that method?

**Comment by KorsaR-ZN** [comment]
@andresgutierrez I have to do rebase?

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
