### PR TITLE
Rewritten Phalcon\Logger\Multiple to make it consistent with Phalcon\Logger\AdapterInterface

### PR DESCRIPTION
**Pull request by evolic**
Hello!

* Type: code quality
* Link to issue: https://github.com/phalcon/cphalcon/issues/13256

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

**Small description of change**:

I rewritten _Phalcon\Logger\Multiple_ to make it consistent with _Phalcon\Logger\AdapterInterface_ 

**Do I need to write unit tests for this modification?**

Not only checking
```php
if ($multipleStreamAdapter instanceof Phalcon\Logger\AdapterInterface)
```
but also testing it's previous and new functionality e.g. handling transaction?

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
1. We don't accept changes to master
2. This is possibly breaking change so please send it to 4.0.x branch
3. Multiple as far as i know is not itself Adapter for logger, it's just something like a Bag for multiple loggers.

**Comment by evolic** [comment]
@Jurigag My change was made as following with forum:
https://forum.phalconphp.com/discussion/17617/why-class-phalconloggermultiple-does-not-implement-phalconlogger

I am writing code for PHP 7.2 (7.0 is not as good as the latest version with it's changes) and trying to use type hinting as much as possible. When I was working with logger I could use _Phalcon\Logger\AdapterInterface_ but _Multiple_ class was not implementing it (it was like a Bag as you mentioned) and was causing errors.

I will fix target branch with new fix using 4.0.x
I will try to write unit tests too.

Can I find some details about this new version? What features will be added, etc?

**Comment by Jurigag** [comment]
Just check changelog and find issues and prs tagged with 4.0.x

**Comment by evolic** [comment]
@Jurigag As I noticed Multiple does not have to implement _logInternal()_ method.
It just pushes any logs forward to attached loggers.

Here is sample code to check this class in CLI.

```php
<?php
namespace Sandbox;

use Phalcon\Logger;
use Phalcon\Logger\Multiple as MultipleStream;
use Phalcon\Logger\AdapterInterface;
use Phalcon\Logger\Adapter\File as FileAdapter;
use Phalcon\Logger\Adapter\Stream as StreamAdapter;

$logger = new MultipleStream();

$fileLogger = new FileAdapter('./test.log');
$streamLogger = new StreamAdapter('php://stdout');

$logger->push($fileLogger);
$logger->push($streamLogger);

$logger->log(
    "This is a message"
);

$logger->log(
    "This is an error",
    Logger::ERROR
);

$logger->error(
    "This is another error"
);

$loggers = [
	'FileLogger' => $fileLogger,
	'StreamLogger' => $streamLogger,
	'MultipleLogger' => $logger,
];

foreach ($loggers as $name => $_logger) {
	if ($_logger instanceof AdapterInterface) {
		$logger->info($name . ' is an instance of AdapterInterface');
	} else {
		$logger->emergency($name . ' is not an instance of AdapterInterface');
	}
}
```

**Comment by evolic** [comment]
@Jurigag And if we are talking about errors I was adapting this class:
https://github.com/phalcon/incubator/blob/1.3.0/Library/Phalcon/Db/Profiler/QueryLogger.php
to my project.

Constructor was like this:
```php
    /**
     * QueryLogger constructor.
     *
     * @param \Phalcon\Logger\LoggerAdapterInterface      $logger   optional, \Phalcon\Logger\LoggerAdapterInterface instance, defaults to Firephp adapter.
     * @param \Phalcon\Db\Profiler $profiler optional, \Phalcon\Db\Profiler instance
     * @param int                  $priority optional, defaults to \Phalcon\Logger::DEBUG
     */
    public function __construct(
        \Phalcon\Logger\LoggerAdapterInterface $logger = null,
        \Phalcon\Db\Profiler $profiler = null,
        $priority = \Phalcon\Logger::DEBUG
    ) {
        $this->logger = $logger;
        if (!$this->logger) {
            $this->logger = new \Phalcon\Logger\Adapter\Firephp();
        }
        $this->profiler = $profiler;
        if (!$this->profiler) {
            $this->profiler = new \Phalcon\Db\Profiler();
        }
        $this->priority = $priority;
    }
```
but _Multiple_, when provided to this class, does not implement this interface so I encountered error.

I changed it to not set type for the _$logger_ temporarily.

Previously there was used _\Phalcon\Logger_ - I don't know why.

And frankly speaking... my code is not really mine from the ground - it bases on _Phalcon\Logger\Adapter_ - logger abstract class.

**Comment by Jurigag** [comment]
Yea but multiple itself is not a logger, as i wrote already - it's a bag for loggers.

**Comment by niden** [comment]
@evolic Thank you for the work. With the new PSR-3 implementation the Multiple adapter has been removed since now the main logger offers multiple adapter logging capabilities.

https://github.com/phalcon/cphalcon/pull/13636

Closing

**Pull request closed without merging**
