### PR TITLE
Added CLI interfaces.

### PR DESCRIPTION
**Pull request by SidRoberts**
Not exactly ground-breaking but I thought the CLI classes should have interfaces to match the MVC classes.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Looks good to me. @andresgutierrez ?

**Comment by sergeyklay** [comment]
Can you please rebase?

**Comment by SidRoberts** [comment]
@sergeyklay Rebased.

**Comment by sergeyklay** [comment]
@SidRoberts Could you please rebase again?

**Comment by SidRoberts** [comment]
@sergeyklay Rebased. :smile:

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
