### PR TITLE
[2.0.x] [NFR] Added events response:beforeSendHeaders, response:afterSendHeaders

### PR DESCRIPTION
**Pull request by KorsaR-ZN**
see #10689

### CODE REVIEW

**Comment by andresgutierrez** [comment]
I think this event should be in Mvc\Application instead of here

**Comment by iotch** [comment]
@andresgutierrez Response events is useful when using the component stand-alone. For example if I don't need a full-stack Mvc\Applcation, and only a request, router, dispatcher and response. Router and dispatcher are sending events, will be great to have the response to.

**Comment by KorsaR-ZN** [comment]
@iotch :+1:

**Comment by KorsaR-ZN** [comment]
@andresgutierrez 

Quote from the docs:
>  What is Phalcon?
 ....
Phalcon also is loosely coupled, allowing you to use its objects as glue components based on the needs of your application.


If the event is moved `Mvc\Application`, it will not be able to use `Http\Response` as not dependent component.

**Comment by iotch** [comment]
@andresgutierrez Please, accept the request, no one else has commented against this change and this will not break anything

**Pull request closed without merging**
