### PR TITLE
T13825 view tostring

### PR DESCRIPTION
**Pull request by niden**
Hello!

* Type: new feature
* Link to issue: #13825 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Added `Phalcon\Mvc\View::toString()` to return the rendered view as a string

Thanks

### CODE REVIEW

**Comment by niden** [comment]
cc @sergeyklay

**Comment by niden** [comment]
Made a mistake when creating the branch hence the extra files. I will sort out the ext folder in 4.x branch

**Comment by SidRoberts** [comment]
How about adding '__toString()' as well?

**Comment by niden** [comment]
@SidRoberts not sure if we can do that since we need some parameters for the `toString()`. From what I know `__toString()` does not accept any, unless I am mistaken.

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
@SidRoberts I don't support the idea of adding `__toString` method. First of all `__toString` is not designed for humans. It acts as a magic method because for the most part it is don't get called explicitly but rather intercept operations. Unfortunately there are limits to its magic, specifically the only "context" the method is aware of is its design contract: to return a string. But its not clear what purpose that is. Should this be for some internal debugging or logging purposes? Secondly, you cannot throw an exception from within a `__toString` method. Doing so will result in a _fatal error_. It is by design. If you give users today `__toString`, then tomorrow they will start using it in situations where exceptions will theoretically occur. So it will yet another ability to get fatal error using Phalcon. Let's use principle of least astonishment as long as we can.

**Pull request merged**
