### PR TITLE
[2.0.x] Added options for cookie parameters. Removed DocBlock, and more...х

### PR DESCRIPTION
**Pull request by KorsaR-ZN**
Update `Phalcon\Session\Adapter`, `Phalcon\Session\AdapterInterface` and also full coverage of the tests... And more improvements...

_Added public method:_
- `getOption()`
- `getCookieParams()`
- `setCookieParams()`
- `setName()`
- `getName()`
- `regenerateId()`
- `reset()`
- `commit()`
- `abort()`
- `clear()`
- `status()`
- `encode()`
- `decode()`

_Added protected method_
- `configure()`
- `legacySessionReset()`
- `legacySessionAbort()`
- `legacySessionStatus()`

_Added options:_
- name (session name) 
- cookie_lifetime
- cookie_path
- cookie_domain
- cookie_secure
- cookie_httponly

_`Phalcon\Session\Adapter\Files` added options:_
- savePath

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by KorsaR-ZN** [comment]
@andresgutierrez ?

**Comment by andresgutierrez** [comment]
Could you please move the CHANGELOG to 2.0.2, also this need rebase

**Comment by KorsaR-ZN** [comment]
@andresgutierrez Rebased

**Comment by KorsaR-ZN** [comment]
@andresgutierrez Rebased

**Comment by KorsaR-ZN** [comment]
@andresgutierrez Why not merge?

**Comment by KorsaR-ZN** [comment]
@andresgutierrez ping

**Comment by KorsaR-ZN** [comment]
@phalcon ping

**Comment by KorsaR-ZN** [comment]
@phalcon, @andresgutierrez 
What's the problem with this PR why not merge it?

**Comment by ErickSkrauch** [comment]
+1

**Comment by Green-Cat** [comment]
@phalcon Could this be merged please?

**Comment by sergeyklay** [comment]
+1

**Pull request closed without merging**
