### PR TITLE
[2.0.0] #3135 #3213 & Skip model saving.

### PR DESCRIPTION
**Pull request by KoriSeng**
anyone got a good git tutorial?

### CODE REVIEW

**Comment by ovr** [comment]
> anyone got a good git tutorial?
http://git-scm.com/book/en/v2

**Comment by maxgalbu** [comment]
if you're on windows or mac, I recommend using [SourceTree](http://www.sourcetreeapp.com/) which got me started with git, it eases the creation of branches, reversion of commts, etc...

(ps: you are editing a c file which is unrelated :)

**Comment by 7thcubic** [comment]
Edited that previously before ovr told me its auto generated. Cant help it. Github interface cant revert it for nuts. 

Side notes:
Have you guys noticed during print_r the config and di object is recursively found? Especially the config object it is created everytime ur anon function is targetted. 

I fixed the issue on my side by passing it as a reference using use(&$config) or another way is to use phalcon di default->config and set config as a shared service. 

Another side note about injectable services. 
I have an idea to rewrite all of the services to instead of saving a pointer to the di by default and instead only save the explictly user defined di. And return phalcon di default static instead or use it in itself. The code would seem longer also there will be more cpu calls instead of memory. 

In terms of big project deployment, what's the opinion? Since i am pretty new on the block i still have no clue how zend/zephir/native php works in that matter especially on a production project. 

In terms of small scale web i would say memory consumption is better den cpu?
And on a big project where traffic hits maybe what a million request a min? How does that pan out? Still memory > cpu? Cause i feel a retrieve static call from phalcon di default shldnt take more than a few extra cycles?

**Comment by 7thcubic** [comment]
boy i figured something out,
origin = my clone in git.

i tot origin = cphalcon/2.0.0

**Comment by maxgalbu** [comment]
what does "tot" mean? phalcon/cphalcon should be upstream in your repo, not origin

- your local git clone is not a remote so let's call it `local`
- your repo on github (https://github.com/7thcubic/cphalcon) is `origin`
- phalcon's repo (https://github.com/phalcon/cphalcon) is `upstream`.
- you should use a branch for your pull request, otherwise you can't easily get the changes from the upstream repo.

A remote is a repository on the internet. You can have as many remotes as you want. Everything that is on github is remote.

You should use a branch for each fix you provide.

You're still including too many changes in a single pull request:
- some changes for getBestLanguages(): https://github.com/7thcubic/cphalcon/commit/0f50773a0814c7e800aebbd0c4247023d3fd5a0b
- some changes to model.zep (skip model saving?)

Follow these instructions:

```bash
#IMPORTANT: Copy these files MANUALLY to a location out of your repository, 
#so you can save your changes and reintegrate them later
#- phalcon/db/dialect/mysql.zep
#- phalcon/mvc/model.zep
#- phalcon/http/request.zep
#- unit-tests/DbDialectTest.php

#Do the following commands from the root of your repo

#This will add the upstream repo to your repo
git remote add upstream https://github.com/phalcon/cphalcon.git

#Revert your changes to the 2.0.0 branch, until this commit: 
#https://github.com/phalcon/cphalcon/commit/4f81c42c7b94188eaa1edf0e3e296f70ff8af3e8
git reset --hard 4f81c42c7b94188eaa1edf0e3e296f70ff8af3e8

#Force the push to origin to delete the commits on the 2.0.0 branch
git push -f origin

#This will create a branch for a SINGLE fix. 
#This is a branch for your fix for Mysql's CREATE TABLE
git checkout -b "2.0.0_mysql-create-table"

#Paste in your local repository (overwriting the existing files) ONLY these two files:
#- phalcon/db/dialect/mysql.zep
#- unit-tests/DbDialectTest.php

#Add the files and commit your changes
git add phalcon/db/dialect/mysql.zep unit-tests/DbDialectTest.php
git commit -m "Fix reference schema on create"

#Push your changes to origin
git push -u origin "2.0.0_mysql-create-table"

#Go to github.com/7thcubic/cphalcon and create a pull request 
#using the branch "2.0.0_mysql-create-table"
#This fix is done!
```

Now, for every other fix, you can start with these instructions:

```bash
#This will create a branch for a SINGLE fix. 
#This is a branch for your fix for getBestLanguage()
git checkout -b "2.0.0_getbestlanguage-dialect"

#Paste in your local repository (overwriting the existing files) ONLY this file:
#- phalcon/http/request.zep

#Add the files and commit your changes
git add phalcon/http/request.zep
git commit -m "Fix #3135: allow Request::getBestLanguage() to return language without dialect"

#Push your changes to origin
git push -u origin "2.0.0_getbestlanguage-dialect"

#Go to github.com/7thcubic/cphalcon and create a pull request 
#using the branch "2.0.0_getbestlanguage-dialect"
#Done!
```

**Pull request closed without merging**
