### PR TITLE
Update micro.zep in order to fix 'after' Middleware not stopping execution flow..

### PR DESCRIPTION
**Pull request by stamster**
Reference: https://forum.phalconphp.com/discussion/6347/canceling-route-execution-with-micros-before-middleware

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`

**Comment by stamster** [comment]
OK Sergey. :+1: 

I don't commit that often, so this was quick try to fix this issue.

**Comment by stamster** [comment]
Is there a way to edit pull request category?

**Comment by SidRoberts** [comment]
@stamster, There isn't a way to change the branch. You'll have to checkout 2.1.x, manually recreate the commit and then create another pull request.

**Pull request closed without merging**
