### PR TITLE
fixed skipping application/x-www-form-urlencoded in getPut()

### PR DESCRIPTION
**Pull request by sinbadxiii**
Hello!

* Type: bug fix 
* Link to issue: https://github.com/phalcon/cphalcon/issues/16519

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

I have fixed it, it doesn't look as nice as before, but it works any content type now :)

Thanks

### CODE REVIEW

**Comment by niden** [comment]
@sinbadxiii Can you please target the v5.0.x branch? I will make another PR to update the 5.4.x branch with the latest changes.

**Comment by sinbadxiii** [comment]
> @sinbadxiii Can you please target the v5.0.x branch? I will make another PR to update the 5.4.x branch with the latest changes.

exactly! I missed a little :) I have changed the branch

**Comment by niden** [comment]
@sinbadxiii we have a conflict - it shows the changelog and a postgres file not being updated properly. Maybe if you pull and rebase?

**Comment by sinbadxiii** [comment]
> @sinbadxiii we have a conflict - it shows the changelog and a postgres file not being updated properly. Maybe if you pull and rebase?

@niden is it better now?

**Review by niden — APPROVED** [review]

**Pull request merged**
