### PR TITLE
Factory loaders

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/11001

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: This is adding factory loaders for all possible classes which have any adapters. So you can load adapters using config files for example etc.

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
Okay finally compiled, need to write tests which will cover use cases nicely. Also i added factory for all adapters. But i highly doubt in use cases of `Phalcon\Paginator\Factory`, `Phalcon\Image\Factory`, tell me guys what you think if i should remove those factories from this PR or not.

**Comment by Izopi4a** [comment]
i see no harm to let them stay there.

**Comment by Jurigag** [comment]
Yea but with paginator factory the problem is it requires something builder/data thing and when creating paginator you pretty much already know what paginator you want to use. Well i guess it can stay here for now.

**Comment by Jurigag** [comment]
Tests added.

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
I will keep this open for a some time to allow other contributors a chance to speak up, and to take a fresh look at it later. But at the moment it seems good to me.

**Comment by sergeyklay** [comment]
Cc: @niden @andresgutierrez

**Comment by Jurigag** [comment]
Needed to switch to isset instead of fetch, doesn't seem zephir fetch to work with arrayaccess interface.

**Comment by Jurigag** [comment]
rebased @sergeyklay

**Comment by sergeyklay** [comment]
@phalcon/framework-team Could you please take a look

**Comment by sergeyklay** [comment]
Thanks you

**Comment by Jurigag** [comment]
Yea i know update docs now.

**Pull request merged**
