### PR TITLE
Form::clear() now correctly clears single fields

### PR DESCRIPTION
**Pull request by SidRoberts**
Hello!

* Type: bug fix | code quality
* Link to issue: #14217

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [-] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Thanks

### CODE REVIEW

**Comment by scrnjakovic** [comment]
The issue I reported in #14217 is for 3.4.x version, I don't think it applies to 4.0  as `Form::clear()`, `Element::clear()`, `Form::getValue()` and `Element::getValue()` methods were re-written for 4.0 in #13500.

**Comment by SidRoberts** [comment]
@scrnjakovic I've added another PR (#14219) for `3.4.x`.

**Review by sergeyklay — APPROVED** [review]
:heart:

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
