### PR TITLE
Adding addServers method to enable pool of servers for memcache

### PR DESCRIPTION
**Pull request by jaskaransingh156**
Adding addServers method to enable pool of servers for memcache

### CODE REVIEW

**Comment by aleksandrzen** [comment]
We don't add changes to `master`, could you please submit this to the `2.1.x` branch?
Also, we don't change `.zep` files directly.

**Comment by SidRoberts** [comment]
\* We don't change .zep.c files directly. We **do** change .zep files (found in phalcon/).

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md

**Comment by jaskaransingh156** [comment]
Thanks aleksandrzen, SidRoberts and sergeyklay for your guidance. I have submitted this to the 2.1.x branch now. I have made changes in phalcon/cache/backend/memcache.zep. Also, i had earlier missed "persistent" parameter in addServers method. I have added it too. It is following pull request:

https://github.com/phalcon/cphalcon/pull/11474

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`

**Pull request closed without merging**
