### PR TITLE
di support custom adapter

### PR DESCRIPTION
**Pull request by cq-z**
Hello!

Type: new feature
Link to issue:
di support custom adapter ，compatibly to swoole context of coroutine or recover context

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

di support custom adapter ，compatibly to swoole context of coroutine or recover context

### CODE REVIEW

**Comment by Jurigag** [comment]
Could you add some tests for it? Also rebase to resolve changelog conflict. Also why exactly would someone need it for swoole? Can you show any example of code when other adapter would be required?

**Comment by cq-z** [comment]
@Jurigag OK，is support the swoole coroutine。like  run phalcon in coroutine ，i need get di 

```
       $coroutineId = SwooleCoroutine::getCid();
        //协程情况下使用进程ID区分上下文
        if ($coroutineId > 0) {
            return !empty($this->_default[$coroutineId]);
        } else {
            return !empty($this->_default);
        }
```

**Comment by Jurigag** [comment]
Oh, so each coroutine can have their own DI instance? Makes sense then. So rebase it if you can add maybe some tests?

**Comment by cq-z** [comment]
ok, please give me a moment 。

**Comment by cq-z** [comment]
@Jurigag hi,this test case is ok? but windows install packages is error！

**Comment by cq-z** [comment]
image
image

**Comment by Jurigag** [comment]
Yea looks good, windows error is not related and needs to be fixed.

**Comment by cq-z** [comment]
> Yea looks good, windows error is not related and needs to be fixed.

Do i need to do something？

**Comment by Jurigag** [comment]
@ruudboon

**Pull request closed without merging**
