### PR TITLE
fixed bug for phalcon/mvc/collection and phalcon/image/adapter/imagick

### PR DESCRIPTION
**Pull request by youyoubao**
Hello!

* Type: bug fix 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
 fixed bug for phalcon/mvc/collection and phalcon/image/adapter/imagick

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
We don't accept PRs to master repo, please send it to 3.1.x, also update changelog and provide some test that issue is fixed.

**Comment by sergeyklay** [comment]
@dormscript It's technically not a bug. Actually `Imagick::getVersion` is static: https://github.com/mkoppanen/imagick/search?l=PHP&q=getVersion

Nevertheless, we can do it the way you suggest. In any case, as noted @Jurigag , we don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.1.x` branch?

Also I would like to have 2 separate PR for this:  Imagick and Collection

**Comment by Jurigag** [comment]
As you see testa are failing, are you sure you wanted to do this change for collection? Keep in mind that existing collection in phalcon is only for using with php 5, for php7 there are classes in incubator https://github.com/phalcon/incubator maybe there you mean this change?

**Comment by dormscript** [comment]
@sergeyklay Thanks for you attention！
About Imagick extends，in my systems , the method "Imagick::getVersion()" show the error "PHP Strict Standards:  Non-static method Imagick::getversion() should not be called statically". As you say，“Imagick::getVersion is static”，you are right , buy don't work in my system.  I'll find ou the error in my system.

**Comment by dormscript** [comment]
I'll do 2 separate PR for this: Imagick and Collection,thanks

**Comment by dormscript** [comment]
@Jurigag @sergeyklay   
 Current phalcon/mvc/collect  is only adapt to the php extend 'mongo', not adapt 'mongodb' ?

**Comment by Jurigag** [comment]
@dormscript Yes, for mongodb you must use classes from incubator.

**Comment by dormscript** [comment]
Thanks ,I'll try

**Pull request closed without merging**
