### PR TITLE
Phalcon\Db\Adapter::insert build bas data types array

### PR DESCRIPTION
**Pull request by olivier-monaco**
See #6788

### CODE REVIEW

**Comment by andresgutierrez** [comment]
But this removes the bind types that come from parameters

**Comment by olivier-monaco** [comment]
The array is then built by the following for. See line 335 where bindDataTypes is effectively build, field by field.

Keeping the initialization results in duplicate types.

**Comment by olivier-monaco** [comment]
Probably same problem in update function... I need to test.

Are you okay with my pull request?

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
