### PR TITLE
fixed. threw RuntimeException, if db:beforeQuery() returned false

### PR DESCRIPTION
**Pull request by kanehama**
Hello!

* Type: bug fix

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:
threw RuntimeException, if db:beforeQuery() returned false

Thanks

### CODE REVIEW

**Comment by kanehama** [comment]
https://docs.phalconphp.com/ar/3.2/db-layer#events 

"beforeQuery" supported stop operation. "YES"

**Comment by sergeyklay** [comment]
@kanehama Could you please submit this PR to the 3.2.x branch? I'll cherry-pick it to the 4.0.x a bit later. Also update please the `CHANGELOG.md`. Thank you for contributing!

**Comment by kanehama** [comment]
Thank you for checking.
I changed it, is this OK?

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
