### PR TITLE
Fix allow empty string functionality

### PR DESCRIPTION
**Pull request by NikolasSumrak**
Hello!

* Type: bug fix 
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
In model.zep at 2104 line:
```if isset emptyStringValues[field]```
if we have array $array = ['field' => null]; - function isset returns false!

*Steps for reproducing*
1. Have model
```php
class ModelWithField extends \Phalcon\Mvc\Model
{
    protected $field;

    protected function initialize()
    {
        $this->allowEmptyStringValues([
            'field'
        ]);
    }
}
```
2. Have mysql table
```sql
create table `model_with_field` (
   `field` VARCHAR(255) NOT NULL
)
```
3. Have config
```ini
phalcon.orm.not_null_validations = On
phalcon.orm.exception_on_failed_save = On
```
4.
```php
$model = new ModelWithField();
$model->save([
    'field' => ''
]); // return false and throws ValidationFailed exception
```

Thanks

### CODE REVIEW

**Review by sergeyklay — CHANGES_REQUESTED** [review]
You need to update `DbDescribeTest::testDbSqlite`, `MysqlTest::testListTables` and `PostgresqlTest::testListTables`.

Also could you please update change log.

**Comment by sergeyklay** [comment]
@NikolasSumrak ping :)

**Comment by NikolasSumrak** [comment]
@sergeyklay give me more time for it ;) at the moment i very busy at my work ((

**Comment by sergeyklay** [comment]
@NikolasSumrak No problem. Note: you'll need to rebase your branch onto 3.3.x due to conflicts

**Comment by NikolasSumrak** [comment]
@sergeyklay so pull request is into 3.3.x now. I need something else to do?

**Comment by sergeyklay** [comment]
@NikolasSumrak In fact, there have already been changes in the 3.3.x branch. This PR has conflicts with current 3.3.x branch that must be resolved. For example:

**Step 1**: From your project repository, check out a new branch and test the changes.
```sh
git checkout -b NikolasSumrak-hotfix/fix-allow-empty-string-in-model 3.3.x
git pull https://github.com/NikolasSumrak/cphalcon.git hotfix/fix-allow-empty-string-in-model
```

**Step 2**: Merge the changes and update on GitHub.
```sh
git checkout 3.3.x
git merge --no-ff NikolasSumrak-hotfix/fix-allow-empty-string-in-model
git push origin 3.3.x
```

**Comment by sergeyklay** [comment]
Finally squash commits into a single commit to keep the history clean :)

**Comment by NikolasSumrak** [comment]
@sergeyklay round 3.... fight! https://github.com/phalcon/cphalcon/pull/13178 ;)

**Pull request closed without merging**
