### PR TITLE
[4.0.0] Strengthened parameter/return types

### PR DESCRIPTION
**Pull request by SidRoberts**

### CODE REVIEW

**Comment by sergeyklay** [comment]
4.0.0 but sent to 3.0.x?

**Comment by Jurigag** [comment]
Like the rest of his PRs with 4.0.0.

**Comment by SidRoberts** [comment]
There isn't a 4.0.x branch. It's possible to change it within the PR: 
image

I'm getting these PRs ready now because I have spare time now but I'm going to become very busy in a few weeks.

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
