### PR TITLE
Fix ManyToMany select query across multiple schemas

### PR DESCRIPTION
**Pull request by alrieckert**
Hello!

Same bug fix PR as 
https://github.com/phalcon/cphalcon/pull/14715
Just for v4.0.x

Thanks

### CODE REVIEW

**Comment by ruudboon** [comment]
@alrieckert Thank you. Could you add a test for this as well?

**Comment by alrieckert** [comment]
> @alrieckert Thank you. Could you add a test for this as well?

Yes, I'll read through the testing documentation and try to add a test for this

**Comment by ruudboon** [comment]
@alrieckert No problem. Thnx for the pull. 
@niden @Jeckerson I wanna try to get this in for 4.0.3. Besides change log we need a test for this. Probably I can do this tomorrow. But if somebody else has time... :D

**Review by ruudboon — APPROVED** [review]

**Comment by Jeckerson** [comment]
@alrieckert Could you provide some code example?

**Comment by alrieckert** [comment]
> @alrieckert Could you provide some code example?

Hi Jeckerson,

Please see below a stripped down version of my models and a simple select query.

Basically I have 2 DB schemas:

**Schema: hardware**
Contains all the hardware and hardware related tables

**Schema: app**
Contains all my application specific tables

For this example, I have various _devices_ in the hardware schema that links to _sites_ in the app schema via the _device_to_site_ table in the app schema

```php
namespace App\Model\Device;

use App\Model\Site\Site;
use App\Model\Device\DeviceToSite;

class Device extends \Phalcon\Mvc\Model
{
    public function columnMap()
    {
        return [
            'device_id'                 => 'id',
            'device_serial'             => 'serial',
            'device_name'               => 'name'
        ];
    }

    public function initialize()
    {
        $this->setSource('device');
        $this->setSchema('hardware');

        $this->hasMany('id', DeviceToSite::class, 'device_id');
        $this->hasManyToMany('id', DeviceToSite::class, 'device_id', 'site_id', Site::class, 'id');
    }
}
```
```php
namespace App\Model\Device;

use App\Model\Device\Device;
use App\Model\Site\Site;

class DeviceToSite extends \Phalcon\Mvc\Model
{
    public function columnMap()
    {
        return [
            'device_id'         => 'device_id',
            'site_id'           => 'site_id'
        ];
    }

    public function initialize()
    {
        $this->setSource('device_to_site');
        $this->setSchema('app');

        $this->belongsTo('device_id', Device::class, 'id');
        $this->belongsTo('site_id', Site::class, 'id');
    }
}
```

```php
namespace App\Model\Site;

class Site extends \Phalcon\Mvc\Model
{
    public function columnMap()
    {
        return [
            'site_id'           => 'id',
            'site_name'         => 'name'
        ];
    }

    public function initialize()
    {
        $this->setSource('site');
        $this->setSchema('app');
    }
}
```

My MySQL connector points to the **hardware** schema by default
```php
use Phalcon\Db\Adapter\Pdo\Mysql;

$config = [
    "host"     => "localhost",
    "dbname"   => "hardware",
    "port"     => 3306,
    "username" => "demo",
    "password" => "demo",
];

$connection = new Mysql($config);
```

A sample query would then look like this to get all the devices belonging to the site with ID 1

```php
use App\Model\Device\Device;
use App\Model\Device\DeviceToSite;
use App\Model\Site\Site;

$devices = $this
    ->modelsManager
    ->createBuilder()
    ->from(Device::class)
    ->join(Site::class, '[' . Site::class . '].id = 1')
    ->getQuery()
    ->execute();    
```

Everything is working fine when the tables are in the same schema. Only when the tables are spread across multiple schemas, the query doesn't fully reference the intermediate model's schema, but rather uses the default schema as setup in the config

This PR seems to fix the issue in my application 

Please let me know should you require more code or examples

**Comment by niden** [comment]
@Jeckerson if you have some time can you set up a test for this so that we can merge this?

@alrieckert Thank you for the contribution

**Comment by jenovateurs** [comment]
I'm on it ;-)

**Pull request merged**
