### PR TITLE
T13655 DI::getServices unit tests

### PR DESCRIPTION
**Pull request by emiliodeg**
Hello!

* Type: code quality
* Link to issue: #13655 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:
I just added DI::getServices unit tests
Thanks

### CODE REVIEW

**Comment by emiliodeg** [comment]
As I thought there is a problem with zephir and `unset` on arrays

[Di::remove()](https://github.com/phalcon/cphalcon/blob/master/phalcon/Di.zep#L517) doesn't work as expected

**Comment by emiliodeg** [comment]
Here the Zephir bug https://github.com/phalcon/zephir/issues/1259

**Comment by Jurigag** [comment]
Can you reproduce code with zephir and post it to zephir repository?

**Comment by emiliodeg** [comment]
> Can you reproduce code with zephir and post it to zephir repository?

We're dragging this error for 3 years https://github.com/phalcon/zephir/issues/1259

**Comment by sergeyklay** [comment]
@emiliodeg Try again after https://github.com/phalcon/cphalcon/pull/14191

**Comment by sergeyklay** [comment]
Declaration of:
```php
Phalcon\Validation\ValidatorComposite::validate(Phalcon\Validation\Validation $validation, $field): bool
```
must be compatible with
```php
Phalcon\Validation\Validator::validate(Phalcon\Validation $validation, $field): bool 
```
Declaration of 
```php
Phalcon\Validation\Validator\File::getValidators()
```
must be compatible with 
```php
Phalcon\Validation\ValidatorCompositeInterface::getValidators(): array
```
Declaration of:
```php
Phalcon\Validation\Validator\StringLength::getValidators()
```
must be compatible with
```php
Phalcon\Validation\ValidatorCompositeInterface::getValidators(): array 
```


and so on

**Comment by niden** [comment]
@emiliodeg can you rebase this please?

**Comment by emiliodeg** [comment]
Yes I'm working on it

**Comment by emiliodeg** [comment]
Well the `unset` bug is still there

**Comment by sergeyklay** [comment]
I did'n see any segfault. Are you sure about unset bug?

**Comment by emiliodeg** [comment]
I've been making some tests but I still getting problems
```zep
namespace Phalcon;

class Test {

    public function __construct()
    {
        var a, key;
        array b = [];

        // a like a var
        let a["key"] = 1234;
        var_dump(a, count(a)); // get UNKNOWN and 1

        unset a["key"];
        var_dump(a, count(a));  // get UNKNOWN and 1 <<< must be 0

        let key = "other";
        let a[key] = "bar";
        var_dump(a, count(a)); // get UNKNOWN and 1

        unset a[key];
        var_dump(a, count(a));  // get UNKNOWN and 1 <<< must be 0

        // b like an array
        var_dump(b, count(b)); // get UNKNOWN and 1 <<< must be 0

        let b["key"] = 1234;
        var_dump(b, count(b));// get UNKNOWN and 1

        unset b["key"];
        var_dump(b, count(b));// get UNKNOWN and 1 <<< must be 0

        let key = "other";
        let b[key] = "bar";
        var_dump(b, count(b));// get UNKNOWN and 1 <<< must be 0

        unset b[key];
        var_dump(b, count(b)); // get UNKNOWN and 1 <<< must be 0
    }
}
```

I don't know maybe is a problem with `count()`

**Comment by sergeyklay** [comment]
@emiliodeg Could you please open an issue at Zephir with simple steps to reproduce (not a whole framework)?

**Comment by ruudboon** [comment]
@emiliodeg Did you already tested this with the latest Zephir?

**Comment by emiliodeg** [comment]
I'm so sorry but I didn't have time yet. I'll try this weekend

**Comment by ruudboon** [comment]
@emiliodeg closing this pull in favour of #14396. I included your tests, fix will be in soon. Thnx!

**Pull request closed without merging**
