### PR TITLE
Annotation Router - Removed converting the action name to lowercase

### PR DESCRIPTION
**Pull request by makerlabs**
I found this bug by analyzing the issue https://github.com/phalcon/cphalcon/issues/11568. I still don't know why the the action name was converted to lowercase.

### CODE REVIEW

**Comment by Green-Cat** [comment]
This change seems to be breaking tests.

**Comment by makerlabs** [comment]
Sorry about that I forgot to update the unit test now it's fixed.

**Comment by sergeyklay** [comment]
Could you please rebase? Also update CHANGELOG.md

**Comment by makerlabs** [comment]
OK but what should I put in the changelog? The 2.0.10 is already out you could also better describe the whole pull request workflow in the documentation because there is no reference to that.

**Comment by Jurigag** [comment]
```Removed converting the action name to lowercase```

**Comment by andresgutierrez** [comment]
This PR contains many commits that don't belong to the PR, could you please submit a new PR?

**Pull request closed without merging**
