### PR TITLE
3.2.x Validate date NULL, make required.

### PR DESCRIPTION
**Pull request by renatogabrielbr**
Its possible when to send null or empty string dont ask the presence, date validator i don't think must have PresenceOf. 

https://github.com/phalcon/cphalcon/blob/master/phalcon/validation/validator/date.zep

Something like

```
if empty value {
      return
}
```

Or 

```
if is_null (value) {
      return
}
```

```

$post['time'] = NULL;

$var = new Text('time');
$var
->setFilters(['string','null'])
 ->addValidator(new Date(['format' => 'Y-m-d H:i:s', 'message' => $this->translate->_('Wrong')]));
```

Return asking a valid date. this should be done by the PresenceOf validator.

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.2.x` branch?

**Comment by tidytrax** [comment]
Sorry, how i do that ?

**Comment by sergeyklay** [comment]
First of all lets clarify. Do you want report an issue or submit a pull request?

**Comment by Jurigag** [comment]
Just add `allowEmpty => true` to options....

**Comment by tidytrax** [comment]
Thanks works fine.

**Pull request closed without merging**
