### PR TITLE
[2.0.x] Issue #11286 - Model property visibility and setter functionality

### PR DESCRIPTION
**Pull request by bmoore**
Fix __set functionality to maintain variable visibility and utilize setter methods.

### CODE REVIEW

**Comment by sergeyklay** [comment]
This just a port of #11320 ? In any case update please CHANGELOG.md

**Comment by bmoore** [comment]
@sergeyklay yes, just a port. Changelog updated. This was created because this pull request https://github.com/phalcon/cphalcon/pull/10391 would have redundant and conflicting functionality.

**Comment by sergeyklay** [comment]
Could you please rebase?

**Comment by bmoore** [comment]
@sergeyklay rebase why? It has no merge conflicts and is squished to a single commit.

**Comment by sergeyklay** [comment]
Current 2.0.x CHANGELOG
https://github.com/phalcon/cphalcon/blob/2.0.x/CHANGELOG.md

Yours
https://github.com/bmoore/cphalcon/blob/2.0.x-patch-11286/CHANGELOG.md

**Comment by bmoore** [comment]
It would have merged cleanly. But I rebased it anyways.

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
