### PR TITLE
renamed phalcon\mvc\url to phalcon\url

### PR DESCRIPTION
**Pull request by ekmst**
Hello!

* Type: new feature
* Link to issue: #13742

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Thanks

### CODE REVIEW

**Comment by ruudboon** [comment]
@ekmst I think you missed the Di Factory.
https://github.com/ekmst/cphalcon/blob/0b42416fc99f5b65ddd239049f5d1ab17d62a30a/phalcon/di/factorydefault.zep#L54

Probably that will fix the tests. To be sure could you do a search in your repo for Mvc\\Url to make sure we got them all?

**Comment by ekmst** [comment]
Thank you @ruudboon!
fixed

**Comment by niden** [comment]
@ekmst dont forget the changelog please

**Comment by ruudboon** [comment]
And we should scan the documentation for the use of phalcon\mvc\url also.

**Comment by ekmst** [comment]
@niden done

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @ekmst

**Pull request merged**
