### PR TITLE
fix deep acl inherit

### PR DESCRIPTION
**Pull request by sersh88**
Fixes issue with deep acl inherit ( https://github.com/phalcon/cphalcon/issues/10134 )

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Could you please add tests?

**Comment by jkns** [comment]
@sersh88 Good work.

**Comment by sersh88** [comment]
Tests added.

**Comment by andresgutierrez** [comment]
Could you please submit this to the branch 2.0.x, we don't add commits directly on master.

https://github.com/phalcon/cphalcon/blob/2.0.x/CONTRIBUTING.md#pull-request-checklist

**Pull request closed without merging**
