### PR TITLE
Support for SELECT ALL/SELECT DISTINCT

### LINKED ISSUE #10143: [2.0.0] [BUG] Phalcon\Mvc\Model\Query in method parse()
Bug only with "distinct", 
without "distinct" - **no error**
```
$query = $this->modelsManager->createBuilder()
  ->addFrom('ProductForm', 'f')
  ->innerJoin('Product', 'p.form_id=f.id', 'p')
  ->orderBy('f.name_ru')
  ->groupBy('p.form_id');
  ->distinct(true);

 print_r($query->getQuery()->parse());
```

Error:
```
Syntax error, unexpected token *, near to ' FROM [ProductForm] AS [f] INNER JOIN [Product] AS [p] ON p.form_id=f.id ) GROUP BY p.form_id ORDER BY f.name_ru (1461)
```

### PR DESCRIPTION
**Pull request by dreamsxin**
Fix #10143

### CODE REVIEW

**Comment by KorsaR-ZN** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Could you please add tests?

**Comment by dreamsxin** [comment]
@andresgutierrez ok

**Comment by dreamsxin** [comment]
@andresgutierrez ok

**Comment by andresgutierrez** [comment]
Could you please add tests for SELECT ALL ?

**Comment by dreamsxin** [comment]
@andresgutierrez 

That's happen error
https://travis-ci.org/phalcon/cphalcon/builds/60156543
```error
Zephir\ParseException: Syntax error in /home/travis/build/phalcon/cphalcon/phalcon/security.zep on line 185
	    let saltBytes = this->getSaltBytes(2);
	------^
```
That's is ok.
https://travis-ci.org/dreamsxin/cphalcon/builds/60156536

**Comment by andresgutierrez** [comment]
Could you please remove this file from your commit? https://github.com/dreamsxin/cphalcon/blob/f01aa1f4e6b4d4f165e5a1ef7afccd9ada5de9b1/ext/phalcon/mvc/model/query/lemon

**Comment by dreamsxin** [comment]
@andresgutierrez Has been deleted.

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
