### PR TITLE
Added redis selected database

### PR DESCRIPTION
**Pull request by kjdev**
Phalcon\Cache\Backend\Redis selected database.

``` php
new Phalcon\Cache\Backend\Redis($frontCache, array(
  'host' => 'localhost',
  'port' => 6379,
  'index' => 1  // Added index option (database number: default index 0)
));
```

Re-submit. (#10093)

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by sergeyklay** [comment]
:+1:

**Comment by Green-Cat** [comment]
The build is failing because of an unrelated issue (yaml extension not loaded in travis ci on php 5.5)

**Comment by andresgutierrez** [comment]
Could you please remove this commit from the PR: https://github.com/karakurihiden/cphalcon/commit/f9678fbaac023ec09afb65ce18f5d9d9103c37df

**Comment by kjdev** [comment]
Re: Pull Request.

**Pull request closed without merging**
