### PR TITLE
Explicitly define nullable columns

### PR DESCRIPTION
**Pull request by 1RV34**
Hello!

* Type: bug fix
* Link to issue: #13099

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Explicitly define nullable columns. This fixes an issue I had with timestamp columns. By default when creating a timestamp column without explicitly telling it's allowed to be null and defaulted to null it will automatically give it an "on update current_timestamp" property.

To clarify: In my code I used the following:
```php
new Column('deadline', [
    'type' => Column::TYPE_TIMESTAMP,
    'notNull' => false,
    'default' => null
])
```
and instead it would create a timestamp with `CURRENT_TIMESTAMP` as default and the "on update current_timestamp" property.

Thanks

Ricardo Vermeltfoort

### CODE REVIEW

**Comment by 1RV34** [comment]
1. Not exactly sure how to properly write a test for this.
2. SQLite seems to default to `null` but i'm not 100% sure on this as I don't use it much at all.

**Comment by 1RV34** [comment]
I just saw the test that checks this and will update it now.

**Comment by 1RV34** [comment]
Still updating PostgreSQL tests.

**Comment by 1RV34** [comment]
Not exactly sure why the tests still fail, it's only the PHP 5.6 build, do you know?

**Comment by sergeyklay** [comment]
@1RV34 I've changed the base branch from `3.2.x`  to `3.3.x` and going to merge. There is some minor things. Could you please update change log also squash commits into one to keep history clean. Thank you.

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you!

**Pull request merged**
