### PR TITLE
Fix decimal digits

### PR DESCRIPTION
**Pull request by nekulin**
```
// Check    
$trade = \App\Models\Trades::findFirst(1);
    $trade->price_all = '85.6703707035391';
    $trade->save();

    var_dump($trade->price_all); // "85.6703707035391"
```

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or master. Can you please do PR to 2.0.x branch?

**Comment by SidRoberts** [comment]
@sergeyklay, you need to tell this guy too #10806 :stuck_out_tongue_winking_eye:

**Comment by sergeyklay** [comment]
Oops :)

**Comment by andresgutierrez** [comment]
Also, build/64bits/phalcon.c and build/32bits/phalcon.c must not be edited directly. They are generated based on the sources in ext/

**Pull request closed without merging**
