### PR TITLE
Merging 2.0.x

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by sergeyklay** [comment]
@SidRoberts As you can see I don't merged [your changes](https://github.com/phalcon/cphalcon/commit/47a86c72c4fe056a64d300f523fcbf5ec2d6d4aa) form 2.0.x because tests fails. It would be great if you could see what was happening

**Comment by SidRoberts** [comment]
@sergeyklay, I'm on the train at the moment. Can you post the link of the failed Travis build so I can see it before I get home? Thanks.

**Comment by sergeyklay** [comment]
https://travis-ci.org/phalcon/cphalcon/jobs/115320045#L590-L595

**Comment by SidRoberts** [comment]
It would appear that cc050456adff1108230242cdcf5de9056b3d9f57 is being overwritten. I've created a new PR for the 2.1.x branch: https://github.com/phalcon/cphalcon/pull/11525

**Comment by sergeyklay** [comment]
Okay. Shall I merge this PR?

**Comment by SidRoberts** [comment]
Yeah, I think so. :smile:

**Pull request merged**
