### PR TITLE
[2.0.x] [NFR] Added fastest alias in Phalcon\Mvc\Controller for redirect and forward

### PR DESCRIPTION
**Pull request by KorsaR-ZN**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
This violates the [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle)

**Comment by KorsaR-ZN** [comment]
@andresgutierrez This does not violate the SRP, because the class does not appear the new responsibilities he did the appropriate classes to delegate a proxy methods...

**Comment by andresgutierrez** [comment]
Yeah, but you depend on Mvc\Controller to make redirections or forwards

**Comment by KorsaR-ZN** [comment]
@andresgutierrez Yes you are right.
I make another PR which adds only the interface to the controller.

**Pull request closed without merging**
