### PR TITLE
Unset params["parameters"]

### PR DESCRIPTION
**Pull request by scrnjakovic**
This fixes the issue where if parameters are specified, they also get rendered into the form element as parameters attribute because whole params array is passed to `self::renderAttributes`.

* Type: bug fix
* Link to issue: I don't think there was an issue raised because of this yet

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
We don't accept pull requests to master, can you send it to 3.4.x and rebase?

**Comment by niden** [comment]
@scrnjakovic A small request please. Could you add a line in the `CHANGELOG` for 3.4 please so that we do not lose track of this?

Thank you!

**Comment by scrnjakovic** [comment]
@niden ofc, do I append to 3.4.1 section or create 3.4.2 ?

**Comment by scrnjakovic** [comment]
Oh crap, I have no idea what I'm doing. I haven't got used to Git & Github yet. I've a `patch-1` branch in my fork which was created when I edited `Tag.zep` file. The `CHANGELOG-3.4.md` with `3.4.2` section, however, is located in `3.4.x` branch of my fork. What am I supposed to do to fix this?

**Review by niden — DISMISSED** [review]

**Review by niden — APPROVED** [review]

**Pull request merged**
