### PR TITLE
Adds a prepareSave event to model saving.

### PR DESCRIPTION
**Pull request by Green-Cat**
Ref #1185

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Can we discuss the name of this event: everything can be: delete, update, find, validate, initialize?

**Comment by andresgutierrez** [comment]
@Green-Cat ping

**Comment by sszdh** [comment]
+1
With transaction/rollback support actualy

**Comment by sszdh** [comment]
My comment related to [this](https://forum.phalconphp.com/discussion/6954/related-models-rollbacks-and-aftercreate-events)

**Comment by carvajaldiazeduar** [comment]
@Green-Cat ping

**Comment by williamokano** [comment]
+1

**Comment by Green-Cat** [comment]
Any ideas of what the event can be called?

**Comment by KorsaR-ZN** [comment]
maybe `preparation`

**Comment by andresgutierrez** [comment]
I think prepareSave is a good name

**Comment by Green-Cat** [comment]
@andresgutierrez Changed the name of the event and rebased

**Comment by Green-Cat** [comment]
@andresgutierrez @sergeyklay rebased again

**Comment by sergeyklay** [comment]
Thanks

**Comment by sergeyklay** [comment]
@Green-Cat Update please `CHANGELOG.md`

**Pull request merged**
