### PR TITLE
clear queue

### PR DESCRIPTION
**Pull request by shopiz**
日志事务提交，清空队列

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`

**Comment by shopiz** [comment]
I need to submit to which branch？2.1.x？

**Comment by sergeyklay** [comment]
If this is bug related to the 2.0.x - send to the 2.0.x. Anyway  please describe a bit more what exactly are you trying to fix. And I'm not sure that you need to change Phalcon\Mvc\Model

**Comment by shopiz** [comment]
When the table design for not null, and set the default value (0 or the empty string), at the time of update, can not succeed.

**Comment by shopiz** [comment]
When the table field is designed as null not, and set the default value (0 or empty string), the original 0 or empty string will be modified to null value at update, leading to the update failed.

**Comment by shopiz** [comment]
If I submit it to 2.0.x, do I need to submit it to 2.1.x?

**Comment by sergeyklay** [comment]
Could you please separate PRs?

**Pull request closed without merging**
