### PR TITLE
Bugfix | Release action

### PR DESCRIPTION
**Pull request by AlexNDRmac**
Hello!

* Type: bug fix
* Link to issue: #15469 

Small description of change:

- Fixed paths for release action
- Added automatic release notes publishing from CHANGELOG

Thanks

### CODE REVIEW

**Review by niden — DISMISSED** [review]

**Comment by AlexNDRmac** [comment]
@niden in this PR also added automatic release notes publishing from CHANGELOG... but needs to check it :)

**Review by Jeckerson — DISMISSED** [review]

**Comment by Jeckerson** [comment]
Win builds seems to fail...

**Comment by AlexNDRmac** [comment]
Yes... failed because too long cmd line in batch... it must be reworked. I'll try to sort out with it ASAP

**Comment by AlexNDRmac** [comment]
@Jeckerson, Windows builds – fixed

**Review by Jeckerson — APPROVED** [review]

**Pull request merged**
