### PR TITLE
Corrected imports

### PR DESCRIPTION
**Pull request by ekmst**
Hello!

* Type: code quality
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change: Corrected imports

Thanks

### CODE REVIEW

**Review by ruudboon — CHANGES_REQUESTED** [review]
@ekmst While you optimising this. Could you have a look at Phalcon\Mvc\Model as well?

https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/Model.zep#L21
https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/Model.zep#L29

**Comment by ekmst** [comment]
@ruudboon 
I'm not sure I understand you correctly. Can you clarify?

**Comment by ruudboon** [comment]
@ekmst ManagerInterface is used twice. One as ManagerInterface and one with EventsManagerInterface as alias.
I think this line can go https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/Model.zep#L21
and where EventsManagerInterface is used it can be replaced by ManagerInterface

**Comment by ruudboon** [comment]
> @ruudboon
> I'm not sure I understand you correctly. Can you clarify?

Sorry, My mistake EventsManagerInterface isn't the same namespace.

**Review by ruudboon — APPROVED** [review]

**Comment by niden** [comment]
Thank you @ekmst

**Pull request merged**
