### PR TITLE
Change catch Exception to Throwable

### PR DESCRIPTION
**Pull request by sergeyklay**
Refs: #12288

### CODE REVIEW

**Comment by Jurigag** [comment]
Still i would like to see option to handlError diffrently than handleException? What you think? Sometimes people would want this.

**Comment by sergeyklay** [comment]
What do you think about something like that:
```php
$dispatcher->setExceptionHandler($callable);
```

**Comment by Jurigag** [comment]
Well what i mean is to add to dispatcher event called beforeError and if we have error - fire it first. Right not we have fired beforeException on error too, not sure if this is what someone would like, i think we need `dispatch:beforeException`, `dispatch:beforeThrowable` and `dispatch:beforeError`

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/pull/12292 like this

**Comment by sergeyklay** [comment]
@Jurigag Could you open nfr?

**Pull request merged**
