### PR TITLE
[2.1.x] Added new feature for pagination and also optional sets the aliases

### PR DESCRIPTION
**Pull request by KorsaR-ZN**
**Maintain compatibility with version 2.0.x**
see  #10957 

``` php
$repository = new \Phalcon\Paginator\Repository();
$repository->setAliases(array(
    'myFirstPage' => $repository::PROPERTY_FIRST_PAGE,
    'myLastPage' => $repository::PROPERTY_LAST_PAGE,
    'myCurrentPage' => $repository::PROPERTY_CURRENT_PAGE
));

$paginator = new \Phalcon\Paginator\Adapter\NativeArray(array(
    'data' => array_fill(0, 30, 'banana'),
    'limit'=> 25,
    'page' => 1,
    'repository' => $repository
));

$page = $paginator->getPaginate();

// First page
echo $page->first . PHP_EOL; // compatibility with version 2.0.x
echo $page->getFirstPage() . PHP_EOL; // Getter
echo $page->firstPage . PHP_EOL; // Magic getter
echo $page->myFirstPage . PHP_EOL; // Alias

// Current page
echo $page->current . PHP_EOL; // compatibility with version 2.0.x
echo $page->getCurrentPage() . PHP_EOL; // Getter
echo $page->currentPage . PHP_EOL; // Magic getter
echo $page->myCurrentPage . PHP_EOL; // Alias

// Last page
echo $page->last . PHP_EOL; // compatibility with version 2.0.x
echo $page->getLastPage() . PHP_EOL; // Getter
echo $page->lastPage . PHP_EOL; // Magic getter
echo $page->myLastPage . PHP_EOL; // Alias
```

### CODE REVIEW

**Comment by sergeyklay** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Why introduce a new class?

**Comment by KorsaR-ZN** [comment]
@andresgutierrez This can be useful for the type-hinting:
In order not to transmit the `paginator` fully in `function`, but only a concrete state
```php
function renderPage(\Phalcon\Paginator\RepositoryInterface $page) 
{
    //...expr...
}

//...expr...

$page = $paginator->getPaginate();
$pageRendred= renderPage($page);

//...expr...
```
or eg for serialization to transfer anywhere

**Comment by sergeyklay** [comment]
@KorsaR-ZN The 2.1.x branch is best place for this

**Comment by Green-Cat** [comment]
This is already targeting 2.1.x. It does need to be rebased though.

**Comment by sergeyklay** [comment]
Oh, yes. Could you please rebease?

**Comment by sergeyklay** [comment]
ping @KorsaR-ZN

**Comment by niden** [comment]
@KorsaR-ZN @CameronHall Thank you both. This has been addressed/cherry-picked in

https://github.com/phalcon/cphalcon/pull/13653

**Pull request closed without merging**
