### PR TITLE
Take advantage of prefix in router for faster handling

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/12758

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: Right now router always iterate through all routes even when for example using router groups prefix it couldn't have to. This PR adds such possibility to first check prefix if handledUri starts with it, if not then it continues to next prefix group.

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
First ow all we need to discuss this. Could you please open NFR.

Cc: @phalcon/framework-team

**Comment by Jurigag** [comment]
Yea i will do NFR and post some results from benchmark how it affects speed or something.

**Comment by Jurigag** [comment]
Any info? What you guys think about it?

**Comment by sergeyklay** [comment]
Thank you

**Comment by sergeyklay** [comment]
@Jurigag Could you please send PR to the docs repo with example?

**Comment by Jurigag** [comment]
Sure thing.

**Comment by michanismus** [comment]
@Jurigag You did introduce a new function `Router\Group::getRawRoutes()` which is not added to group interface. In Router::mount() you use this function which is not part of the interface. Your only check is the function argument <GroupInterface>.

**Comment by michanismus** [comment]
In `Router::mount()` you forgot to reset the sorted flag.

**Comment by Jurigag** [comment]
Yes it's not added because we can't add new methods to interfaces to not break BC - this is 3.2.x branch, not 4.0.x, in phalcon 4 it will be added.

About reset the sorted flag - what you mean here?

**Comment by virgofx** [comment]
@Jurigag Any chance you can benchmark before and after --- similar to microbench in zephir ?

**Comment by Jurigag** [comment]
I already did it in nfr

28.04.2017 1:19 AM "Mark Johnson" <notifications@github.com> napisał(a):

**Comment by Jurigag** [comment]
Oh right i know what you mean by sort flag - sure need to reset it after mounting group, thanks.

**Comment by michanismus** [comment]
@Jurigag Yeah, mounting groups I meant ;)

The interface... but right now you are expecting a GroupInterface as argument. So if I create an own group class which of cource implements GroupInterface, the default router will crash because I did not implement getRawRoutes() function.

I guess it also breaks BC right now ;)

**Comment by michanismus** [comment]
To be honest, I don't like this PR.
Why add a prefix option to paths for a single route? So there are 2 places where I can add a prefix, a single route and a `Group`. But why would I add a prefix to a route if i could just simply add it to pattern.

**Comment by Jurigag** [comment]
Will change this to check method_exists then.

Well i added simply to take advantage of faster handling for single routes too. Many people are using just single routes.php file with many routes or something like this when handling many routes will be slow. Adding option to grouping them by prefixes any way will speed up stuff.

**Comment by michanismus** [comment]
Does it really speed it up? 
For me it breaks a lot of stuff because I extended the Router class.
Means a looooot of work for me. 

If the router groups the routes by prefix why don't use the `Router\Group` internally in `Router`.
Btw it is not possible to set the `Route`class to be used. The creation of route objects is hardcoded on different places.

My suggestion is, revert this PR, refactor the whole Router / Group stuff and implement it in 4.0.0

**Comment by Jurigag** [comment]
Yes it really speed it up - check issue https://github.com/phalcon/cphalcon/issues/12758#issue-217299834

**Comment by michanismus** [comment]
Ok for the case someone uses group with prefixes and he wants to handle it 10000x times ;)
But for a real scenario? I mean, what is the speed benefit to handle 1 route, to find the one route that matches? Must be something around 0.05 - 0.010 millisecs...

**Comment by Jurigag** [comment]
Depends how many routes you have in application.

**Comment by michanismus** [comment]
Yes, for me I do have an average of 200 routes, I bet it won't give the expected advantage.

The introduction of `prefix` as a path argument to single routes which will be added to router? Prefix for a single route? I bet everyone would define the prefix in pattern. If not they would use `Router\Group`...

I really like the idea to improve the whole router stuff but I think it would be better to do it with 4.0.0 and refactor the whole stuff together.

**Comment by Jurigag** [comment]
Yea maybe, i can add there already what i mention too, maybe it's better idea,

**Comment by michanismus** [comment]
Yes - I have something in mind to store all routes in `Router\Group` in router internally - if you add a group it will simply added to router stack. Something like this...

Or just drop the `Router\Group` and add this functionality to the Router itself. Something like:

```php 

$prefix = $router->getPrefix();
$router->setPrefix('/admin');
$router->add('/login');
$router->add('/logout');
$router->add('/dashboard');
$router->setPrefix($prefix);
```

Just to simplify the route registration and generation. At the moment there are 2 places where `RouteInterface`objects are initiated, the router itself and the `Router\Group`. 

It would be easier to define the final route class to be used - which is not possible at the moment. Only if you overload the whole Router and Group.

```php
$router->setRouteClass(MyFancyRoute::class);
```

I do have a lot of ideas ;)

**Comment by Jurigag** [comment]
No, `Router\Group` is good - it allows you to have seperated classes with your routes, it's nice feature to have. Im using it in my apps and can't live without it.

This won't simplify things, it will make it longer imho.

About route class - well could be good if someone needs it.

Currently if for example request method is post we are checking all the routes(get, put, delete anyway) and we just check them against method - i want to change this to, so when we do addGet addPut etc it will be added to get/put group and we first check request type and use correct group to handle our route - it will be add speed too.

**Comment by michanismus** [comment]
Yes, grouping routes internally by method makes sense but how would you store routes which are accessible for POST, PUT and GET?

Ok - `Router\Group` should stay, but the whole Route initiation stuff should be taken out of the `Router\Group`. Right now there are two places where it happens. I would suggest to try to put it into `Router`. Just use `Router\Group` as a better simple array collection which will be compiled at mount point, not when you add a route to a group.

**Comment by Jurigag** [comment]
Well i updated my comment, we could actually remove it if we would add way to merge router classes.

something like:

```php
$router1 = new Router();
$router1->add('/login');
$router2 = new Router();
$router2->add('/dashboard');
$router1->merge($router2); // now router 1 have both login and dashboard
```

You mean via method? It will be just added to those 3 groups.

**Comment by michanismus** [comment]
That is another possible option :) 

Yes I mean the via. That would mean you would add the same route to 3 groups?

**Comment by michanismus** [comment]
What if you would filter the routes array according to method used before you iterate through the routes? Does not make sense right? You could just loop the the routes and check the method in place....

Bad idea :)

**Comment by Jurigag** [comment]
The best will be just:

```
protected _getRoutes;

protected _postRoutes;

public function handle()
{
    // ...
    switch request->getMethod {
        case "GET":
            let routes = this->_getRoutes;
            break;
    }

    for prefix, prefixGroup in routes {
        if prefix !== "" && !starts_with(handledUri, prefix) {
            continue;
        }
        for route in prefixGroup {
        
        }
    }
}
```

**Comment by Jurigag** [comment]
The biggest issue will be this via method in route - that's it here. Not really sure how to solve it, doing something like add it to all request types and then remove from certain ones - feels kind of messy.

**Comment by Jurigag** [comment]
I see two ways to solve it:

- add it to all method groups when doing `router->add` without methods, when someone will call via - remove it from method groups which are not selected
- add it to some seperated group like `_nonMethodRoutes` after selecting method group those routes with method groupes, if user will call via remove this route from only this routes and add to other

The question is what will be faster, array_merge or adding to all and then removing from added without a need.

**Comment by michanismus** [comment]
I would store them in `$this->_routes[request->getMethod]`.

What do you think about introducing a Route Factory and a Route Collection?

**Comment by Jurigag** [comment]
Yea but there will be then $this->routes[request->getMethod] and here prefix => group, pretty much.

What you mean by collection? Seperated class for storing routes? That would make more sense.

**Comment by michanismus** [comment]
It would be much easier if we only allow route objects to be added to router/collection. These routes have all necessary informations, methods, name etc.

Yes a storage object for the compiled routes, internally used by any router object.

**Comment by Jurigag** [comment]
But it's like this already, router have only route objects in routes property.

**Comment by michanismus** [comment]
Thats right but at the moment we can add routes like `router->get('/pattern')`. 
I mean only allow route objects to be added `router->add(<RouteInterface> route)`.

**Comment by Jurigag** [comment]
I don't like this really, router->add('/pattern') feels better, what we could do allow adding just router objects alone if someone would like, like `addRoute` method.

It would require people to do a lote of changes to their applications for phalcon 4.

**Comment by michanismus** [comment]
Maybe create a factory within `Route` for example:

```
Route::get('pattern', options)
```

**Comment by Jurigag** [comment]
But this doesn't change really anything, add method already pretty much do this and construction of route in current `add`, what's a difference?

**Comment by michanismus** [comment]
What I am thinking about is the following. If we add a route the current way
```
router->get('/pattern')
```
it would be added to _routes[GET] or _getRoutes. The method return the route itself to be able to name it or even change the method with `via` route method. 
How would you handle the modification of the currently added route?

**Comment by Jurigag** [comment]
Objects are passed as references so name change is not a problem, via is, I posted above how to solve this, not sure how your factory is supposed to fix this

**Comment by Jurigag** [comment]
After some thinking I know what you mean, I guess you want to do something like:

Route::via? This would actually make sense, I think it will be better.

Well I think we should leave old way of adding routes but add method should also just accept route object and add those factories.

**Comment by Jurigag** [comment]
Just instead of return route make it void or return this and problem with via is gone.

**Comment by michanismus** [comment]
Yes, I think thats the best way to archive a solid base for adding routes to router/collection.
The current way is not really compatible with new optimizations...

Anyone else who like to give his/her opinion on this topic? @sergeyklay @virgofx

**Pull request merged**
