### PR TITLE
default parameter value matches the type

### PR DESCRIPTION
**Pull request by wjiec**
Hello!

* Type: code quality

Default value for Boolean type parameter.

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Thanks

### CODE REVIEW

**Comment by JShadowMan** [comment]
And I have a question.

Is it an BUG that the `autoLoad` method does not check for files exists that are registered through the `registerClasses` method?

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
@JShadowMan There is `loader:pathFound` event so you are able to do any custom checks. In general any check for files exists will slow down your application. For more refer to https://github.com/phalcon/cphalcon/issues/13360

**Comment by sergeyklay** [comment]
Thank you

**Comment by JShadowMan** [comment]
@sergeyklay Okay, I got it. Thanks for your guidance.

**Pull request merged**
