### PR TITLE
Added way to get active key and active function from Phalcon\Acl\Adapter\Memory

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: new feature

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: added methods for getting active key and active function for latest acquired access in acl.

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
@sergeyklay could this be merged? Need this for some other PR.

**Comment by sergeyklay** [comment]
This will work only for Memory Adapter right? So typical user, who does not read CHANGELOG.md,  will be very surprised why feature which will use these methods does not work with MyAwesomeAclAdapterFromIncubator. I'm not sure that some custom adapter (impements adapter pattern) should contain methods except those which are declared in the interface.

**Comment by Jurigag** [comment]
Yea only for memory. Well then just incubator would need to add this too. This is why i added this to Memory class, not Adapter. I can do the same pr to incubator classes.

**Comment by michanismus** [comment]
@Jurigag When it is only for Memory, why don't you extend the Memory adapter for your special purpose?

**Comment by Jurigag** [comment]
@michanismus the thing is i needed this functionality for some other PR but i will postpone it to phalcon 4

**Comment by sergeyklay** [comment]
@Jurigag Could you please rebase

**Comment by niden** [comment]
This has been merged with cherry-pick

https://github.com/phalcon/cphalcon/commit/80ced232ff758fc92904679fff82f2349891e52f

@Jurigag thanks!

**Pull request closed without merging**
