### PR TITLE
Minor changes on Stream adapter

### PR DESCRIPTION
**Pull request by ekmst**
Hello!

* Type: code quality | enhancement | bugfix
* Link to issue: https://github.com/phalcon/cphalcon/issues/14725

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

I could not reproduce this problem(https://github.com/phalcon/cphalcon/issues/14714), but I think this will solve it.

Even if this does not help, I think this improvement will not be superfluous :)

Thanks

### CODE REVIEW

**Comment by ruudboon** [comment]
@ekmst Can you add a test for this?

**Comment by ekmst** [comment]
@ruudboon Existing tests pass and I did not add.

Ok, add later

**Comment by ekmst** [comment]
I caught another mistake when writing tests.
If we call the `Stream::getKeys()` method with empty data and using a prefix, we get an exception. The following is an example for this behavior:

```php
$serializer = new \Phalcon\Storage\SerializerFactory();

        $adapter = new \Phalcon\Cache\Adapter\Stream(
            $serializer,
            [
                'storageDir' => '/tmp/',
                'prefix'     => 'pref-',       // The '/tmp/pref-' directory will not be created until we have written any data
            ]
        );
       $adapter->getKeys();  // Throws an exception
```

We get an exception:
```
Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/tmp/pref-/): failed to open dir: No such file or directory in ...
```

**Comment by ruudboon** [comment]
> I caught another mistake when writing tests.
> If we call the `Stream::getKeys()` method with empty data and using a prefix, we get an exception. The following is an example for this behavior:
> 
> ```
> $serializer = new \Phalcon\Storage\SerializerFactory();
> 
> $adapter = new \Phalcon\Cache\Adapter\Stream(
>     $serializer,
>     [
>         'storageDir' => '/tmp/',
>         'prefix'     => 'pref-',       // The '/tmp/pref-' directory will not be created until we have written any data
>     ]
> );
> $adapter->getKeys();  // Throws an exception
> ```
> 
> We get an exception:
> 
> ```
> Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/tmp/pref-/): failed to open dir: No such file or directory in ...
> ```
Let's handle that in a new issue.

**Comment by ekmst** [comment]
> Let's handle that in a new issue.

Done

**Review by ruudboon — APPROVED** [review]
@ekmst Thank you

**Comment by ruudboon** [comment]
Please don't merge this yet. Looks like Travis missed this pull

**Comment by ekmst** [comment]
@ruudboon 
In the last commit, only the change log was updated, so I explicitly skipped the building.

The build was in the previous commit
https://ci.appveyor.com/project/sergeyklay/cphalcon/builds/30181621
and
https://travis-ci.org/phalcon/cphalcon/builds/638377382?utm_source=github_status&utm_medium=notification

**Comment by ruudboon** [comment]
@ekmst Sorry. I was sleeping ;)

**Comment by ekmst** [comment]
@ruudboon no problem :)

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @ekmst !

**Pull request merged**
