### PR TITLE
[2.0.0] Binding arrays

### PR DESCRIPTION
**Pull request by vlad-khramov**
Related #2934

Port of Doctrine DBAL SQLParserUtils

Usage:

```
$songs = $connection->fetchAll(
        'select * from songs where name in (?) order by id',
        Db::FETCH_ASSOC,
        array(array('Born to Die', 'Off to Races', 'Blue Jeans'))
    );

    $connection->delete(
        'songs',
        'name in (?)',
        array(array('name1','name2'))
    );

    $persons = Robots::find(array(
        "id in (:ids:)",
        'bind' => array('ids' => array(1, 2, 3)),
        'bindTypes' => array('ids' => Column::BIND_PARAM_INT_ARRAY)
    ));

    $persons = Robots::find(array(
        "id in (?0)",
        'bind' => array(array(1, 2, 3))
    ));

    $persons = Robots::findById(array(1, 2, 3));
```

Original class is under MIT licence. In which form I must write copyright notices in ported files?
Now I write default template for such files:
https://github.com/quantum13/cphalcon/blob/bind_array/phalcon/db/utils/sqlparser.zep
https://github.com/quantum13/cphalcon/blob/bind_array/tests/unit/Phalcon/Db/Utils/SQLParserTest.php

### CODE REVIEW

**Comment by quantum13** [comment]
@phalcon I changed header of files and added Doctrine license to license.txt. Could you please comment it.

My question to Doctrine authors: http://www.doctrine-project.org/jira/browse/DBAL-1124

**Comment by Green-Cat** [comment]
I think it would be better to put the MIT license in the relevant file only.
Also you need to credit the original author of the class in the header docblock.

**Comment by quantum13** [comment]
@Green-Cat +

**Comment by sergeyklay** [comment]
:+1:

**Comment by Green-Cat** [comment]
@quantum13 Can you please rebase against 2.0.x and resubmit? Thanks

**Pull request closed without merging**
