### PR TITLE
Added Redis model metadata class.

### PR DESCRIPTION
**Pull request by SidRoberts**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Missed `<?php` in `phalcon/mvc/model/metadata/redis.zep`

**Comment by SidRoberts** [comment]
@sergeyklay Where?

**Comment by sergeyklay** [comment]
selection_052

**Comment by SidRoberts** [comment]
But it's Zephir? :stuck_out_tongue:

**Comment by sergeyklay** [comment]
:facepalm: I overworked :)

**Comment by andresgutierrez** [comment]
:grin:

**Pull request merged**
