### PR TITLE
[1.3.x] Fix #3124 (check email with filter_var)

### LINKED ISSUE #3124: [bug]email valid
I write a test case:
```php
$model2 = new AccountInfo();
$model2->email = 'sdfsaf@asfd$d.+*';
$model2->nickName = 'aaaaa';
$model2->validation();
$this->tester->assertEquals(false, filter_var($model2->email,FILTER_VALIDATE_EMAIL));
$this->assertNotNull($model2->getMessages());
$this->assertCount(1,$model2->getMessages());
```
result:
```php
$this->tester->assertEquals(false, filter_var($model2->email,FILTER_VALIDATE_EMAIL));   # is ok
```
but 
```
$this->assertNotNull($model2->getMessages());     # fail  $model2->getMessages() return null
```

I use Phalcon 1.3.4 and codeception testing framework 2.0.8

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6941668-bug-email-valid?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by maxgalbu**
#3124

### CODE REVIEW

**Comment by sergeyklay** [comment]
About regex vs `FILTER_VALIDATE_EMAIL` validation

**Comment by phalcon** [comment]
But this is a validator not a filter, we need a regex there

**Comment by maxgalbu** [comment]
In the issue #3124 i saw that phalcon 2 uses filter_var():

https://github.com/phalcon/cphalcon/blob/dc8ced6a83da2d9e148c5ca222abc4db9e4a1604/phalcon/mvc/model/validator/email.zep#L80

Filter_var() return false if the email is not valid, so it should actually act as a validator, if I'm not mistaken

**Comment by phalcon** [comment]
It should use regex on both, filter_var doesn't validate a format correctly

**Comment by maxgalbu** [comment]
Do you agree with #3227?
I think filter_var() validates most of the emails except some "obscure" emails ("string with spaces"@example.com, test@localhost, etc which IMHO are very obscure), and is accepted by the php community.

We can add a "strict" boolean that when enabled makes the function checks the emails with the regex, otherwise it checks them using filter_var().

**Comment by phalcon** [comment]
Maybe adding an extra option to avoid localhost and obscure emails would be fine :+1:

**Pull request closed without merging**
