### PR TITLE
3.2.x Update and Bugfix for `Phalcon\Mvc\Model\MetaData\Strategy\Annotations`

### PR DESCRIPTION
**Pull request by michanismus**
Hello!

* Type: bug fix | new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

I added some missing data types to `Phalcon\Mvc\Model\MetaData\Strategy\Annotations`.
I introduced three new named params:

skip_on_insert=true/false
skip_on_update=true/false
allow_empty_string=true/false

Example:

```php
    /**
     * @Column(
     *     type="string",
     *     nullable=true,
     *     column="meta_title",
     *     skip_on_insert=false,
     *     skip_on_update=false,
     *     allow_empty_string=false
     * )
     */
    protected $metaTitle;
```

I fixed a bug in `getColumnMaps`. Currently it is not possible to have a mixed definition of renamed fields. Example:

```php
    /**
     * @Column(type="string", nullable=true, column="meta_title")
     */
    protected $metaTitle;

    /**
     * @Column(type="text", nullable=true)
     */
    protected $meta_description;

    /**
     * @Column(type="text", nullable=true, column="meta_author")
     */
    protected $metaAuthor;
```
The field `meta_description` would be ignored which will result in exceptions for various model actions (save/update/...).

Second bug I fixed is the column name for data type `integer`. At the moment it is impossible to define an integer field which is renamed as well. Field type definition uses wrong column name:

```zephir
    case "integer":
        let fieldTypes[property] = Column::TYPE_INTEGER, // <- property instead of columnName
            fieldBindTypes[columnName] = Column::BIND_PARAM_INT,
            numericTyped[columnName] = true;
        break;
```
Will result in an exeption while updating or creating a new record (unknown data type for ...).

Thanks

### CODE REVIEW

**Comment by virgofx** [comment]
Phalcon doesn't actually implement any of the metadata properties in the application so this should not be merged. This is better off left for your application to handle. You could submit a separate PR which handles the few typos which you corrected.

**Comment by Jurigag** [comment]
@virgofx what you mean doesn't implement metadata properties?

**Comment by virgofx** [comment]
Model, models manager doesn't handle skip on insert or skip on update.

**Comment by michanismus** [comment]
@virgofx Phalcon doesn't actually implement any of the metadata properties?

**Comment by michanismus** [comment]
@virgofx 
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/metadata.zep#L563
https://github.com/phalcon/cphalcon/blob/14c604636ce5a69bb49e97cc99a91e8d966f17e4/phalcon/mvc/model.zep#L2469?

These metadata is not new.

**Comment by Jurigag** [comment]
@virgofx i don't sure exactly what you mean, model is exactly doing this:

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L2255

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L2269

So it's exactly working, it's skipping fields provided in skipAttributesOnCreate.

**Comment by michanismus** [comment]
@virgofx I did not introduce these "features". There were already there, I simply added a way to define them by annotations.

**Comment by virgofx** [comment]
I do see that the PR is not adding new indexes -- I briefly skimmed PR and didn't review thoroughly. Looks like it's just some bugfixes and a slight name update.  👍  Only other thought is I'd love to see all potential options updated in annotations docs

**Comment by Jurigag** [comment]
Yea as i see it's only adding missing types in annotations and options to set attributes skip in annotations.

**Comment by michanismus** [comment]
@virgofx If these names I introduced are fine for all then I'm going to add them to docs...

**Comment by virgofx** [comment]
Key names seem fine to me.

**Comment by sergeyklay** [comment]
@michanismus Could you please cover you additions by small test

**Comment by michanismus** [comment]
@sergeyklay I create some tests today.

**Comment by michanismus** [comment]
@sergeyklay Tests added and rebased.

**Comment by michanismus** [comment]
Ping :)

**Comment by sergeyklay** [comment]
@michanismus
I will keep this open for a day or two to allow other contributors a chance to speak up, and to take a fresh look at it later. But at the moment it seems good to me.

Could you please update CHANEGELOG.md?

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Cc: @phalcon/core-team

**Comment by virgofx** [comment]
Looks good to me.

**Review by niden — CHANGES_REQUESTED** [review]
Well done changes. Thank you.

Could you please add this functionality in the documentation?

Thanks

**Comment by michanismus** [comment]
Added PR to docs
@niden @sergeyklay

**Comment by michanismus** [comment]
@sergeyklay Updated CHANGELOG.md

**Comment by sergeyklay** [comment]
Thank you!

**Pull request merged**
