### PR TITLE
[2.0.x] The Model Paginator now iterates over the models.

### PR DESCRIPTION
**Pull request by SidRoberts**
~~@KorsaR-ZN, could you check [your code](https://github.com/phalcon/cphalcon/pull/10247#issuecomment-99114221) to see if this solves the problem?~~

Update: This does solve an issue in the Paginator, but see also #10253 for the real fix.

### CODE REVIEW

**Comment by KorsaR-ZN** [comment]
@SidRoberts I've tried it, it does not solve the problem. 
But this code will solve the problem, after fixed #10100

**Comment by patrick-zippenfenig** [comment]
Looks good. Valid() previously moved the pointer to the next position which is a non-standard behaviour. Next() has to be called. I'm currently reviewing #10100 and look for other occurrences. I did not anticipate such problems...

**Comment by KorsaR-ZN** [comment]
@SidRoberts 
```php
$robots = Robots::find();

$page  = isset($_GET['page']) ? $_GET['page'] : 1;
$limit = isset($_GET['limit']) ? $_GET['limit'] : 3;

$paginator = new Phalcon\Paginator\Adapter\Model([
    'data' => $robots,
    'limit' => $limit,
    'page' => $page
]);

$paginate = $paginator->getPaginate();

echo 'Items: ' . count($robots) . '<br>';
echo 'Page: ' . $page . ' / ' . $paginate->total_pages . '<br>';

echo 'Results: ';

foreach ($paginate->items as $item) {
    echo $item->id . ',';
}
```

## 2.0.x (fail)

**Test 1 ($page = 1)**
```
Items: 53
Page: 1 / 18
Results: 1,2,3,
```

**Test 2 ($page = 2)**
```
Items: 53
Page: 2 / 18
Results: 7,8,9,
```

**Test 3 ($page = 5)**
```
Items: 53
Page: 5 / 18
Results: 25,26,27,
```

**Test 4 ($page = 17)**
```
Items: 53
Page: 17 / 18
Results: // FAIL
```

## 2.0.0 (success)

**Test 1 ($page = 1)**
```
Items: 53
Page: 1 / 18
Results: 1,2,3,
```

**Test 2 ($page = 2)**
```
Items: 53
Page: 2 / 18
Results: 4,5,6,
```

**Test 3 ($page = 5)**
```
Items: 53
Page: 5 / 18
Results: 13,14,15,
```

**Test 4 ($page = 17)**
```
Items: 53
Page: 17 / 18
Results: 49,50,51,
```

**Comment by KorsaR-ZN** [comment]
@patrick-zippenfenig
Error in the method `\Phalcon\Mvc\Model\Resultset::seek()`

Please use `Paginator` tests, https://gist.github.com/KorsaR-ZN/e649cf5a1325112472d3,
It is tests partly, but covers the error. When fix #10100, then I improve tests...

**Comment by patrick-zippenfenig** [comment]
#10253 should fix the issues mentioned by @KorsaR-ZN. valid() is also used in [volt.zep#L248](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/engine/volt.zep#L248) but correctly implemented.

**Comment by KorsaR-ZN** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
