### PR TITLE
Filter boolval minor changes

### PR DESCRIPTION
**Pull request by ekmst**
Hello!

* Type: code quality
* Link to issue: -

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by Jeckerson** [comment]
`(bool)` works faster then function `boolval()`.

**Comment by niden** [comment]
@Jeckerson what you changed is the opposite of what the commit offers. Typo or something else?

**Comment by Jeckerson** [comment]
@niden PR isn't mine.

**Comment by CameronHall** [comment]
@ekmst I don't believe this change is necessary. Nor is it an improvement to code quality.

**Comment by sergeyklay** [comment]
`(bool)` is the language instruction and `boolval` is the function that depends on 2 arguments. Functions run slower than instructions.

**Comment by niden** [comment]
@Jeckerson sorry bud - brain fart lol

**Pull request closed without merging**
