### PR TITLE
#14801 - Phalcon\Helper\Arr::blackList()

### PR DESCRIPTION
**Pull request by TimurFlush**
Hello!

* Type: new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/14801

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Thanks

### CODE REVIEW

**Comment by TimurFlush** [comment]
@ruudboon Is it normal that test have failed?

**Comment by ruudboon** [comment]
Looks like something is messed up in the 4.1.x branch. Will try to make some time this weekend to sync 4.1 with 4.0 if you can rebase after that we can check again.

**Comment by TimurFlush** [comment]
@ruudboon, I'll try

**Comment by niden** [comment]
@TimurFlush wait a bit. We will merge 4.0 -> 4.1 (hopefully) today or tomorrow and then you can rebase.

**Comment by TimurFlush** [comment]
@niden okay

**Pull request closed without merging**
