### PR TITLE
basic validation credit card number using luhn algorithm

### PR DESCRIPTION
**Pull request by caiofralmeida**
I am very happy to be learning and have the opportunity, thank you for your attention :)

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please update the CHANGELOG?

**Comment by caiofralmeida** [comment]
done, friend, but conflict happened :/ I can not solve.

I've got an idea to create a credit card type (vendor) detector. For example from "BIN" report card which is flag.

examples:
number starting with 4 ... length 16, is VISA
number starting with 37 or 34 ... length 15, is AMEX

more information https://en.wikipedia.org/wiki/Bank_card_number

**Comment by caiofralmeida** [comment]
thank you !!!

**Comment by andresgutierrez** [comment]
Could you please rebase against 2.0.x? https://help.github.com/articles/about-git-rebase/

**Comment by caiofralmeida** [comment]
I think it worked.

**Comment by sergeyklay** [comment]
@caiofralmeida Could you rebase and squash it into a single commit to keep the history clean? Let me know if you need instructions.

**Comment by caiofralmeida** [comment]
@sergeyklay can you help me?

**Comment by sergeyklay** [comment]
Did you pushed with `-f ` ?

**Comment by caiofralmeida** [comment]
pushed without `-f`

**Comment by sergeyklay** [comment]
* [Squash Commits with Git][1]
* [Git: Squash your latests commits into one][2]
* [Squash my last X commits together using Git][3]

[1]:http://davidwalsh.name/squash-commits-git
[2]:https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/
[3]:http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

After squashing it into a single commit you need push with `-f` option

**Comment by caiofralmeida** [comment]
I think it worked.

**Comment by caiofralmeida** [comment]
@andresgutierrez and @sergeyklay, the PR is acceptable?
thank you.

**Comment by sergeyklay** [comment]
You made squash but did not rebased a `caiofralmeida/validation-cc-v2` branch onto `origin/2.0.x`.
Also please see [Pull Request Checklist][1]:
> Remove any change to `ext/kernel` / `*.zep.c` / `*.zep.h` files before submitting the pull request

[1]:https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md#pull-request-checklist

**Comment by caiofralmeida** [comment]
@sergeyklay sorry for the problems caused, all right now?

thank you for your attention.

**Comment by sergeyklay** [comment]
@andresgutierrez

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
