### PR TITLE
Acl Docblock Cleanup

### PR DESCRIPTION
**Pull request by Green-Cat**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Build is broken, could you please check?

**Comment by Green-Cat** [comment]
@andresgutierrez it seems like Phalcon\Acl\Role does not implement RoleInterface.
Is that by design?

**Comment by Green-Cat** [comment]
@phalcon @andresgutierrez I fixed the build.
Should I squash to a single commit and create a new pull request or will this do?

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
