### PR TITLE
T13680 breadcrumbs component

### PR DESCRIPTION
**Pull request by niden**
Hello!

* Type: new feature
* Link to issue: #13680 

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Added `Html\Breadcrumbs component, offering an easy way to create breadcrumbs for your application

Thanks

### CODE REVIEW

**Comment by niden** [comment]
cc @sergeyklay

**Review by CameronHall — CHANGES_REQUESTED** [review]
Could you please fix up the two minor things I found in the docblocks? Thank you!

**Review by sergeyklay — APPROVED** [review]
There are some minor issues mentioned by @CameronHall, but on the whole LGTM

**Comment by niden** [comment]
@sergeyklay Already addressed them

**Pull request merged**
