### PR TITLE
Phalcon application upload

### PR DESCRIPTION
**Pull request by jeanthierry**
Hello,
I am having a problem with viewing my phalcon site on the internet.
I uploaded the project folder under public_html as noted by my web server provider but still i can't view my app online.
Is there anything special i need for phalcon?
could you help please i am new in phalcon and it the the first phalcon app i am deploying?
thank you in advance.

### CODE REVIEW

**Comment by phalcon** [comment]
Why are you submitting a PR? If you need help feel free to use the forum: forum.phalconphp.com

**Comment by jeanthierry** [comment]
i am uploading my phalcon website to the internet.
could you help?
because it is written on my domain info that i need to upload my files on the public_html or www folder.

**Comment by Amazium** [comment]
Jean-Thierry, is the phalcon module installed on the webserver? add a php file with phpinfo() to check this.

**Comment by jeanthierry** [comment]
Dear Amazium, i don't think so. I just bought a domain. How do i install phalcon module on it? could you help?
On the localhost that was easy but now that i want to upload on the internet, it becomes different.
Is there any tutorial for uploading phalcon site or installing phalcon on a webserver? 
Thank you in advance.

**Pull request closed without merging**
