### PR TITLE
add more dialect for postgresql

### PR DESCRIPTION
**Pull request by wamxx**
Add more dialect for manage postgresql tables

### CODE REVIEW

**Comment by sergeyklay** [comment]
Can u provide tests please?

P.S. Also check indents

**Comment by andresgutierrez** [comment]
Zephir says:

```
Zephir\CompilerException: Class Phalcon\Db\Dialect\Oracle::modifyColumn() does not have the same number of required parameters in interface: Phalcon\Db\DialectInterface
```

**Comment by wamxx** [comment]
all good, fix bug , indent and add unit testing.

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
