### PR TITLE
add getOrderBy method (alias getOrder) to criteria

### PR DESCRIPTION
**Pull request by tmihalik**
as in:
https://github.com/phalcon/cphalcon/blob/c8d4916bbfd0cb18395fe25d8c5a663fc5077d8f/phalcon/mvc/model/query/builder.zep#L858

### CODE REVIEW

**Comment by andresgutierrez** [comment]
I think this could break many applications

**Comment by tmihalik** [comment]
OK, and +1 method as alias?

**Comment by sergeyklay** [comment]
@tmihalik 
1. Create PR to 2.1.x branch please
2. Alias for 2.1.x not needed
3. Update tests
4. Update CHANGELOG.md please

**Comment by tmihalik** [comment]
https://github.com/phalcon/cphalcon/pull/11200

**Pull request closed without merging**
