### PR TITLE
Implement NFR #10798

### PR DESCRIPTION
**Pull request by lajosbencz**
Moved to latest branch

### CODE REVIEW

**Comment by lajosbencz** [comment]
@andresgutierrez the unit-test which I've added passes, but there are two other which fail... please advise :D

**Comment by andresgutierrez** [comment]
Could you please rebase?

**Comment by lajosbencz** [comment]
@andresgutierrez @sergeyklay I'm fairly retarded with git... :] Should I update my forked 2.1.x branch from upstream and commit, or rebase it to a different branch? And if the latter, then which branch?

**Comment by sergeyklay** [comment]
I use always this way :grimacing: 

```sh
git checkout 2.1.x
git fetch
git rebase origin/2.1.x
// ...
git commint -m '...'
git push lajosbencz/2.1.x
```

it doesn't fit you?

**Comment by lajosbencz** [comment]
@sergeyklay that's why I'm confused, it says there are no changes! :] Thanks for helping!

**Comment by lajosbencz** [comment]
Did I get it right this time? :D

**Comment by lajosbencz** [comment]
I don't think it worked... here is what I did:
Using PhpStorm, I merged ```upstream/2.1.x``` (phalcon/cphalcon)

```
First, rewinding head to replay your work on top of it...
Applying: Updated CHANGELOG [ci skip]
Applying: Added support of `DEFAULT CURRENT_TIMESTAMP` definition to SQL dialects
...
```

Then I updated my forked repo:
git push origin 2.1.x (lajosbencz/cphalcon)

But now it can't even automerge :(

**Comment by sergeyklay** [comment]
:neutral_face: give me 10 min

**Comment by sergeyklay** [comment]
@lajosbencz see https://github.com/phalcon/cphalcon/pull/10926

**Pull request closed without merging**
