### PR TITLE
Refactor db tests

### PR DESCRIPTION
**Pull request by ruudboon**
Hello!

* Type: code quality
* Link to issue: #13655 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Refactored UniquenessCest

### CODE REVIEW

**Comment by ruudboon** [comment]
@niden If you have time can you ping me to check how we can solve the sql db-lock? https://github.com/phalcon/cphalcon/runs/747581338?check_suite_focus=true#step:17:180

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Sqlite does not like group statements, where etc. Anything "fast" i.e. tests running seems to lock the sqlite database.

**Comment by ruudboon** [comment]
Ok, let's leave it open then. I will try to fix it or remove sqlite from these tests.

**Comment by ruudboon** [comment]
Looks like connection to db is still open (maybe cause by a transaction?) 
I'm wondering if `PRAGMA journal_mode = wal;` could solve our sqlite issues.

**Comment by ruudboon** [comment]
@jenovateurs Do you have an idea what is causing this error?https://github.com/phalcon/cphalcon/pull/15076/checks?check_run_id=752726095#step:19:27

**Comment by jenovateurs** [comment]
Hi @ruudboon, I think it's a type trouble. PostgreSQL is very strict about that.
In your case, `obj_name` it's a varchar and `obj_type` is a smallint, so two differents types but in the SQL request there is no differences.
So I think you discovered a new Phalcon bug. I don't understand why Phalcon check `obj_name` and `obj_type` with the same parameters, it makes no sense to me.
I think it's work with MySQL because there is no strong check about the type and it doesn't affect the result with the keyword OR.
The problem might be here : 
https://github.com/phalcon/cphalcon/blob/6f9ce5c4af4486f6b40413571182408732dc617c/phalcon/Validation/Validator/Uniqueness.zep#L373
These days, I have too much work to do. I haven't the time to debug line by line this code.

**Pull request merged**
