### PR TITLE
Fix bug #10239

### PR DESCRIPTION
**Pull request by dreamsxin**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
I think it could be more powerful to use an expression for the cache lifetime instead of identifier or integer

**Comment by dreamsxin** [comment]
@andresgutierrez The best way is to modify the parameters of the cache, like this:
```php
{% cache "sidebar", 3600 %}
    <!-- generate this content is slow so we are going to cache it -->
{% endcache %}
```

**Comment by andresgutierrez** [comment]
Is the parser having conflicts if you use an expression?

**Comment by dreamsxin** [comment]
@andresgutierrez Yes, will conflict, error: `Not enough precedence: error`
```lemon
cache_statement(R) ::= OPEN_DELIMITER CACHE expr(E) expr(N) CLOSE_DELIMITER statement_list(T) OPEN_DELIMITER ENDCACHE CLOSE_DELIMITER . {
```
There is something wrong with the priority.

**Comment by andresgutierrez** [comment]
Ok, so I think we're fine with this

**Pull request merged**
