### PR TITLE
Added listTubes to `\Phalcon\Queue\Beanstalk`

### PR DESCRIPTION
**Pull request by pauliuspetronis**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please add the entry in the CHANGELOG in 2.0.7?

**Comment by pauliuspetronis** [comment]
@andresgutierrez - added and rebased from 2.0.x

**Comment by andresgutierrez** [comment]
Could you please rebase?

**Comment by pauliuspetronis** [comment]
Rebased

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
