### PR TITLE
Fix total_items and total_pages in Paginator when it has `GROUP BY` #2411

### PR DESCRIPTION
**Pull request by ryomo**
#2411
#10955

### CODE REVIEW

**Comment by sergeyklay** [comment]
@andresgutierrez Test for PHP 5.3 fails because https://github.com/phalcon/zephir/pull/1139

**Comment by sergeyklay** [comment]
@andresgutierrez Now tests fails because https://github.com/phalcon/zephir/pull/1141

**Comment by andresgutierrez** [comment]
Thanks

**Comment by pedoc** [comment]
@andresgutierrez
hi,i was use version 2.0.10,but except 'group',i had 'distinct(true) '  is wrong。sorry,my english is bad.
code example：
$builder=$this->modelsManager->createBuilder()->from("Robots")->leftJoin('Parts',"Parts.id=Robots.part_id")->distinct(true);
$paginator = new Phalcon\Paginator\Adapter\QueryBuilder(
            array(
                "builder" => $builder,
                "limit"   => 10,
                "page"    => 1
            )
        );
You can get to the two data，but，‘total_items’ property is 3。
I think the problem is the same ‘group’ and the，It is a bug?
Looking forward to your reply。

**Comment by Jurigag** [comment]
As i see query builder paginator ignores distinct method at all. There is only check for groupBy but not for distinct. https://github.com/phalcon/cphalcon/blob/master/phalcon/paginator/adapter/querybuilder.zep

**Pull request merged**
