### PR TITLE
Support set the connection profiler

### PR DESCRIPTION
**Pull request by dreamsxin**

### CODE REVIEW

**Comment by SidRoberts** [comment]
References #10461

**Comment by andresgutierrez** [comment]
This will add more overhead to the database component, maybe update the documentation to this example? https://docs.phalconphp.com/en/latest/reference/models.html#profiling-sql-statements

**Comment by dreamsxin** [comment]
@andresgutierrez Use the event, the `executePrepared` and `execute` can't captured, and not enough easy to use

**Comment by dreamsxin** [comment]
Can change `Profiler` to this:
```php
class Profiler
{
    public function beforeQuery($event, $db, $bindParams = NULL)
    {
        // TODO
    }

    public function afterQuery($event, $db, $bindParams = NULL)
    {
        // TODO
    }
}
$profiler = new Profiler;
$eventsManager->attach('my-component', $profiler);
```

**Pull request closed without merging**
