### PR TITLE
Redis now flushes properly

### PR DESCRIPTION
**Pull request by SidRoberts**
References #11444

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by sergeyklay** [comment]
As you can see tests fails.

**Comment by sergeyklay** [comment]
@SidRoberts Phalcon 2.0 is not longer supported. Could you please send PR to the `2.1.x` branch?

**Comment by sergeyklay** [comment]
Fixed in the `2.1.x` branch

**Pull request closed without merging**
