### PR TITLE
Improved regular expression in Mvc\Url to detect external resources

### PR DESCRIPTION
**Pull request by sergeyklay**
- Cleanup local regexp
- Digits for matching need for example for `e2dk` protocol

### CODE REVIEW

**Comment by andresgutierrez** [comment]
It needs two regex (or less/more) to match these:

-  //localhost/something
- http://localhost/something
- mailto:something@something.com

**Comment by sergeyklay** [comment]
@andresgutierrez 
- Added support for `mailto:something@something.com`
- `http://localhost/something` works fine

Can you explain please `//localhost/something` ?

**Comment by andresgutierrez** [comment]
It takes the current scheme according to the served page: http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by sergeyklay** [comment]
Ok, added support for CDN

**Pull request merged**
