### PR TITLE
Amended Phalcon\Mvc\Model\Query\BuilderInterface::join() to specify type join

### PR DESCRIPTION
**Pull request by andrew-demb**

### CODE REVIEW

**Review by sergeyklay — APPROVED** [review]

**Comment by Jurigag** [comment]
Isn't this some kind of bug in zephir ? It shouldn't allow to implement interface method with additional parameter, like parameters in method header should be the same in interface and class @andresgutierrez @sergeyklay

**Comment by andrew-demb** [comment]
@sergeyklay, we can't just change target branch instead of close PR?

**Comment by Jurigag** [comment]
I think you can, don't know really why it was closed.

**Comment by sergeyklay** [comment]
It  was closed by mistake. I'm sorry

**Comment by sergeyklay** [comment]
@andrew-demb Could you please

**Comment by andrew-demb** [comment]
I will fix conflicts for about two or three days

**Comment by sergeyklay** [comment]
@andrew-demb

**Comment by andrew-demb** [comment]
@sergeyklay, done

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
