### PR TITLE
Refactored tests

### PR DESCRIPTION
**Pull request by carusogabriel**
Hello!

* Type: bug fix | new feature | **`code quality`** | documentation
* Link to issue: none

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

I've refactored several tests, using:
- `assertInternalType` and `assertNotInternalType` instead of `is_*` and `gettype` methods;
- `assertInstanceOf` instead of  `get_class`;
- `assertNull` and `assertNotNull` instead of strict comparisons with `null` keyword;
- `assertTrue` instead of strict comparisons with `true` keyword;
- `assertFalse` and `assertNotFalse` instead of strict comparisons with `false` keyword;
- `assertSame` instead of strict comparisons;
- `assertContains` instead of `in_array` method;
- `assertStringEqualsFile` when comparing a `string` and `file`;
- `assertArrayHasKey` instead of `array_key_exists` method;
- `assertFileExists` and `assertFileNotExists` instead of `file_exists` method;
- `assertGreaterThan` for mathematical comparisons.

### CODE REVIEW

**Comment by sergeyklay** [comment]
@carusogabriel Could you please sort out with failed tests

**Comment by carusogabriel** [comment]
@sergeyklay The tests [are failing](https://travis-ci.org/phalcon/cphalcon/jobs/319707025#L1013) because of `symfony/yaml` `Parser` class. [In line 510](https://github.com/symfony/yaml/blob/master/Parser.php#L510), the return type method has some PHP 7.1 notation. From where this dependency come from? Or should we limit it in your `composer.json`?

**Comment by sergeyklay** [comment]
@carusogabriel Yes, limit it in your composer.json. Good job.

/cc @Jurigag

**Comment by Jurigag** [comment]
But it doesn't change anything. Don't limit anything, just comment out ignore platform reqs.

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/pull/13230 Just pull those changes after they will be merged.

**Comment by carusogabriel** [comment]
Ok. As #13230 gets merge, I’ll rebase this PR as se if everything passes 😄

**Comment by sergeyklay** [comment]
@carusogabriel #13230 was merged

**Comment by carusogabriel** [comment]
Ok. I’m getting home, I’ll rebase 😇

**Comment by carusogabriel** [comment]
@sergeyklay Done, everything is working now :tada:

**Review by Jurigag — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
