### PR TITLE
Constructors should never declare return type [skip appveyor]

### PR DESCRIPTION
**Pull request by sergeyklay**
Hello!

* Type: bug fix
* Link to issue: -

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change: Constructors _should never_ declare return type.
Thanks.

/cc @niden

### CODE REVIEW

**Comment by ruudboon** [comment]
Is this something Zephir specific? Looks like the default return type is void

https://www.php.net/manual/en/language.oop5.decon.php#object.construct

**Comment by sergeyklay** [comment]
Zephir != PHP. Did you see something related in the Zephir docs? PHP driven development in Zephir leads to unexpected results:  https://travis-ci.org/phalcon/cphalcon/jobs/588067789

**Comment by ruudboon** [comment]
> Zephir != PHP. Did you see something related in the Zephir docs? PHP driven development in Zephir leads to unexpected results: https://travis-ci.org/phalcon/cphalcon/jobs/588067789

Missed it btw in the docs of Zephir.

**Review by ruudboon — APPROVED** [review]

**Comment by sergeyklay** [comment]
@ruudboon Check any constructor here https://www.php.net/manual/en/book.spl.php

**Pull request merged**
