### PR TITLE
Fixed checking case insensitive image extensions

### PR DESCRIPTION
**Pull request by agim-a**
Replaced **strcmp** with **strcasecmp** for checking image extenstions

### CODE REVIEW

**Comment by sergeyklay** [comment]
or just use one time `strtolower(ext)` :)

**Comment by andresgutierrez** [comment]
@sergeyklay +1

**Comment by agim-alb** [comment]
That is how I use it while I code, and I did not want to change the programming style of the file

**Comment by KorsaR-ZN** [comment]
@sergeyklay +1

**Comment by andresgutierrez** [comment]
@agim-alb Could you please change it to one strtolower?

**Comment by agim-alb** [comment]
Changed it using strtolower. 

Also fixed a bug using imagepng instead of imagejpeg to create png images

**Comment by sergeyklay** [comment]
> Also fixed a bug using imagepng instead of imagejpeg to create png images

:+1:

**Comment by andresgutierrez** [comment]
I'v reverted this merge, could you please submit it to the 2.0.x branch?

https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md#pull-request-checklist

**Comment by sergeyklay** [comment]
Oh.. it was a PR to the master

**Pull request merged**
