### PR TITLE
adding type_json support for mysql dialect

### PR DESCRIPTION
**Pull request by ChangePlaces**
Hello!

* Type: bug fix | new feature

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR. - no tests exists for mysql dialect?

Small description of change:

adding type_json support for mysql dialect

Thanks

### CODE REVIEW

**Comment by ChangePlaces** [comment]
not sure why the ci builds have failed?

**Comment by Jurigag** [comment]
Looks like some travis/github issue.

**Comment by sergeyklay** [comment]
The tests failed related to the composer dependencies. I fixed this in the 3.2.x branch: https://github.com/phalcon/cphalcon/compare/0f9f9e37351df03b1e457bd6155b788426c41027...04044ff3a11488f4f17a192ecef884fa675915de

You have to cherry pick these changes to the 4.0.x branch to be able to run tests.

**Comment by ChangePlaces** [comment]
As this would be a non-breaking change, wouldn't it be more suitable for 3.2 as per [SEMVER](http://semver.org/)?

**Comment by sergeyklay** [comment]
@ChangePlaces The 3.2.x version is last on 3.x branch. Thus we can accept this on 4.0.0

**Comment by sergeyklay** [comment]
Cc: @phalcon/framework-team @phalcon/core-team

**Comment by sergeyklay** [comment]
Closing in favor of https://github.com/phalcon/cphalcon/pull/13216. Thank you for contributing

**Pull request closed without merging**
