### PR TITLE
Criteria::FromInput functionality added

### PR DESCRIPTION
**Pull request by rudiservo**
Added functionality to the Criteria::FromInput method

current stable has no use for values that are arrays
it wont creak current stable default funcionality since arrays are passed as "%Array%"

so with this modification a column with more then one parameter will have OR.

example:

```
name => ["john", "jon"] 

 ([name] like :name0: **OR** name like :name1: [bind] => ["name0" => "john", "name1" => "jon"])
```

again nothing fancy just some added functionality.

Tested and working

### CODE REVIEW

**Comment by Jurigag** [comment]
As you see tests are failing

**Comment by rudiservo** [comment]
I deleted the extra spaces before and after the "=" and left just one, this is why it is failing

-    'conditions' => '[id]  =  :id:'

+    'conditions' => '[id] = :id:'

**Comment by Jurigag** [comment]
So you need to change it in tests.

**Comment by Jurigag** [comment]
And squash commits so it would contain only 1 commit.

**Comment by Jurigag** [comment]
To squash this into one commit you need to:

Rebase onto 2.1.x upstream(phalcons repo). Squash all commits. Config your git repo:
git config --global push.default simple
And do force push.

**Comment by rudiservo** [comment]
Hey sorry, about the mess
Kind of new in squashing things.
I am using Atom, but usually do everything on a terminal
will get the hang of it just screwing up things on my end thanks for the tip

**Comment by rudiservo** [comment]
Done testing should be done in 30 minutes, thanks ;)

git rebase -i HEAD~2
git push origin 2.1.x --force

**Comment by rudiservo** [comment]
Should I add unit tests for this feature?

**Comment by Jurigag** [comment]
Well that wouldn't be bad. But add them in new tests folder: https://github.com/phalcon/cphalcon/tree/2.1.x/tests

**Comment by rudiservo** [comment]
there are missing a lot of tests here, is there an issue or todos to be made for the new tests folder?

**Comment by Jurigag** [comment]
Yes they are missing, just add a new test folder in the same naming convention that already there. I think @sergeyklay somewhere posted link but i can't find it now.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/blob/2.1.x/tests/README.md

**Comment by sergeyklay** [comment]
@rudiservo

**Comment by rudiservo** [comment]
yes sorry, work came along, trying to make the old and new test for criteria.

**Pull request closed without merging**
