### PR TITLE
Added describeReferences method in postgresql DB

### PR DESCRIPTION
**Pull request by sergeysviridenko**
Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/438

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

- Fixed `Phalcon\Db\Dialect\Postgresql::describeReferences` to generate correct SQL
- Added `Phalcon\Db\Adapter\Pdo\Postgresql::describeReferences` for proper creating `Reference` object [phalcon/phalcon-devtools#438](https://github.com/phalcon/phalcon-devtools/issues/438)

Thanks

### CODE REVIEW

**Comment by tztztztz** [comment]
Your file phalcon/db/adapter/pdo/postgresql.zep is still missinga already merged and approved changes in https://github.com/phalcon/cphalcon/issues/12842

**Review by sergeyklay — CHANGES_REQUESTED** [review]
This PR need to be rebased onto 3.2.x

**Comment by sergeyklay** [comment]
Could you please submit just the commits that belong to the PR?

**Comment by sergeysviridenko** [comment]
This PR I'll close. New PR with rebased branch https://github.com/phalcon/cphalcon/pull/12982

**Pull request closed without merging**
