### PR TITLE
Add service provider interface to configure services by context

### PR DESCRIPTION
**Pull request by caiofralmeida**
Hello!

* Type: new feature

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

With this interface it is possible to separate services by context, improving the organization of applications have many dependencies in Container:

e.g:

```php
use Phalcon\Di\ServiceProviderInterface;
use Phalcon\DiInterface;

class SomeComponent
{
}

class SomeServiceProvider implements ServiceProviderInterface
{
    public function register(DiInterface $di)
    {
        $di['foo'] = function () {
            return 'bar';
        };

        $di['fooAction'] = function () {
            return new SomeComponent();
        };
    }
}

$di = new \Phalcon\Di\FactoryDefault();
$di->register(new SomeServiceProvider());

$di->get('fooAction');
```
Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please submit this PR to the 3.1.x branch?

**Comment by caiofralmeida** [comment]
@sergeyklay It is possible to submit PR to 3.1.x and 3.0.x, because we use 3.0.x in our projects.

Thanks.

**Comment by Jurigag** [comment]
But this is new feature. From phalcon 3 we are following semver which means 3.0.x is only for bug fixes.

**Comment by caiofralmeida** [comment]
@Jurigag I understand, I will submit in branch 3.1.x.

Thank you!

**Pull request closed without merging**
