### PR TITLE
Fix Dynamic update soft delete for renamed model does not work as exp…

### PR DESCRIPTION
**Pull request by limingxinleo**
…ected!

Hello!

* Type: bug fix 
* Link to issue: #13306, #13302

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Thanks

### CODE REVIEW

**Comment by virgofx** [comment]
I believe this also fixes the similar issue: #13302 

The solution in 13302 is also what was done in this solution.

Ping @Jurigag to confirm.

**Comment by Jurigag** [comment]
Looks like fine, though appveyor fails.

**Comment by sergeyklay** [comment]
@limingxinleo Could you please update change log? @Jurigag I'll fix AppVeyor's build a bit later.

**Comment by limingxinleo** [comment]
@sergeyklay done

**Comment by limingxinleo** [comment]
I just updated a releasenote.md.

oh my god...

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you

**Comment by virgofx** [comment]
Thank you. ETA for patch release? Need this in production

**Comment by sergeyklay** [comment]
@virgofx I'll try to release next weekend

**Comment by virgofx** [comment]
Perfect 👍

**Pull request merged**
