### PR TITLE
Corrected parameter types in Debug\Dump

### PR DESCRIPTION
**Pull request by SidRoberts**

### CODE REVIEW

**Review by sergeyklay — CHANGES_REQUESTED** [review]
Could you please submit this PR to the `3.0.x` branch?

**Comment by Jurigag** [comment]
Maybe im blind, but it is already ?

**Comment by SidRoberts** [comment]
It's currently based on 3.0.x. :stuck_out_tongue:

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
