### PR TITLE
Fix #10344

### LINKED ISSUE #10344: [2.0.x] Model Column Map Bug
#### Create DB & Table

For example DB name - **test**
SQL dump:

```sql
CREATE TABLE `visitors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `name` VARCHAR(128) DEFAULT NULL,
  `last_online` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `visitors` (`email`, `name`, `last_online`)
VALUES ('foo@bar.com', 'Test User', '0');
```

#### Create php file

For example file called `test.php`.
Put code:

```php
<?php

$di = new Phalcon\DI();

$di->set('db', function () {
    $connection = new Phalcon\Db\Adapter\Pdo\Mysql(array(
        'host'       => 'localhost',
        'username'   => 'root',
        'password'   => '',
        'dbname'     => 'test',
        'persistent' => 'true',
    ));

    $eventsManager = new Phalcon\Events\Manager();

    $eventsManager->attach('db', function($event, $connection) {
        if ($event->getType() == 'afterQuery') {
            $sql = $connection->getSQLStatement();

            if (false !== strpos($sql, 'FROM `INFORMATION_SCHEMA`') || 0 === strpos($sql, 'DESCRIBE')) {
                return;
            }

            $bind = $connection->getSQLVariables();
            $bindParams = (empty($bind) ? '' : json_encode($bind, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));

            // Debug queries
            error_log('QUERY: ' . $sql);
            error_log('PARAMS: ' . $bindParams);
        }
    });

    $connection->setEventsManager($eventsManager);

    return $connection;
});

$di->set('modelsManager', new Phalcon\Mvc\Model\Manager());
$di->set('modelsMetadata', new Phalcon\Mvc\Model\Metadata\Memory());

class Visitors extends Phalcon\Mvc\Model
{
    public $id;
    public $email;
    public $name;
    public $lastOnline;

    public function getSource()
    {
        return 'visitors';
    }

    public function columnMap()
    {
        return [
            'id'          => 'id',
            'email'       => 'email',
            'name'        => 'name',
            'last_online' => 'lastOnline',
        ];
    }

    public function testUpdate()
    {
        $phql = 'UPDATE Visitors SET lastOnline = ?0 WHERE id = ?1';

        $result = $this->getModelsManager()->executeQuery($phql, [
            0 => time(),  // NOTE
            1 => 1
        ]);

        return $result->success(); 
    }
}

$visitors = new Visitors();

var_dump($visitors->testUpdate()); // true to stdOut
```

#### Run script from console

```bash
$ php test.php
bool(true)
```

#### Let's go to error log.

```bash
$ tail -f /var/log/php_error.log
QUERY: SELECT `visitors`.`id`, `visitors`.`email`, `visitors`.`name`, `visitors`.`last_online` FROM `visitors` WHERE `visitors`.`id` = :1
PARAMS: {":1":1}
QUERY: UPDATE `visitors` SET `email` = ?, `name` = ?, `last_online` = ? WHERE `id` = ?
PARAMS: ["foo@bar.com","Test User","0","1"]
```

#### Questions

1. Why I don't see timestamp in log for bind params?
2. Main question: Why row not updated?

### PR DESCRIPTION
**Pull request by dreamsxin**

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Thanks again

**Comment by sergeyklay** [comment]
@dreamsxin Thanks

**Comment by dreamsxin** [comment]
:)

**Pull request merged**
