### PR TITLE
Introducing ability of multiple directories for namespace

### PR DESCRIPTION
**Pull request by sergeyklay**
Fixed issue #11021

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Thanks!

**Comment by virgofx** [comment]
@sergeyklay Does this incorporate namespaced related view/partial support as outlined in #692?  If not, would it be possible to incorporate this into the PR as well?

Thanks!

**Comment by sergeyklay** [comment]
@virgofx  This PR introduce class loading through searching for the namespace in multiple directories. 
Only classes, not views. In particular, it solves [this issue](https://github.com/phalcon/cphalcon/issues/11021) only.

**Comment by virgofx** [comment]
@sergeyklay Since you just worked on this any chance you could see about implementing `https://github.com/phalcon/cphalcon/issues/692#issuecomment-50416113` which would just be directory support for views based on controller namespaces?  I have a small mockup in my code base extending View to handle this.

Pseudo Code:

View:
* Add a flag to not break backward compatibility.
* Update render() to check if flag is defined from [ useNamespacedViews() ] and if so, quickly parse the namespace and render the hierarchy starting at the bottom.  (Essentially each parent just gets rendered as a template before/after would)

**Pull request merged**
