### PR TITLE
[2.0.0] can't delete builder limit

### PR DESCRIPTION
**Pull request by tmihalik**
can't delete limit with $builder->limit(null)

(for example paginator)

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by tmihalik** [comment]
@ovr 
convinced me

**Comment by tmihalik** [comment]
@ovr 
convinced me

**Comment by ovr** [comment]
Rebase it to 1 commit

```
git reset --soft HEAD~2
git commit -m "Fix setLimit for Builder"
git push %YOU REMOTE% patch-5 -f
```

**Comment by ovr** [comment]
ping @phalcon

**Pull request merged**
