### PR TITLE
Replace deprecated `each()` function with for...in loop

### PR DESCRIPTION
**Pull request by jmsfwk**
Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/cphalcon/issues/13253

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

The `each()` function in `Phalcon\Debug\Dump` is deprecated. I have replaced it with of `for...in` loop.

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
Any notice or warning for this code?

**Comment by jmsfwk** [comment]
> **Deprecated**: The each() function is deprecated. This message will be suppressed on further calls [...]

http://php.net/manual/en/function.each.php

**Comment by sergeyklay** [comment]
@jmsfwk This is PHP docs, not Zephir. Right? :) We didn't deprecate this function in Zephir. So my question is there any PHP notice or/and warning using this class/method?

**Comment by jmsfwk** [comment]
Yes this is PHP, I get an `E_DEPRECATED` error when using `Phalcon\Debug\Dump`.

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
@jmsfwk Could you please update change log too?

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
