### PR TITLE
Fixed memory leak

### PR DESCRIPTION
**Pull request by sergeyklay**
Refs: #12115, #11995, #12116

### CODE REVIEW

**Comment by tembem** [comment]
@sergeyklay I tested with my previous issue https://github.com/phalcon/cphalcon/issues/12057 with memory_limit=128M. Script still won't work with this new patch :(. Maybe another problems.

**Comment by sergeyklay** [comment]
@tembem maybe there's another problem. we will check

**Comment by sergeyklay** [comment]
@tembem Have you use Phalcon 3.0.0 ?

**Comment by tembem** [comment]
@sergeyklay Phalcon 3.0.x. I ended using plain PDO for big result.

**Comment by tembem** [comment]
@sergeyklay sorry, my bad. My issue https://github.com/phalcon/cphalcon/issues/12057 is solved by this patch. Need to build latest commit with zephir.

Thank you so much. You're the best.

**Comment by sergeyklay** [comment]
Fine!

**Pull request merged**
