### PR TITLE
handles "options" arg on Collection aggregate

### PR DESCRIPTION
**Pull request by challet**
As seen on http://php.net/manual/fr/mongocollection.aggregate.php there is a second argument available for MongoCollection::aggregate.
It accepts for instance a _maxTimeMS_ argument which can be very useful to increase for the aggregation process.

### CODE REVIEW

**Review by Jurigag — COMMENTED** [review]
`Phalcon/Mvc/Colllection` requires changes anyway which are gonna be done in 3.1.0 or later to support both php versions.

**Comment by sergeyklay** [comment]
@challet Could you pleas  rebase onto 3.1.x, amend CHANGELOG.md and add tests

**Comment by challet** [comment]
Hi @sergeyklay, I'm trying to find a documentation about using the test suite on a custom Phalcon build. Would you have some link to help me with this matter please ?

**Comment by sergeyklay** [comment]
@challet Hello

Readme: https://github.com/phalcon/cphalcon/tree/master/tests
Collection Test: https://github.com/phalcon/cphalcon/blob/master/tests/unit/Mvc/CollectionTest.php
Example environment: https://github.com/phalcon/cphalcon/blob/master/.travis.yml

**Pull request closed without merging**
