### PR TITLE
Install apcu_bc-beta on php 7 tests

### PR DESCRIPTION
**Pull request by Jurigag**

### CODE REVIEW

**Comment by Jurigag** [comment]
Well, i will need to test it if it works before merged on php 7.

**Comment by sergeyklay** [comment]
Thanks

**Comment by Jurigag** [comment]
But did someone checked it ? :D

**Comment by sergeyklay** [comment]
The Phalcon 2.1.0 with support of PHP 7 isn't released yet. It is time to test in this branch

**Comment by Jurigag** [comment]
Well if it will not work then mention me.

**Pull request merged**
