### PR TITLE
Fixed saving a model after fetching its related records

### PR DESCRIPTION
**Pull request by zsilbi**
Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/cphalcon/issues/13964

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Small description of change:

I've added some tests to check if this issue exists at all.
The tests failed, so added a fix in a previous PR (https://github.com/phalcon/cphalcon/pull/13970) but ran into a conflict so I made a new PR.

The problem is, that the related models are stored in the `_related` storage inside Model after accessing via `__get()`. It is not stored when accessing related records via `__call()`.

When the model is saved,` _postSaveRelatedRecords` is being called and it iterates through `_related` and tries to save the previously fetched related records.

For now, I just removed adding these records to the `_related` as it's not mandatory when you are only reading them.

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@zsilbi Could you please provide a small example of code which leads to an error you're fixes

**Comment by sergeyklay** [comment]
I will keep this open for a some time to allow other contributors a chance to speak up, and to take a fresh look at it later. But at the moment it seems good to me.

/cc @phalcon/framework-team

**Review by sergeyklay — DISMISSED** [review]

**Comment by niden** [comment]
@zsilbi can you update the changelog when you get a chance please and rebase.

Thanks!

**Comment by virgofx** [comment]
We need another test as it looks like this removed functionality.

Need to query a related record multiple times and ensure the database is only hit once. In this case, it will be re-queried every time when you remove that line.

**Comment by zsilbi** [comment]
> We need another test as it looks like this removed functionality. I'm not sure with regards to the run-time exception or what was generating ... but this is likely not the right fix as this will break caching.
> 
> Need to query a related record multiple times and ensure the database is only hit once. In this case, it will be re-queried every time when you remove that line.

1. In `Model::__get()`, relations are obtained via `Model/Manager::getRelationByAlias()`. `Manager` caches them properly.
2. Queried related objects are stored in properties of the `Model`. This functionality in not affected by this PR.

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @zsilbi

**Comment by virgofx** [comment]
Well now `isRelationshipLoaded` won't return correctly. If you're going to refactor the caching of related items ... it needs to be done everywhere. If we somehow double cached (manager + model) that needs to be more conveyed.

This needs to not be merged @niden.

**Comment by zsilbi** [comment]
> Well now `isRelationshipLoaded` won't return correctly. If you're going to refactor the caching of related items ... it needs to be done everywhere. If we somehow double cached (manager + model) that needs to be more conveyed and fixed in all locations. Commenting out one line breaks other areas. As I mentioned ... this still will re-query ... so it's broken as you haven't tested for that anywhere.
> 
> This needs to not be merged @niden.
> 
> If a runtime exception is being thrown somewhere ... the fix is to not UNCOMMENT a line .. it's to fix the issue where the exception is being thrown and explain it properly with tests.

@virgofx it's a different issue then because if you query the items via `Model::__call()` (for example `$robot->getRobotParts()`) the relation is never added to the `Model::related` array anyway. 

If you investigate further you will notice that this related storage is only used before and after updating a models related records. Only if this storage is empty `_preSaveRelatedRecords` and `_postSaveRelatedRecords` will never run during an update.

**Comment by sergeyklay** [comment]
Just reverted this PR from 4.0.x branch

**Comment by sergeyklay** [comment]
@zsilbi Feel free to discuss the issue here and re-send a new one, again if the need arises

**Comment by virgofx** [comment]
@zsilbi I'm not disagreeing that the original implementation is poor. If we're going to remove the related ... it should be removed everywhere and we should have tests to account for what I described above. It's still being used when setting related items and checking if it's loaded. So if we're going to remove the `related` attribute for handling that .... all 3 things need to be taking care of:

1 - getting related
2 - setting related
3 - checking related
4 - tests - all 3 above +
   please add: 
      1 - multiple repeat getting related -- instantiate a new SQL logger of the queries to show only the first one is set.

**Comment by zsilbi** [comment]
Ok guys, I've done some research to get the complete picture about the purpose of `Model::related[]`

In #12772 @Surt mentoined that the former `Model::_related[]` (now `related[]`) storage is only used for belongs-to relations. Maybe that's why it must've failed when it was populated with other type of relations.

I am not sure if @CameronHall had been aware of this in #13616 when he'd added that line that I uncommented here. When `Model::isRelationshipLoaded()` was implemented, it only returned true when the related records were accessed as a property (`$robot->robotParts`). It passed the tests that time because they were only written to cover this case.

Also, this related storage problem needs to be redone together with issue #13531, as storing objects only in properties as a cache and using `isset()` will make the `reusable` option uneffective.

Please advise.

**Comment by virgofx** [comment]
Like I said ... the related records is very *finicky* and any changes will either be super minor ... or a refactor and need to cover the cases I've mentioned above. We have to be very careful because I have made changes in extending models and small changes like this cause issues where repeat queries kill production servers .... from an end-users application logic ... they may want to use    `$myModel->getFancyRelated()->getValue()` in numerous places throughout code.

**Comment by CameronHall** [comment]
I agree `isRelationshipLoaded` is a silly method. I only added it because I was cleaning up the PR backlog. In hindsight, we should only be able to rely upon `__isset` to handle this.

**Pull request merged**
