### PR TITLE
Add Aliases for ciphers in Phalcon\Crypt

### PR DESCRIPTION
**Pull request by ibpavlov**
Hello!

* Type: bug fix | code quality

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
The old versions supported aliases of ciphers and now it doesn't. They are easier to use and migration will be easier for those who use this class. 

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
Update changelog too. Also we don't accept PRs to master branch. Please send it to 3.0.x.

**Comment by sergeyklay** [comment]
1. We don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.0.x` branch?
2. Could you please update CHANGELOG.md

**Comment by ibpavlov** [comment]
I see that on 3.0.x are only fixes. If I have to I can change it to 3.1.x. 
I'm sorry that I do things slow, but this is my first official pull-request.

**Comment by Jurigag** [comment]
Well you wrote this is bug fix, so it's for 3.0.x, not sure which exactly bug it's fixing.

**Comment by ibpavlov** [comment]
When I migrated my application to Phalcon 3.0.x it gave me an exception. These changes fixed the issue. I've decided to try and contribute it directly and not to create an issue in the system for someone else to solve.

**Comment by Jurigag** [comment]
Yea np, but if it's really bugfix then 3.0.x is fine.

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
