### PR TITLE
 add persistent id for Redis `pconnect()` method.

### PR DESCRIPTION
**Pull request by lanlin**
we'd better have a persistent id for Redis pconnect() method.
cause without it we can't switch between multiple databases at in the same PHP process.
the data will always be saved to the last database without it.
as I know all Phalcon versions have this bug.

* Type: bug fix
* Link to issue: https://github.com/phalcon/cphalcon/issues/14334

check this: https://github.com/phpredis/phpredis#pconnect-popen

### CODE REVIEW

**Review by sergeyklay — DISMISSED** [review]

**Review by Jurigag — CHANGES_REQUESTED** [review]
Change branch, we don't accept prs to master branch.

**Review by niden — CHANGES_REQUESTED** [review]

**Review by ruudboon — CHANGES_REQUESTED** [review]
Can you update the CHANGELOG-4.0.md also?

**Comment by lanlin** [comment]
> Change branch, we don't accept prs to master branch.
> Also please target the 4.x branch and update the changelog. After that this is good to go.
> Can you update the CHANGELOG-4.0.md also?

@niden @ruudboon @Jurigag the above changes have been modified. there anything else?

**Comment by CameronHall** [comment]
@lanlin, you have a lot of commits in your PR that aren't relevant. Can you please only send the relevant commits?

**Comment by lanlin** [comment]
sorry，i based on a wrong branch, let me create a new pull.

**Pull request closed without merging**
