### PR TITLE
Improved Phalcon\Config\Adapter\Ini

### PR DESCRIPTION
**Pull request by dred86**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Thanks

**Comment by sergeyklay** [comment]
👍

**Comment by dred86** [comment]
Thank you too

**Comment by zytzagoo** [comment]
This breaks parsing option values that have php constants in them? (due to use of INI_SCANNER_RAW, in which case option values are not parsed according to http://php.net/manual/en/function.parse-ini-file.php)

This is a BC break (worked fine until 3.0) - might be a good idea to add it to the list of major incompatible changes somewhere

**Comment by sergeyklay** [comment]
https://blog.phalconphp.com/post/phalcon-3-0-0-released

**Comment by zytzagoo** [comment]
Hm, the blog post doesn't mention it (neither does the changelog)... 

Not really sure how to easily fix this yet, but I made a test which passes in 2.0.13 (and earlier) and fails in 3.0.0: https://github.com/zytzagoo/cphalcon/commit/cb5af1f7c9012734456381a2431e96e34b73a0bc

**Pull request merged**
