### PR TITLE
License update

### PR DESCRIPTION
**Pull request by niden**
Changed the `LICENSE.txt` to `LICENSE.md` throughout the framework so that GitHub can show our license in the front page.

This will be applied when RC3 is out.

### CODE REVIEW

**Comment by niden** [comment]
cc @sergeyklay @ruudboon

**Review by sergeyklay — CHANGES_REQUESTED** [review]
I need a plain text version so that tools I use to create installation packages can simple use license text w/o rendering it. So please leave txt version

**Comment by sergeyklay** [comment]
@niden Please take a look at . You don't need rename file to help GitHub show license in the front page. You just have to follow _the standard format of the license_ agreement and _not write anything extra_ to this file.

image

**Comment by niden** [comment]
In this case this can be closed

**Pull request closed without merging**
