### PR TITLE
Fix getRelations() method on Phalcon\Mvc\Model\Manager

### PR DESCRIPTION
**Pull request by RemyJeancolas**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Why `phalcon/cache/backend/redis.zep` 100644 → 100755 ?

**Comment by moisemorard** [comment]
Sorry, It's a mistake I fix that now

**Comment by moisemorard** [comment]
Done

**Comment by sergeyklay** [comment]
:+1:

**Comment by moisemorard** [comment]
Hello,
I've rebased the branch, so the title correspond with the last commit.
I create another branch dedicated to redis.
@phalcon : Please get back to me if it's ok for you ;)
Thanx

**Comment by phalcon** [comment]
Thanks

**Pull request merged**
