### PR TITLE
Data not update when update value from integer to decimal

### PR DESCRIPTION
**Pull request by olivier-monaco**
Issue #3247 

Strict type comparisons to detect changes. Need someone to check my code...

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please rebase against 2.0.0?

**Comment by olivier-monaco** [comment]
This is old... do you want a new pull request?

**Comment by andresgutierrez** [comment]
Yes please

**Comment by olivier-monaco** [comment]
I need some time... Zephir segfault after update to latest version...

**Pull request closed without merging**
