### PR TITLE
Add service provider interface to configure services by context

### PR DESCRIPTION
**Pull request by caiofralmeida**
Hello!

* Type: new feature

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

With this interface it is possible to separate services by context, improving the organization of applications that have many dependencies in Container.
e.g:
```php
use Phalcon\Di\ServiceProviderInterface;
use Phalcon\DiInterface;

class SomeComponent
{
}

class SomeServiceProvider implements ServiceProviderInterface
{
    public function register(DiInterface $di)
    {
        $di['foo'] = function () {
            return 'bar';
        };

        $di['fooAction'] = function () {
            return new SomeComponent();
        };
    }
}

$di = new \Phalcon\Di\FactoryDefault();
$di->register(new SomeServiceProvider());

$di->get('fooAction');
```

Thanks

### CODE REVIEW

**Comment by caiofralmeida** [comment]
@sergeyklay and @Jurigag (PR from https://github.com/phalcon/cphalcon/pull/12538) in 3.1.x branch.

**Comment by Jurigag** [comment]
Tests are failing(intents). Also squash commits.

**Comment by caiofralmeida** [comment]
@Jurigag I'll create another PR because I had problems with commits overflow :(

**Comment by Jurigag** [comment]
Well im just always rebasing onto 3.1.x upstream in phpstorm, squashing all commits and force pushing it. Not sure about command line, it can be done easier as far as i know.

**Comment by caiofralmeida** [comment]
@jurigag how to setup localy environment to run codeception tests?

**Comment by sergeyklay** [comment]
@caiofralmeida Unfortunately there are a side-effect. As you probably know since 3.0.0 Phalcon follows the semantic versioning. Given a version number `MAJOR.MINOR.PATCH` (eg. v1.2.3), increment the:

* `MAJOR` version when you make incompatible API changes,
* `MINOR` version when you add functionality in a backwards-compatible manner, and
* `PATCH` version when you make backwards-compatible bug fixes.

So I think we can't accept this PR to the 3.x.x at all. In this case I'll just ask you in future to rebase (or do it yourself) again your RP wen we'll create the `4.0.x` branch.  Until then, your PR will remain frozen as all others: https://github.com/phalcon/cphalcon/milestone/21

**Comment by Jurigag** [comment]
Wait what, why we can' accept it ? How this breaks BC ? @sergeyklay

**Comment by sergeyklay** [comment]
new interface will break all extended classes for 3rd party developers

**Comment by Jurigag** [comment]
But this PR is not adding new interface.

**Comment by Jurigag** [comment]
It will break only if they have they own register method. So yea it's breaking BC.

**Comment by caiofralmeida** [comment]
Will break BC only if the client implemented this method in some extended class, but I consider this a design problem :(

@Jurigag and @sergeyklay thanks for all feedbacks :+1:

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
LGTM

**Comment by david-duncan** [comment]
Is anything ever going to happen with this? Lets at least get it squashed and rebased

**Comment by sergeyklay** [comment]
I'll merge it title later. For a day or two

**Comment by Kachit** [comment]
shared/unshared option ?

**Comment by sergeyklay** [comment]
Implemented in the `3.2.x` branch. Thank you for contributing.

**Pull request closed without merging**
