### PR TITLE
4.1.x lazy loader get handler

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: new feature
* Link to issue: #14871 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change: It adds `getHandler` method to `LazyLoader` so we can real handler. Right now it's not possible. 

Thanks

### CODE REVIEW

**Comment by Jurigag** [comment]
Any idea why this certain test fails?

**Comment by ruudboon** [comment]
> Any idea why this certain test fails?

Hmm not directly. Currently working on a backup laptop so can't easily test it for you. Maybe you stumbled on a bug as well?

**Comment by Jurigag** [comment]
Maybe, will check this when have a time to compile phalcon 4 and run a test.

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/cphalcon/pull/14872

**Pull request closed without merging**
