### PR TITLE
[2.0.x] [NFR] Added method generate random text

### PR DESCRIPTION
**Pull request by KorsaR-ZN**
Generates random text in accordance with the template:

```
echo Phalcon\Text::dynamic("{Hi|Hello}, my name is a {Bob|Mark|Jon}!"); 
    // Hi my name is a Bob

echo Phalcon\Text::dynamic("{Hi|Hello}, my name is a {Bob|Mark|Jon}!");
    // Hi my name is a Jon

echo Phalcon\Text::dynamic("{Hi|Hello}, my name is a {Bob|Mark|Jon}!");
   // Hello my name is a Bob
```

### CODE REVIEW

**Comment by sergeyklay** [comment]
Can you please add small test?

**Comment by andresgutierrez** [comment]
Could you please rebase?

**Comment by KorsaR-ZN** [comment]
@andresgutierrez rebased

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
