### PR TITLE
Removed converting the action name to lowercase in `Phalcon\Mvc\Route…

### PR DESCRIPTION
**Pull request by makerlabs**
Fixed issue #11568

### CODE REVIEW

**Comment by andresgutierrez** [comment]
This will break several applications

**Comment by sergeyklay** [comment]
@makerlabs 

This PR will result in serious breaks in many applications.
All developers will have to rename all view folders. 

We will return to this PR when the 2.2.x branch is ready.

**Comment by Jurigag** [comment]
But there is inconsistency now. The framework should be all about consistency, you can define actions with annotatons and it will be camel sensitive, but when define it in annotations it won't ?

**Comment by makerlabs** [comment]
OK no problem for now I will just use my branch. We could also add additional parameter that will change this behavior for routing but I don't think that this will be a good approach as Jurigag stated this is an inconsistency.

**Comment by fenixphp** [comment]
If it plays such a role in the views, why transform "lowercase" does not move directly the call view and keep the original name of the method?

**Pull request closed without merging**
