### PR TITLE
Fixed wrong return type in documentation (spelling error)

### PR DESCRIPTION
**Pull request by greew**

### CODE REVIEW

**Comment by Green-Cat** [comment]
You should edit the .zep file, not the generated .zep.c

**Comment by andresgutierrez** [comment]
@greew Ping

**Comment by greew** [comment]
Sorry for the whole close- and reopen stuff here. My first pull request on GitHub - I just need to understand all buttons :)
I hope it's better now :)

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
