### PR TITLE
Phalcon\Db\Dialect\Mysql must implement DialectInterface

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by 7thcubic** [comment]
hey @ovr 

when you edit doc blocks did you have some error for declaration in zephir? but build and run alright?

https://github.com/7thcubic/cphalcon/commit/8ff39872d1dcc121814e98b099743e527e1a64aa

after i did that it keep giving me a declaration of cloneResult in model.zep is different from cloneResult in modelinterface.zep

**Comment by ovr** [comment]
@7thcubic 
It's related to phpdocs
`Zephir` didnt use it for code generation or analyze!

Can you show an error in runtime?

**Comment by 7thcubic** [comment]
Fatal error: Declaration of Phalcon\Mvc\Model::cloneResult() must be compatible
with Phalcon\Mvc\ModelInterface::cloneResult(Phalcon\Mvc\ModelInterface $base, $
data, $dirtyState = NULL) in Unknown on line 0

**Comment by ovr** [comment]
Attention It's a Fatal error
disable phalcon ext
zephir fullclean
zephir install
enable phalcon

**Pull request merged**
