### PR TITLE
[4.0.0] Collections now use the Validation component

### PR DESCRIPTION
**Pull request by SidRoberts**
Refs: https://github.com/phalcon/cphalcon/issues/12098

### CODE REVIEW

**Comment by Jurigag** [comment]
Adding this already to 3.x.0 won't be hard and still BC. Only instanceof checks and that's it. Question is - are we want do it ?

**Comment by Jurigag** [comment]
Well im adding this for 3.1.0 with BC. So in your PR there will be only need to remove old ability and and old classess.

**Comment by SidRoberts** [comment]
I had to remove some files from ext/ because, previously, AppVeyor reached 100 errors and would stop compiling.

**Comment by sergeyklay** [comment]
Let me deal with this a bit later. I'll try to sort out tomorrow.

**Comment by sergeyklay** [comment]
@SidRoberts Regenerated the build and updated `ext/` dir. Could you please rebase

**Comment by niden** [comment]
Thank you!

**Pull request merged**
