### PR TITLE
Added the ability to truncate DB tables

### PR DESCRIPTION
**Pull request by SidRoberts**
I've purposely left `truncateTable()` out of DialectInterface to maintain BC.

### CODE REVIEW

**Comment by sergeyklay** [comment]
@SidRoberts Could you please update `CHANGELOG.md`

**Comment by SidRoberts** [comment]
CHANGELOG updated.

**Comment by sergeyklay** [comment]
Thanks

**Review by lisek2000 — COMMENTED** [review]
- [ ] Hello,

what about calling truncate for table referenced by foreign keys? Current implementation will fail as e.g. mysql will not allow to truncate such table.  You can disable checking by SET FOREIGN_KEY_CHECKS = 0;  but I don't know if it's not too risky for data integrity.

**Comment by sergeyklay** [comment]
@lisek2000 As you can see these are only the dialect generators. They do not do any work, they just create the SQL that can be executed later.

**Comment by lisek2000** [comment]
@sergeyklay my bad. It's ok then.

**Pull request merged**
