### PR TITLE
Ability to load individual files in Phalcon\Loader

### PR DESCRIPTION
**Pull request by rahuldroy**
There are cases where you have helper files which don't have any classes. In composer, you add something like this to add them - 

``` javascript
{
...
     "autoload": {
         "files": ["src/blah.php"],
     },
...
}
```

The changes below will allow something like this - 

``` php
$loader = new Loader();
$loader->registerFiles(['src/blah.php']);
```

`blah.php` will added using require and all the contents will be usable as normal.

This indirectly addresses -
https://github.com/phalcon/cphalcon/issues/2533
https://github.com/guzzle/guzzle/issues/707

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please update `CHANGELOG.md`?

**Comment by rahuldroy** [comment]
Done

**Comment by sergeyklay** [comment]
Could you please rebase?

**Comment by sergeyklay** [comment]
This PR has conflicts with current 2.1.x branch

**Comment by sergeyklay** [comment]
@rahuldroy

**Comment by rahuldroy** [comment]
@sergeyklay, Apologies for the delay. I'll have it done tonight.

**Comment by rahuldroy** [comment]
Closing this as I screwed this one up pretty badly. A new PR can be seen at https://github.com/phalcon/cphalcon/pull/11849

**Comment by Jurigag** [comment]
Just next time:
-rebase onto 2.1.x
-squash commits
-resolve conflicts if any
-force push

And done.

**Pull request closed without merging**
