### PR TITLE
escape rowcount alias

### PR DESCRIPTION
**Pull request by dnapierata**
Hello!

* Link to issue: [#12950](https://github.com/phalcon/cphalcon/issues/12950)

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change: Escaped row count aliases with double quotes

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@dnapierata Could you please update the CHANGELOG.md

**Comment by sergeyklay** [comment]
As you can see the tests failed. And yes, I'm not sure about escaping the PHQL

**Comment by dnapierata** [comment]
I agree I don't think that is the correct way to escape when using PHQL. 
I used this as a reference:
[https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L1135](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L1135)
 but it is not actally using PHQL, just raw SQL. 
What about using the built in escaping of PHQL by using brackets? 
Ex: `[rowcount]`

**Comment by Jurigag** [comment]
Well the failing test is about PHQL, i guess it should be `[rowcount]` most likely yea.

**Comment by dnapierata** [comment]
Any idea about the AppVeyor tests? It is getting a 404 when trying to download a php release

**Comment by Jurigag** [comment]
Not sure, seems unrelated, also update changelog.md and squash commits.

**Review by Jurigag — APPROVED** [review]

**Comment by sergeyklay** [comment]
@dnapierata Could you please create a small test which will cover code you have changed?

**Comment by dnapierata** [comment]
The tests which are already written for the querybuilder paginator cover this block of code. The only true way to test this feature would be to set up a database that has `ROWCOUNT` as a reserved word such as MSSQL, OpenEdge, Rave, etc. I'm not well familiar enough in this testing environment with setting up this level of config.

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
