### PR TITLE
WIP: Update params for deep assoc completion plugin

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: new feature | documentation
* Link to issue:https://github.com/phalcon/cphalcon/issues/13991

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR - not needed really, needs to check generated stubs
- [x] I have updated the relevant CHANGELOG - not required since it doesn't add any new feature
- [x] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change - no documentation change required

Small description of change: it adds `@param array config` etc on all methods having things like options, config etc with all keys which are accepted in those arrays, using plugin https://github.com/klesun/deep-assoc-completion for phpstorm it will autocomplete it in all usages of those methods.

Thanks

### CODE REVIEW

**Comment by niden** [comment]
We need to make sure that these comments end up in the stubs with `zephir stubs`

**Comment by sergeyklay** [comment]
@niden The `zephir stubs` command should leave they as is. If there are bugs, we can follow up in separated Zephir issue.

**Comment by Jurigag** [comment]
Yea they are leaving them because regex don't detect it as `@param` currently, but then it still add new `@param mixed config` etc because of that. Need to test if everything will work with this.

**Comment by Jurigag** [comment]
Currently in generated php file it looks like this:

```
/**
@param array config = [
    'test' => 'key'
]
@param mixed $config
*/
```

So we need changes to zephir stubs generation first.

**Comment by sergeyklay** [comment]
@Jurigag As a far as I know @AlexNDRmac working on this by improving `zephir stubs` command. 

Notice that annotations in the following form:
```
@param array config = [
    'test' => 'key'
]
```
are in non standard form and working with this should considered as a feature request. But actually there are more urgent (and honestly critical) things we should do firstly. So working with non-standard annotation isn't a top priority

**Comment by Jurigag** [comment]
Will check it tomorrow.

**Comment by ruudboon** [comment]
@Jurigag Any progress on this one?

**Review by ruudboon — APPROVED** [review]

**Comment by niden** [comment]
Thank you @Jurigag 

We need to make sure that these propagate to the stubs.

**Pull request merged**
