### PR TITLE
[WIP] Added variable types.

### PR DESCRIPTION
**Pull request by SidRoberts**
Hello!

* Type: code quality
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [-] I wrote some tests for this PR
- [-] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by SidRoberts** [comment]
Keep this open.

**Review by CameronHall — APPROVED** [review]

**Comment by niden** [comment]
@SidRoberts is this ready also?

**Comment by SidRoberts** [comment]
@niden I want to add as many types as possible so I'm 10% done. If a new release is due and you're on a merge spree then you can merge now. :stuck_out_tongue:

**Comment by niden** [comment]
@SidRoberts I am going to merge this now because you have already touched close to 50 files. Then we can merge the rest of the work in chunks.

Thanks for this!

**Review by niden — APPROVED** [review]

**Pull request merged**
