### PR TITLE
Fix for PHQL replaces field names in where #12971

### PR DESCRIPTION
**Pull request by felixDlh**
Hello!

This PR concern issue #12971. While using your framework in a project, we encoutered the same problem as described in the issue. This solution worked for us.
Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@felixDlh Could you please cover your changes by small unit test?

**Comment by felixDlh** [comment]
@sergeyklay Is it right for you now ?

**Comment by sergeyklay** [comment]
Merged by hand to the 3.2.x branch. Thank you

**Comment by sergeyklay** [comment]
@felixDlh Actually your patch is totally wrong
 
```diff
--- mvc/model/query.zep 2017-10-21 15:43:41.000000000 +0300
+++ mvc/model/query.zep 2017-10-21 15:43:58.000000000 +0300
         * Check if the qualified name is a column alias
         */
        let sqlColumnAliases = this->_sqlColumnAliases;
        if isset sqlColumnAliases[columnName] {
            var domain;

-		if isset sqlColumnAliases[columnName] && empty expr["domain"] {
  			return [
  				"type": "qualified",
  				"name": columnName
 			];
 		}

+		if isset sqlColumnAliases[columnName] && (!isset expr["domain"] || empty expr["domain"]) {
  			return [
  				"type": "qualified",
  				"name": columnName
 			];
 		}

        let metaData = this->_metaData;
```

as well as test

```diff
--- wrong test   2017-10-21 15:43:41.000000000 +0300
+++ correct test 2017-10-21 15:43:58.000000000 +0300
***************
*** 2,10 ****

  return [
      // PR #13124, ISSUE #12971
!     Missed space before WHERE and Robotina should be escaped 
-     "phql"     => 'SELECT UPPER('. Robots::class . '.name) AS name FROM ' . Robots::class . 'WHERE ' . Robots::class .'.name = Robotina',
      "expected" => [
-         'distinct' => 0,
          'models' => [
              Robots::class,
          ],
--- 2,9 ----

  return [
      // PR #13124, ISSUE #12971
+     "phql"     => 'SELECT UPPER('. Robots::class . '.name) AS name FROM ' . Robots::class . ' WHERE ' . Robots::class .'.name = "Robotina"',
      "expected" => [
          'models' => [
              Robots::class,
          ],
***************
*** 12,18 ****
              'robots'
          ],
          'columns' => [
!             Why??? 
-             'id' => [
                  'type' => 'scalar',
                  'balias' => 'name',
                  'sqlAlias' => 'name',
--- 11,17 ----
              'robots'
          ],
          'columns' => [
+             'name' => [
                  'type' => 'scalar',
                  'balias' => 'name',
                  'sqlAlias' => 'name',
***************
*** 41,47 ****
              ],
              'right' => [
                  'type' => 'literal',
-                 'value' => 'Robotina'
              ]
          ]
      ]
--- 40,46 ----
              ],
              'right' => [
                  'type' => 'literal',
+                 'value' => '\'Robotina\''
              ]
          ]
      ]
```

**Pull request closed without merging**
