### PR TITLE
[2.1.x] [NFR] Improving adapter session

### PR DESCRIPTION
**Pull request by KorsaR-ZN**
Update `Phalcon\Session\Adapter`, `Phalcon\Session\AdapterInterface` and also full coverage of the tests... And more improvements...

_Added public method:_
- `getOption()`
- `getCookieParams()`
- `setCookieParams()`
- `reset()`
- `commit()`
- `abort()`
- `clear()`
- `encode()`
- `decode()`

_Added protected method_
- `configure()`

_Added options:_
- name (session name) 
- cookie_lifetime
- cookie_path
- cookie_domain
- cookie_secure
- cookie_httponly

_`Phalcon\Session\Adapter\Files` added options:_
- savePath

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by sergeyklay** [comment]
@KorsaR-ZN Could you please rebase?

**Comment by sergeyklay** [comment]
I'm closing this PR due to the lack of any reaction. I'll open it again if the need arises

**Comment by Caffe1neAdd1ct** [comment]
Exposing the `encode` and `decode` would really help me in fixing https://github.com/phalcon/incubator/issues/682

Session values need to be merged in the DB adapter rather than just overriding the data column.

**Comment by sergeysviridenko** [comment]
This PR is very old. Maybe it can be closed.

**Comment by sergeyklay** [comment]
Actually this mostly New Feature Request than Pull Request. I prefer to keep it open like todo for 4.0.x branch.

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/13673

@KorsaR-ZN Thank you for this work. Sadly I could not merge your changes and also moved to a slightly different direction. Thank you again.

**Pull request closed without merging**
