### PR TITLE
[2.0.0][BUG] Fixed #3327

### LINKED ISSUE #3327: [2.0.0][BUG] Multiple logger incompatibility with 1.3
2.0 Multiple Handlers has different parameters (count/order) than 1.3

1.3
https://github.com/phalcon/phalcon-devtools/blob/master/ide/1.3.4/Phalcon/Logger/Multiple.php
public function log(**$type**, **$message**, $context=null)
public function emergency($message, $context=null)
public function emergence($message, $context=null)
public function debug($message, $context=null)
public function error($message, $context=null)
public function info($message, $context=null)
public function notice($message, $context=null)
public function warning($message, $context=null)
public function alert($message, $context=null)

2.0
https://github.com/phalcon/phalcon-devtools/blob/master/ide/2.0.0/Phalcon/Logger/Multiple.php
public function log(**$message**, **$type=null**)
public function emergency($message)
public function debug($message)
public function error($message)
public function info($message)
public function notice($message)
public function warning($message)
public function alert($message)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8445618-2-0-0-multiple-logger-incompatibility-with-1-3?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tmihalik**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please rebase against 2.0.0?

**Comment by tmihalik** [comment]
It's rebased

**Comment by tmihalik** [comment]
It's rebased

**Comment by tmihalik** [comment]
@andresgutierrez 
It's rebased

**Comment by sergeyklay** [comment]
@phalcon If you close the PR - explain why please

**Pull request closed without merging**
