### PR TITLE
[NFR] RoleAware and ResourceAware Interface

### PR DESCRIPTION
**Pull request by Jurigag**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Thanks

**Comment by Green-Cat** [comment]
:+1: 
The docs should probably be updated to add this.

**Comment by Jurigag** [comment]
https://github.com/phalcon/docs you mean add pr here ? Well i will do it if i have time.

**Comment by sergeyklay** [comment]
Yes, docs repo

**Comment by Jurigag** [comment]
Well there is no branch 2.1.x, i guess fork master and do pr for it ?

**Comment by sergeyklay** [comment]
Please use https://github.com/phalcon/docs repo for all question related to the docs.

**Pull request merged**
