### PR TITLE
T13886 collection

### PR DESCRIPTION
**Pull request by niden**
Hello!

* Type: new feature
* Link to issue: #13886 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Added `Phalcon\Collection`, offering a collection object for various parts of the framework such as handling arrays, superglobals etc.

Thanks

### CODE REVIEW

**Comment by niden** [comment]
cc @sergeyklay

**Review by sergeyklay — DISMISSED** [review]

**Comment by sergeyklay** [comment]
@niden Can we reuse this in the Phalcon\Registry ?

**Comment by niden** [comment]
@sergeyklay I need to check the Registry but yeah I believe so

**Comment by david-duncan** [comment]
It looks to me like a similar but better implementation of Registry

**Pull request merged**
