### PR TITLE
filter sanitize before compiling volt

### PR DESCRIPTION
**Pull request by pedro151**

### CODE REVIEW

**Comment by CameronHall** [comment]
@niden did you want me to deal with this one?

**Comment by niden** [comment]
@CameronHall If you can yes please.

**Comment by CameronHall** [comment]
I won't have be able to get this done _soon_. If you remind me what it's supposed to do, I can take a look at it and chip away.

**Comment by sergeyklay** [comment]
If it is a fix for a real problem, let's apply it before beta release. But first I would like to see a script to reproduce the bug

**Comment by niden** [comment]
The way I deciphered this since there was no description or rationale behind this, was to introduce a way to manipulate HTML after it has been compiled. The particular PR introduces this functionality and the supplied filter class strips whitespaces, line feeds etc., thus reducing the output on screen.

I do not think that this should be part of Phalcon. Services such as Varnish or Cloudflare can offer this functionality without having to change your code.

@pedro151 Thank you so much for the contribution, however I will close this. If later on the community is interested in something like this we can reintroduce this.

**Pull request closed without merging**
