### PR TITLE
[2.0.x] Added method addErrorMessage() in Phalcon\Mvc\Model

### PR DESCRIPTION
**Pull request by KorsaR-ZN**

### CODE REVIEW

**Comment by sergeyklay** [comment]
`addErrorMessage(...)` is just alias for `this->appendMessage(new Message(...))` ?

**Comment by KorsaR-ZN** [comment]
@sergeyklay yes

**Comment by andresgutierrez** [comment]
What's the problem with appendMessage?

**Comment by KorsaR-ZN** [comment]
@andresgutierrez `appendMessage()` makes the code much dependent on the `Phalcon\Mvc\Model\Message`


**example:**
```
class ModelA extend ModelBase
{
  .... 
    function some() {
      this->appendMessage(new Message(...));
    }
  ....
}

class ModelB extend ModelBase
{
  .... 
    function some() {
      this->appendMessage(new Message(...));
    }
  ....
}

....

class Model...N extend ModelBase
{
  .... 
    function some() {
      this->appendMessage(new Message(...));
    }
  ....
}
```

For extend the class `Message`, will require a lot of refactoring.
With this PR, can simply override the function `addErrorMessage()` in `ModelBase`

**Pull request closed without merging**
