### PR TITLE
Uniqueness validator with NULL values

### PR DESCRIPTION
**Pull request by basilfx**
This PR adds support for validating uniqueness of NULL values, including two tests.

Example usecase: model instances that are unique as long as they are not deleted using soft-delete behavior.

For the test cases, I added an extra field to the `robots` table, as the other fields were all `NOT NULL`. Fixed other test accordingly.

### CODE REVIEW

**Comment by Jurigag** [comment]
Update changelog and squash commits if you can.

**Comment by basilfx** [comment]
Squashed into one commit and updated changelog.

**Comment by nsossonko** [comment]
This is great, thanks!

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
