### PR TITLE
[2.0.x] setLogLevel method to Multiple Logger

### PR DESCRIPTION
**Pull request by tmihalik**

### CODE REVIEW

**Comment by niden** [comment]
Can we get some tests with this please?

**Comment by andresgutierrez** [comment]
@tmihalik ping

**Comment by carvajaldiazeduar** [comment]
@tmihalik ping

**Comment by sergeyklay** [comment]
@tmihalik ping

**Comment by bmoore** [comment]
This went stale, so I created https://github.com/phalcon/cphalcon/issues/11418 which has the unit-tests.

**Pull request closed without merging**
