### PR TITLE
[2.1.x] Fixed endless loop in Phalcon\Mvc\Model\Resultset::update()

### PR DESCRIPTION
**Pull request by BesedinSasha**

### CODE REVIEW

**Comment by Jurigag** [comment]
@sergeyklay im not sure if there is any test right now, but some would be need to check if it's working with this change.

**Comment by sergeyklay** [comment]
@Besedin86 Could you please explain a bit more - what do you fix here

**Comment by Besedin86** [comment]
The code below will update first record in endless loop. There was no next() method call when update records. 

```php 
$robots = Robot::find();
$robots->update(['name' => 'New name']);
```

**Comment by Jurigag** [comment]
Oh you're right. That's why we need tests for such a things. Also well, udpating resultset like this it's not the best idea to be honest.

**Comment by Besedin86** [comment]
It's just a hotfix. I think for other task we need more refactor and tests. Anyway, I use foreach to fix this locally.

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
