### PR TITLE
fixed issue 14324

### PR DESCRIPTION
**Pull request by ZhangRuiMingZRM**
Hello!

* Type: bug fix 
* Link to issue: https://github.com/phalcon/cphalcon/issues/14324

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Thanks

### CODE REVIEW

**Comment by ZhangRuiMingZRM** [comment]
I want some help for testing this PR

**Comment by sergeyklay** [comment]
@Zaszczyk Can you just test the case described in the https://github.com/phalcon/cphalcon/issues/14324

**Comment by Zaszczyk** [comment]
@sergeyklay are You sure I am related to this issue? :)

**Comment by ruudboon** [comment]
If you could test that you get back the correct object (and not an exception) when using your example it should be fine. You could extend it with testing that (null === this->serializerFactory && null === this->serializer) are throwing an exception.

```
use Phalcon\Cache\Adapter\Stream;
use Phalcon\Storage\Serializer\Json;

$jsonSerializer = new Json();

$options = [
    'defaultSerializer' => 'Json',
    'lifetime'          => 7200,
    'cacheDir'          => '/data/storage/cache',
];

$adapter = new Stream(null, $options);
```

**Review by ruudboon — APPROVED** [review]

**Comment by ruudboon** [comment]
@ZhangRuiMingZRM Thank you!

**Pull request merged**
