### PR TITLE
#15456 - Unify builds of PHP 7 and 8 versions

### LINKED ISSUE #15456: [NFR]: Merge PECL `build/php7` and `build/php8` directories into one
Instead of having x2 separate directories, try to merge into single and generalize version check inside code.

Based on PR #15428

### PR DESCRIPTION
**Pull request by Jeckerson**
Hello!

* Type: new feature | code quality

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Thanks

### CODE REVIEW

**Comment by Jeckerson** [comment]
@remicollet Could you please take a look?

**Comment by remicollet** [comment]
> @remicollet Could you please take a look?

```
$ phpize
make: *** Aucune règle pour fabriquer la cible « clean ». Arrêt.
Cannot find config.m4. 
```

**Comment by Jeckerson** [comment]
@remicollet So `config.*` files must be in the **root** of pecl archive and not inside `build/phalcon/safe` directory?

image

**Comment by remicollet** [comment]
> @remicollet So config.* files must be in the root of pecl archive and not inside build/phalcon/safe directory?

Yes

My test
```
pecl package
mv phalcon-5.0.0.tgz /tmp
cd /tmp
tar xvf phalcon-5.0.0.tgz
cd phalcon-5.0.0
phpize
...

```

**Comment by AlexNDRmac** [comment]
@Jeckerson for multi builds usually use next logic: build/{os}/{build type}/{arch}...
So, all build artefacts must be in destination folder. Main purpose of this approach - is avoiding to rebuild artifacts by build with other (os/build type/arch..) configuration.

**Comment by remicollet** [comment]
BTW... pecl seems able to detect proper location...

```
# pecl install --force ./phalcon-5.0.0.tgz  
5 source files, building
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
building in /var/tmp/pear-build-rootggwrDP/phalcon-5.0.0
running: /var/tmp/phalcon/build/phalcon/safe/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
...

```

**Review by AlexNDRmac — APPROVED** [review]

**Pull request merged**
