### PR TITLE
Add constant \Phalcon\Mvc\View::CACHE_MODE_*

### PR DESCRIPTION
**Pull request by dreamsxin**
As long as the cache action view, See #2377

``` php
$this->view->cache(array("key" => "mykey", "lifetime" => 2, "level" => 1, "mode" => \Phalcon\Mvc\View::CACHE_MODE_INVERSE));
```

### CODE REVIEW

**Comment by serebro** [comment]
Hi. What about this feature in 2.x?

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view.zep#L92

**Comment by serebro** [comment]
@sergeyklay Yes, but it is unused constant, not uses in the code and not works. https://github.com/phalcon/cphalcon/search?q=CACHE_MODE_INVERSE

**Comment by ovr** [comment]
> Hi. What about this feature in 2.x?
:+1:

**Pull request closed without merging**
