### PR TITLE
[NF] Micro: Response handler PR #12452

### PR DESCRIPTION
**Pull request by CameronHall**
Hello!

* Type: cherry-picked existing PR
* Link to PR: [#12425](https://github.com/phalcon/cphalcon/pull/12425)

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I wrote some tests for this PR.

Small description of change: Added response handler to `Phalcon\Mvc\Micro`, `Phalcon\Mvc\Micro::setResponseHandler`, to allow use of a custom response handler. [#12452](https://github.com/phalcon/cphalcon/pull/12452)

Thanks

### CODE REVIEW

**Comment by niden** [comment]
@CameronHall Can you please rebase? Also note that the test structure has changed. Message me on Discord if you have questions

**Comment by CameronHall** [comment]
@niden have rebased.

**Comment by CameronHall** [comment]
All done @niden

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you!

**Pull request merged**
