### PR TITLE
Add setContentLength() method to Phalcon\Http\Response

### PR DESCRIPTION
**Pull request by zamronypj**

### CODE REVIEW

**Comment by Green-Cat** [comment]
Please do not include zep.c and zep.h files in your commit. Only the edited sources.

**Comment by zamronypj** [comment]
those files are not in .gitignore. Should all zep.c and zep.h be include in .gitignore?

**Comment by Jurigag** [comment]
Just remove them and squash commits.

**Comment by sergeyklay** [comment]
Close this in favor of https://github.com/phalcon/cphalcon/pull/11986

**Pull request closed without merging**
