### PR TITLE
[2.0.0] Gets Criteria instance from DI container

### PR DESCRIPTION
**Pull request by KorsaR-ZN**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
I think also this can be moved there: 

```php
https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/mvc/model/manager.zep#L1820
https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/mvc/model/manager.zep#L1847
```

**Comment by KorsaR-ZN** [comment]
@andresgutierrez 
I think so too.
I'll now do it

**Comment by KorsaR-ZN** [comment]
@andresgutierrez 
Who broke the CI build?
My build is passed
https://travis-ci.org/KorsaR-ZN/phalcon-core/builds/57862567

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
