### PR TITLE
[NFR] Http\Request added getPayload() method

### PR DESCRIPTION
**Pull request by ovr**
refs http://stackoverflow.com/questions/9597052/how-to-retrieve-request-payload

### CODE REVIEW

**Comment by sergeyklay** [comment]
@ovr Can you add `@return array` please, for generating stubs and ide autocompleting

**Comment by ovr** [comment]
@sergeyklay 
Return generates automaticaly by `zephir stubs`

https://github.com/ovr/phalcon2-stubs/blob/master/Phalcon/http/Request.zep.php#L422

**Comment by sergeyklay** [comment]
@ovr Thank you for explanation

**Comment by ovr** [comment]
@sergeyklay Not a problem :+1:

**Comment by phalcon** [comment]
https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/http/request.zep#L424

**Comment by ovr** [comment]
Thanks for notice

**Pull request closed without merging**
