### PR TITLE
Fix bug #12715

### PR DESCRIPTION
**Pull request by dreamsxin**
See #12715

### CODE REVIEW

**Comment by Jurigag** [comment]
Can you update changelog and provide small test?

**Comment by dreamsxin** [comment]
@Jurigag Ok, On tomorrow

**Comment by dreamsxin** [comment]
@Jurigag Help, check whether qualified.

**Review by Jurigag — CHANGES_REQUESTED** [review]
Use tests folder please also in changelog move it at the end of 3.1.x

**Comment by dreamsxin** [comment]
@Jurigag How use tests folder?

**Comment by Jurigag** [comment]
Just checks other tests there.

**Comment by dreamsxin** [comment]
@Jurigag I see the folder no relevant test.

**Comment by Jurigag** [comment]
What you mean?

**Comment by dreamsxin** [comment]
@Jurigag I don't know how add test. :(

**Comment by sergeyklay** [comment]
No problem. I'll change later. Thank you

**Pull request merged**
