### PR TITLE
2.1.x. Pass validator error code to validation message constructor.

### PR DESCRIPTION
**Pull request by temuri416**

### CODE REVIEW

**Comment by temuri416** [comment]
@phalcon 

How long is the wait time for review/approval?

Thanks!

**Comment by KorsaR-ZN** [comment]
@temuri416 Please rebase

**Comment by temuri416** [comment]
@KorsaR-ZN 

Can you please help me with that?

After issuing ```git rebase -i HEAD~17``` I have the following screen:

image

How do I proceed?

Thanks a lot!

**Comment by temuri416** [comment]
@KorsaR-ZN 

Done!

**Comment by sergeyklay** [comment]
+1 skill :)

**Comment by temuri416** [comment]
Heheh yeah, thanks! :)

**Comment by temuri416** [comment]
@andresgutierrez 

Something is wrong - does not seem to work...

Code:

```php
new Phalcon\Validation\Message('a','b',1,2);
```

Result:
```php
PHP Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Wrong number of parameters' in /root/i.php:3
Stack trace:
#0 /root/msg.php(3): Phalcon\Validation\Message->__construct('a', 'b', 1, 2)
#1 {main}
  thrown in /msg.php on line 3

Fatal error: Uncaught exception 'BadMethodCallException' with message 'Wrong number of parameters' in /root/i.php:3
Stack trace:
#0 /root/msg.php(3): Phalcon\Validation\Message->__construct('a', 'b', 1, 2)
#1 {main}
  thrown in /msg.php on line 3
```

I tried to rebuild with ```./install.sh```, ```zephir build``` and tried to regenerate with ```php build/gen-build.php```.

Is there some other trick I do not know to rebuild the extension?

Thanks!

**Pull request merged**
