### PR TITLE
Queue beanstalk patch 2

### PR DESCRIPTION
**Pull request by korolev-d-l**
rebase https://github.com/phalcon/cphalcon/pull/11436

### CODE REVIEW

**Comment by Chameleon-m** [comment]
@sergeyklay rebase ready.

**Comment by Chameleon-m** [comment]
@andresgutierrez

**Comment by sergeyklay** [comment]
We have to code freeze the 2.1.x for purposes to testing and preparing for release RC.1. We'll detail consider your PR after release

**Comment by Chameleon-m** [comment]
Reminds me)
after the merger will have a new request drank in incubator.
https://github.com/Chameleon-m/incubator/commits/Queue_beanstalk_patch_for_patch

**Comment by sergeyklay** [comment]
Thanks

**Comment by sergeyklay** [comment]
@Chameleon-m Could you please update docs https://github.com/phalcon/docs/blob/master/en/reference/queue.rst

**Pull request merged**
