### PR TITLE
Save custom validator message option in object

### PR DESCRIPTION
**Pull request by ivan-zolotavin**
* Type: bug fix | new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/15053

### CODE REVIEW

**Review by Jeckerson — APPROVED** [review]

**Comment by ruudboon** [comment]
@ivan-zolotavin Thnx for your contribution! Can you mentioned the fix in our CHANGELOG-4.1.md ?

**Comment by ivan-zolotavin** [comment]
Done.

**Comment by Jeckerson** [comment]
@ivan-zolotavin Please resolve conflicts.

**Comment by ivan-zolotavin** [comment]
Done.

**Review by ruudboon — APPROVED** [review]

**Comment by ruudboon** [comment]
@ivan-zolotavin Thank you! Will merge it when tests finish.

**Pull request merged**
