### PR TITLE
Fix #10726, remove unneeded code

### LINKED ISSUE #10726: assets/collection.zep Filter always true
line 142 And 170
if !filter {
let filter = true;
}

https://github.com/phalcon/cphalcon/blob/master/phalcon/assets/collection.zep

### PR DESCRIPTION
**Pull request by ovr**
refs https://github.com/phalcon/cphalcon/pull/10727#issuecomment-125239212

### CODE REVIEW

**Comment by andresgutierrez** [comment]
This is breaking a test:

```diff
1) AssetsTest::testIssue1198
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'a {
-    text-decoration: none;
-}
-
-b {
-    font-weight: bold;
-}
-'
+'A{TEXT-DECORATION:NONE;}B{FONT-WEIGHT:BOLD;}'
/home/travis/build/phalcon/cphalcon/unit-tests/AssetsTest.php:52
```

**Comment by ovr** [comment]
@andresgutierrez 
Maybe change default value to true...
What do you think about it? or fix test?

**Comment by SidRoberts** [comment]
FWIW, the default was [true in 1.3.4](https://github.com/phalcon/cphalcon/blob/1.3.4/ext/assets/collection.c#L286).

**Comment by andresgutierrez** [comment]
@ovr Maybe use 'true' as default as @SidRoberts noticed

**Comment by ovr** [comment]
@andresgutierrez Already fixed!

**Comment by ovr** [comment]
@SidRoberts Thanks for notice :beer:

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
