### PR TITLE
[2.0.x] Mvc/Model: Setter fallback

### PR DESCRIPTION
**Pull request by brainformatik**
Add setter fallback in "__set" magic.
This is useful if you use protected (private) properties and assign a value directly to a property.
If this property has setter/getter functions they will be called preferably.

### CODE REVIEW

**Comment by sergeyklay** [comment]
@brainformatik  Can you please provide a small test?

In any case :+1:

**Comment by Green-Cat** [comment]
:+1:

**Comment by brainformatik** [comment]
Added a few tests

**Comment by sergeyklay** [comment]
Fine! :+1:

**Comment by Surt** [comment]
I would like to see this one in collection too. By the way I would like to see some "entity" behaviours interfaces in both, collections and models. As well a ResultSet kind of data for both, Models resultsets and ODM multiple results.

**Comment by noobiwan** [comment]
What's the status on this?

**Comment by noobiwan** [comment]
#10391

**Comment by noobiwan** [comment]
Similar issue: #3033

**Comment by sergeyklay** [comment]
@brainformatik Can you please rebase onto `2.0.x` branch and amend CHANGELOG.md?

**Comment by bmoore** [comment]
This will conflict with #11320 if we try to bring #11320 to 2.0.x

**Comment by bmoore** [comment]
https://github.com/phalcon/cphalcon/pull/11417 Is the ported code from #11320 for 2.0.x

**Pull request closed without merging**
