### PR TITLE
Do not use lifetime option as Redis connection timeout

### PR DESCRIPTION
**Pull request by misantron**
Hello!

* Type: bug fix
* Link to issue: -

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Redis cache adapter: using new `timeout` option with Redis connection instead of `lifetime`

Thanks

### CODE REVIEW

**Comment by rudiservo** [comment]
@misantron You probably want to put this to phalcon 5 branch not 4.

**Comment by misantron** [comment]
@rudiservo no, there is no issue at version 5

**Comment by niden** [comment]
I am going to try and rebase this to 4.2.x

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @misantron

**Pull request merged**
