### PR TITLE
Renamed Paginator\Adapter::getPaginate() to paginate()

### PR DESCRIPTION
**Pull request by SidRoberts**
See 4f5381b285fccffdc45fc4263a93db69bca87552

Hello!

* Type: bug fix | documentation
* See also: https://github.com/phalcon/docs/pull/2291

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [-] I wrote some tests for this PR
- [-] I updated the CHANGELOG

Small description of change:

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@SidRoberts Should we update change log as well ?

**Comment by SidRoberts** [comment]
@sergeyklay Update alpha.5 or alpha.1?

**Comment by sergeyklay** [comment]
@SidRoberts alpha.5 please. Also feel free to mention version this change was actually made (even by mistake or wrongly).

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @SidRoberts

**Pull request merged**
