### PR TITLE
Sync ext/phalcon/annotations/base.c with parser.c and add generate file

### PR DESCRIPTION
**Pull request by olivier-monaco**
Issue  #3271

### CODE REVIEW

**Comment by phalcon** [comment]
We absolutely need this file

**Comment by olivier-monaco** [comment]
Phalcon 2 includes 3 base.c files:
<pre>
./ext/phalcon/annotations/base.c
./ext/phalcon/mvc/view/engine/volt/base.c
./ext/phalcon/mvc/model/query/base.c
</pre>

Only 2 of then seems to be used for parsers. Ouput from a grep:
<pre>
ext/phalcon/mvc/view/engine/volt/generate:re2c -o scanner.c scanner.re && ./lemon -s parser.lemon && cat base.c >> parser.c
ext/phalcon/mvc/model/query/generate:re2c -o scanner.c scanner.re && ./lemon parser.lemon && cat base.c >> parser.c
</pre>

The file ext/phalcon/annotations/base.c is in the "exclusions" list of "scripts/gen-build.php".

Phalcon 2 compiles anyway.

Are you sure it's needed?

**Comment by olivier-monaco** [comment]
If it works like other base.c files, there's a generate file missing.

We can also see old code from base.c which is not in parser.c:
- use of PHALCON_INIT_VAR
- use of PHALCON_THROW_EXCEPTION_STR

**Comment by olivier-monaco** [comment]
But now we may have the same problem than #3195...

**Comment by olivier-monaco** [comment]
We have... Use case:
<pre>
<?php

/**
 * @Invalid(")
 */
class MyTest {
}

$reader = new \Phalcon\Annotations\Adapter\Memory();

$reflector = $reader->get('MyTest');
$annotations = $reflector->getClassAnnotations();
foreach ($annotations as $annotation) {
    echo $annotation->getName(), PHP_EOL;
    echo $annotation->numberArguments(), PHP_EOL;
    print_r($annotation->getArguments());
}
</pre>

**Comment by olivier-monaco** [comment]
Rewriting this pull request from scratch.

**Pull request closed without merging**
