### PR TITLE
Pointing where doc issues should be sent to

### PR DESCRIPTION
**Pull request by igorsantos07**
This was surfaced by #12120

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Thanks, we don't add changes directly to master, could you please submit this to 3.0.x?

https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md#pull-request-checklist

**Comment by igorsantos07** [comment]
Actually @andresgutierrez, I think this is a special case. Template files are only considered from the default branch - it seems to be `master` in this case, right?

From the [docs](https://help.github.com/articles/creating-an-issue-template-for-your-repository/):
> Tip: You must create your template in your repository's default branch. Templates created in other branches are not available for collaborators to use.

**Comment by igorsantos07** [comment]
Bonus: what about a pull request template? something like "hey way, are you PRing to the correct branch? we don't use master for this type of work", maybe with about the same text from the PR checklist you linked.

**Comment by andresgutierrez** [comment]
Changes will be available when we merge 3.0.x into master

**Comment by igorsantos07** [comment]
Well, so until 3.0.x gets a release there will be no update to the issue template? The issue template has _nothing_ related to the actual project code or state or release, it's just a repository configuration.
It doesn't make much sense to have this type of fix waiting weeks on 3.0.x...

**Comment by andresgutierrez** [comment]
> Well, so until 3.0.x gets a release there will be no update to the issue template? 

Exactly this

**Comment by igorsantos07** [comment]
Cool. What's would be of work trying to progress without a lot of bureaucracy in front of it, right?
What would be of logic if there was no one thinking about stuff before repeating what has been said by others, right?
Obviously there's a whole lot of sense of leaving a small fix sitting for weeks, together with completely unrelated stuff. Oh well.

**Comment by igorsantos07** [comment]
Funny to actually notice the very issue I'm trying to point out here, @andresgutierrez, is exactly what just happened. There **is** a PR template stating stuff should not be sent to master. But thanks to this crazy policy of tying repository settings to Phalcon versions, I didn't see that.

**Pull request closed without merging**
