### PR TITLE
Refactored SoftDelete model behaviour.

### PR DESCRIPTION
**Pull request by SidRoberts**
Hello!

* Type: code quality
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [-] I wrote some tests for this PR
- [-] I updated the CHANGELOG

Refactored SoftDelete model behaviour.

### CODE REVIEW

**Comment by wajdijurry** [comment]
Good job 👍 
I hope that Mvc\Collection\Behaviors\SoftDelete is refactored too, since the method "beforeDelete" is not being executed on delete.

**Comment by SidRoberts** [comment]
@wajdijurry Good point, I completely forgot about that class. Fixed in 38efbbf64.

**Comment by niden** [comment]
@SidRoberts can you add an entry to the CHANGELOG please?

**Review by niden — DISMISSED** [review]

**Review by sergeyklay — DISMISSED** [review]

**Review by sergeyklay — DISMISSED** [review]

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @SidRoberts

**Pull request merged**
