### PR TITLE
Fixes #11554 - Transaction Manager transaction accounting

### LINKED ISSUE #11554: Issue with transaction manager, doesn't manage transactions correctly
There's an issue with the transaction manager that makes it work very poorly. I will upload a pr that fixes it, but, as of now, I don't have time to run tests really on it. I have extended the manager and overriden this function so that it works properly for me, so that much testing I have done.

### PR DESCRIPTION
**Pull request by nsossonko**
This should fix the issue.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please provide a small test?

**Comment by nsossonko** [comment]
Right now I can't unfortunately, maybe later. I'm just swamped now sorry.

**Comment by nsossonko** [comment]
This fixes #11554 and probably #2632 as well

**Comment by sergeyklay** [comment]
@nsossonko

**Comment by nsossonko** [comment]
@sergeyklay unfortunately I cannot find the time now to create the tests. If I do I will surely update the patch. Sorry.

**Comment by nsossonko** [comment]
@sergeyklay tests now included

**Comment by sergeyklay** [comment]
Well, could you please update CHANGELOG.md

**Comment by nsossonko** [comment]
@sergeyklay that work?

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
