### PR TITLE
Fixed notice in query builder paginator when totalQuery result is empty

### PR DESCRIPTION
**Pull request by ashpumpkin**
issue #11049

### CODE REVIEW

**Comment by andresgutierrez** [comment]
`intval` is not returning zero?

**Comment by sergeyklay** [comment]
```
php > # it is permissible scenario for 'row = result->getFirst()'
php > $row = null; 
php > 
php > var_dump(intval($row->rowcount));
PHP Notice:  Trying to get property of non-object in php shell code on line 1
PHP Stack trace:
PHP   1. {main}() php shell code:0

int(0)  # <--  Yeah :)
```

**Comment by ashpumpkin** [comment]
Please read the issue, in some cases row can be false, and row->rowcount produces notice

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
