### PR TITLE
Notice "Cannot use a scalar value as an array"

### PR DESCRIPTION
**Pull request by olivier-monaco**
#10648

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please provide the script or unit-test you used to test this?

**Comment by olivier-monaco** [comment]
For simple.zep, I don't have any test. It's by code review. It revert the following commit: https://github.com/olivier-monaco/cphalcon/commit/4f5e28abfbe586f43d5ee6c41d3901b91a85d02a#diff-0a0014cdd026fc43956d243d1ecebbcdL202

The current code is doing something like:
<pre>
let renamed[this->_columnMap[key][0][0]] = value
</pre>

But a I think column map entry can't be array of array.

Same for model.zep.

**Comment by andresgutierrez** [comment]
They can be arrays, it you're using orm.castOnHydrate = true

**Comment by olivier-monaco** [comment]
Interesting... I'm working on a use case...

**Comment by olivier-monaco** [comment]
Using use case from https://github.com/phalcon/cphalcon/issues/10648#issuecomment-121749438.

I added a var_dump in simple.zep just before using renamedKey:
```php
						/**
						 * Check if the key is part of the column map
						 */
						if !fetch renamedKey, columnMap[key] {
							throw new Exception("Column '" . key . "' is not part of the column map");
						}

var_dump("SIMPLE", renamedKey);
                        if typeof renamedKey == "array" {
		                    if !fetch renamedKey, renamedKey[0] {
                	            throw new Exception("Column '" . key . "' is not part of the column map");
                        	}

							let renamed[renamedKey[0]] = value;
		                } else {
							let renamed[renamedKey] = value;
						}
```

The result:
```
string(6) "SIMPLE"
array(2) {
  [0]=>
  string(2) "id"
  [1]=>
  int(0)
}
PHP Notice:  Cannot use a scalar value as an array in phalcon/mvc/model/resultset/simple.zep on line 209 in .../i10673a.php on line 24
```

It's not an array of array.

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
