### PR TITLE
Added some tests for Gd image adapter

### PR DESCRIPTION
**Pull request by emiliodeg**
Hello!

* Type: code quality
* Link to issue: #13655 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:
I made some tests for GD image adapter
Thanks

### CODE REVIEW

**Review by niden — DISMISSED** [review]

**Comment by niden** [comment]
@emiliodeg Can you check Travis please?

**Comment by emiliodeg** [comment]
@niden there is a little problem. If I change the MD5's to assert in travis I get error when I tests with codecept in nanobox.
What can I do?

**Comment by niden** [comment]
This is still failing @emiliodeg

**Comment by emiliodeg** [comment]
Well sadly I just remove the tests which made conflicts. I didn't have time to improve it.

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @emiliodeg

**Pull request merged**
