### PR TITLE
Fix "The argument is not initialized or iterable()" in Headers::send()

### PR DESCRIPTION
**Pull request by endeveit**

### CODE REVIEW

**Comment by SidRoberts** [comment]
Because this changes the behaviour of `send()` (if `typeof this->_headers != "array"`, `send()` will never return true, regardless of `headers_sent()`), I'd like to propose changing this instead:

NOW:
```zephir
protected _headers;
```

TO:
```zephir
protected _headers = [];
```

**Comment by endeveit** [comment]
@SidRoberts done

**Comment by andresgutierrez** [comment]
Could you please remove this commit from your PR? https://github.com/endeveit/cphalcon/commit/fea27421bb77f3204a0908bf09f621217bf3d1db

**Comment by endeveit** [comment]
@andresgutierrez done

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
