### PR TITLE
Fixed  issue #11033

### PR DESCRIPTION
**Pull request by rlaffers**
Fixes Model::findFirst erroneous query in Oracle dialect reported  at phalcon/cphalcon#11033. Before this fix the generated query was limited by 'WHERE ROWNUM <=0'. However, in Oracle ROWNUM starts at 1, so the query effectively always returned zero results.

### CODE REVIEW

**Comment by Green-Cat** [comment]
Please only commit changes to the .zep files, not the recompiled zep.c files.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md

**Comment by rlaffers** [comment]
OK, thanks for the pointer. I'm going to put this pull request on hold. It seems to introduce a problem with the limit parameter in find() https://github.com/phalcon/cphalcon/issues/1652#issue-23911602

**Comment by jeiel** [comment]
@rlaffers  You can confirm if your solution is now available for download in the repository

**Comment by sergeyklay** [comment]
@rlaffers In order to this PR was accepted, do the following:
1. Fix indentation
2. Provide a small test
3. Remove all unneeded and commented code
4. Update `CHANGELOG.md`
5. Squash it into a single commit to keep the history clean

**Comment by sergeyklay** [comment]
@rlaffers

**Comment by sergeyklay** [comment]
Phalcon does not support Oracle. Refer to #12008

**Pull request closed without merging**
