### PR TITLE
[2.0.0] [BUG] fixed - variable already defined

### PR DESCRIPTION
**Pull request by KorsaR-ZN**

### CODE REVIEW

**Comment by KorsaR-ZN** [comment]
@phalcon 
Please merge,
This fixes a bug build stable branch 2.0.0

**Comment by arius86** [comment]
:+1:  Also need this :)

**Comment by Green-Cat** [comment]
:+1:

**Comment by ovr** [comment]
:+1:

**Comment by KorsaR-ZN** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
