### PR TITLE
Fix [Source on GitHub] links

### PR DESCRIPTION
**Pull request by Deathamns**
phalcon/docs#2643

Added some changes to make it work on Win too.

### CODE REVIEW

**Review by ruudboon — APPROVED** [review]

**Comment by ruudboon** [comment]
Thnx. Looks good to me. Unfortunately not able to test it (running on linux and MacOS)

**Comment by niden** [comment]
Sadly I don't have Windows either. Wondering if anyone can help test this

**Comment by Deathamns** [comment]
The GitHub links were the main issue here, Win fixes are just an extra, but they were necessary for me to test, as I used Win. Meaning, it shouldn't hold you back, as you won't lose anything, since it didn't work before.

**Comment by ruudboon** [comment]
@Deathamns I can test it this afternoon. So I leave it open for a few more hours.

**Pull request merged**
