### PR TITLE
Added Phalcon\Assets\Manager::exists()

### PR DESCRIPTION
**Pull request by Jurigag**
Rebased into 2.1.x @sergeyklay

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Can you please rebase?

**Comment by Jurigag** [comment]
@andresgutierrez done

**Comment by andresgutierrez** [comment]
Latest changes were merged, can you please rebase?

**Comment by Jurigag** [comment]
Refresh :)

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
