### PR TITLE
Normalizes transaction passing #13235

### PR DESCRIPTION
**Pull request by chilimatic**
- adds transaction get and set to builder
 - adds transaction get and set to criteria
 - moves limit to params (a more idiomatic approach)
 - adds behaviour to set the transaction in the builder::__constructor
 - adds the transaction to the query in builder::getQuery
 - renames and moves _getPreparedQuery below _groupResult because of functional cohesion

Hello!

* Type: new feature
* Link to issue: #13235

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

please look in the ticket for a detailed description

Thanks

### CODE REVIEW

**Comment by chilimatic** [comment]
@sergeyklay when and/or if you approve I will make another rebase to get rid of the Changelog merge.

**Comment by chilimatic** [comment]
@sergeyklay do I need to change something ? or does this look okay to you? :)

**Comment by sergeyklay** [comment]
@chilimatic Could you please send this PR to the 4.0.x branch?

**Comment by chilimatic** [comment]
@sergeyklay kk :)

**Comment by chilimatic** [comment]
@sergeyklay Sorry I am a bit confused, 4.0.0 according to my PHPStorm versionlog does not contain the other commit needed for this to work. Shouldn't 3.3.x first be merged ? or should I cherry pick the PR from before as well ?

**Pull request closed without merging**
