### PR TITLE
Added @Annotation Model and Router classes for supporting IDE Stubs with PHP Annotation Plugin for PHPStorm

### PR DESCRIPTION
**Pull request by Jurigag**

### CODE REVIEW

**Comment by Jurigag** [comment]
@sergeyklay @andresgutierrez 

Im not sure if this if was mistake, just saw earlier files, before PHP 7 support, and there wasnt such a instruction, so i guess it was mistake and it was supposed to be >= 70000 instead of < 70000.

**Comment by mattvb91** [comment]
:+1: nice work spotting that.

**Comment by Jurigag** [comment]
Well i wrote how i found it in your PR.

**Comment by andresgutierrez** [comment]
Could you please submit the fix in a separate PR?

**Comment by sergeyklay** [comment]
@Jurigag Can you please explain a bit more what feature provides your PR?

**Comment by Jurigag** [comment]
After installing PHPStorm plugin: https://plugins.jetbrains.com/plugin/7320

You have autocomplete in php doc if you use `@SomeClass`.

**Comment by sergeyklay** [comment]
In this case this PR related to the [Devtools](https://github.com/phalcon/phalcon-devtools) repo

**Comment by Jurigag** [comment]
Yea but classes for ide stubs are genereated from zephir.

**Comment by Jurigag** [comment]
@sergeyklay so how it is related to devtools ?

**Comment by sergeyklay** [comment]
Frankly your PR introduces the dead classes (okay, just stubs). I can not imagine a real benefit except of the autocompletion

**Pull request closed without merging**
