### PR TITLE
[NFR] Added Phalcon\Mvc\View\Engine\Markdown

### PR DESCRIPTION
**Pull request by kjdev**
see: #9930

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Thanks, we currently have code freeze for 2.0.0, only PR with bug fixes will be accepted

**Comment by kjdev** [comment]
All right.
Please consider also after the 2.0.0 release.

**Comment by wetux** [comment]
This please add this feature at least after 2.0.0 released, because this is very useful to many people who use Markdown. There is also something called ParseDown.org which is even faster.

**Comment by andresgutierrez** [comment]
Branch 2.0.0 was renamed to 2.0.x, could you please submit this change to that branch?

**Pull request closed without merging**
