### PR TITLE
[NFR] Added Phalcon\Mvc\View\Engine\Markdown

### PR DESCRIPTION
**Pull request by kjdev**
Re-submit. (#9983)

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Keeping this open for discussion

**Comment by dedalozzo** [comment]
I'm using hoedown and it works. I use it to render just a part of a view (markdown articles and comments), but it can be useful to render static text or build a static site generator like Jekyll.

**Comment by sergeyklay** [comment]
:+1:

**Comment by sergeyklay** [comment]
I would like see this library in incubator. Thanks for contributing.

**Pull request closed without merging**
