### PR TITLE
Phalcon\Mvc\Model\Criteria::getOrder renamed to Phalcon\Mvc\Model\Criteria::getOrderBy

### PR DESCRIPTION
**Pull request by tmihalik**
`Phalcon\Mvc\Model\Criteria::getGroup` renamed to `Phalcon\Mvc\Model\Criteria::getGroupBy`

### CODE REVIEW

**Comment by sergeyklay** [comment]
@andresgutierrez Can you please resolve Travis issue?

**Comment by andresgutierrez** [comment]
@sergeyklay it must be fixed now

**Comment by sergeyklay** [comment]
@andresgutierrez 

> $ (./unit-tests/ci/install_zephir.sh)
> gcc: error: lemon.c: No such file or directory
> gcc: fatal error: no input files
> compilation terminated.
> re2c: error: cannot open scanner.re
> error: re2c is not installed
> The command "(./unit-tests/ci/install_zephir.sh)" failed and exited with 2 during

https://travis-ci.org/phalcon/cphalcon/jobs/95434319

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
