### PR TITLE
Run tests on php 7.0

### PR DESCRIPTION
**Pull request by Green-Cat**
With an allow failures for now.

### CODE REVIEW

**Comment by andresgutierrez** [comment]
This can't be merged yet

**Comment by Green-Cat** [comment]
@andresgutierrez Why not? There is an allow failures command, so the build failing on 7.0 won't report as a travis failure.

**Comment by mattvb91** [comment]
:+1:

**Comment by sergeyklay** [comment]
@Green-Cat could you please rebase?

**Comment by Green-Cat** [comment]
@sergeyklay I have rebased, but there are a few extensions which don't exist on 7.0 yet which make the tests fail. I'll look into it a little later today.

**Comment by Jurigag** [comment]
I think they exist but you have to compile yourself.

**Comment by sergeyklay** [comment]
Yes. Need to optimize this script https://github.com/phalcon/cphalcon/blob/2.1.x/tests/_ci/install_prereqs.sh

**Comment by Green-Cat** [comment]
@sergeyklay
So I did my research.

- igbinary has a working 7.0 repo, just needs to be compiled from source.
- memcache (not to be confused with memcache**d**) has no working 7.0 version.
- mongo no longer exists for 7.0. It is replaced by mongodb which has a different API. See XXX
- yaml. Need to use ```pecl install yaml-beta```, as only the beta version supports 7.0 (and only 7.0)

**Comment by Green-Cat** [comment]
@sergeyklay
So I did my research.

- igbinary has a working 7.0 repo, just needs to be compiled from source. (https://github.com/igbinary/igbinary7)
- memcache (not to be confused with memcache**d**) has no working 7.0 version.
- mongo no longer exists for 7.0. It is replaced by mongodb which has a different API. See #11156
- yaml. Need to use ```pecl install yaml-beta```, as only the beta version supports 7.0 (and only 7.0)

**Comment by sergeyklay** [comment]
Well, need mark test as skipped for extensions which is impossible to use

**Comment by sergeyklay** [comment]
> memcache (not to be confused with memcached) has no working 7.0 version.

This means that we will have to get rid of the appropriate Phalcon classes

**Comment by Jurigag** [comment]
Or throw exception when using php 7.

**Comment by Green-Cat** [comment]
I've handled most of the extensions (still need to take care of igbinary and mongo (this one will be a separate PR, many files to update across the framework)), however the tests still cause segfaults.

**Comment by Jurigag** [comment]
@sergeyklay are you working on it why it causing segfaults ? I can check it when have time on gdb and write here log from stacktrace if you need.

**Comment by sergeyklay** [comment]
It would be helpful

**Comment by Jurigag** [comment]
http://pastebin.com/UNXLwQxs

I dont know how its related to this test Phalcon\Test\Unit\Logger\Adapter\FileTest::testLoggerAdapterFileOpenReadThrowsException

Even if i put die() in beginning of this function it still causing core dump.

**Comment by Jurigag** [comment]
@sergeyklay @andresgutierrez 
Here stack from php with debug symbols(if you didnt get it yet yourself), hope it helps:

http://pastebin.com/kKC1NJSC

**Comment by Jurigag** [comment]
When i set USE_ZEND_ALLOC=0 to disable zend memory allocator then i got stack which actually have something with adapter logger http://pastebin.com/keUR6Wtv

**Comment by Jurigag** [comment]
Well i pretty much installed everything from zero. Using newest codeception i have only those logs, with USE_ZEND_ALLOC=1 seg fault happens in testLoggerAdapterFileCreationWrite with this:
http://pastebin.com/kKC1NJSC
with USE_ZEND_ALLOC=0 seg fault happens in testLoggerAdapterFileCreationDefault with thos: http://pastebin.com/uxb8iGk2

**Comment by sergeyklay** [comment]
@Green-Cat You can see how to install any extension here https://github.com/phalcon/dockerfiles/tree/master/php

**Comment by andresgutierrez** [comment]
Can you please rebase this?

**Comment by sergeyklay** [comment]
Already in 2.1.x branch

**Pull request closed without merging**
