### PR TITLE
PHP 8.0 Issue - Model relations: set options as array by default

### PR DESCRIPTION
**Pull request by VladKuch**
Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/cphalcon/issues/15971

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [x] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Thanks

### CODE REVIEW

**Comment by Jeckerson** [comment]
Changed the base branch from `master` to `5.0.x`.

**Review by niden — CHANGES_REQUESTED** [review]
You will also need to follow the path of the code in each of these methods. In particular the `Manager.zep` class `addBlongsTo` needs also the `options` to be changed as an array (same with the other functions)

I briefly checked the code and it does not seem to have a side effect although it would be great if we had more tests to be 100% sure.

**Comment by VladKuch** [comment]
@niden CHANGELOG5 updated

**Comment by niden** [comment]
> @niden CHANGELOG5 updated

Also have a look at my previous comment. The `Manager` methods need to be updated also.

**Comment by VladKuch** [comment]
> > @niden CHANGELOG5 updated
> 
> Also have a look at my previous comment. The `Manager` methods need to be updated also.

Sorry, I missed it. Done.

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
@VladKuch Looking great! Thank you

**Pull request merged**
