### PR TITLE
Fix #1933

### LINKED ISSUE #1933: Odd view behavior with layouts + pick
I noticed some odd behavior with calling `setLayout()` and `pick()`.

```
1. $view->setLayout('fancy');
2. $view->pick('someview');
```

1. Turns out if I call `setLayout()` then `pick()` then the `setLayout()` gets ignored. If there is a default layout, that gets picked which is worse since the framework ignores user intent (line 1).

2. The work around right now is to call `pick(['view', 'layout'])`. This behavior is undocumented and I gleaned it by reading the C source. Is this undocumented because it's unsupported and liable to change or is this okay to use?

3. It would be nice to be able to fix this bug and leave out the undocumented array syntax since the code legibility is better and it allows full control to the user to compose views throughout the application lifecycle (set a main, a layout and a view at different stages of the app lifecycle).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1896481-odd-view-behavior-with-layouts-pick?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ryomo**
Fix an odd behavior with `$view->setLayout()` and `$view->pick()`.
This may not be a bug :confused: :question:

### CODE REVIEW

**Comment by ryomo** [comment]
More information.

When I call both `setLayout('layoutName')` and `pick('path/to/view')`, `setLayout()` gets ignored, because `layoutName` is always overwritten by `pick()`.
I fixed this behavior.

But the behavior is intended, this pull request should not be merged.

**Comment by benfavre** [comment]
This is anoying.
+1

**Comment by sergeyklay** [comment]
+1

**Comment by sergeyklay** [comment]
@ryomo

**Comment by ryomo** [comment]
@sergeyklay 
I rebased this.

**Comment by sergeyklay** [comment]
Can you please send this PR to the `2.1.x` branch?

**Pull request closed without merging**
