### PR TITLE
Support subqueries in PHQL

### PR DESCRIPTION
**Pull request by dreamsxin**

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by sergeyklay** [comment]
@dreamsxin  related to #496 ?

**Comment by KorsaR-ZN** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Could you please add unit tests about:

* Execute selects with subqueries

```php
$phql = "SELECT r.* FROM Robots r WHERE r.id NOT IN (SELECT p.id FROM Parts p WHERE r.id < p.id)";
```

* Subqueries referencing models/attributes outside the subquery

```php
$phql = "SELECT * FROM Robots r JOIN RobotsParts rp WHERE rp.id IN (SELECT p.id FROM Parts p WHERE r.partId = p.id)";
```

* Subqueries referencing different fields or incompatible fields?

```php
$phql = "SELECT * FROM Robots r JOIN RobotsParts rp WHERE r.id IN (SELECT p.* FROM Parts)";
```

**Comment by dreamsxin** [comment]
@sergeyklay Yes, That's put on hold for too long.

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
