### PR TITLE
All functions of GetText tested

### PR DESCRIPTION
**Pull request by jenovateurs**
Hello team!

* Type: code quality
* Link to issue: #14685

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

I did the missing tests of Phalcon\Translate\Adapter\Gettext

I add one more expression in en_us and compile .mo to test nquery.

;-)
Thanks

### CODE REVIEW

**Review by ruudboon — DISMISSED** [review]
Approved if test pass and phpcbf is applied. cc @jenovateurs

**Comment by ruudboon** [comment]
@jenovateurs if you run `vendor/bin/phpcbf ` inside your project it should fix it for you.

**Comment by jenovateurs** [comment]
@ruudboon thanks for the tip :-)

**Review by ruudboon — APPROVED** [review]

**Comment by niden** [comment]
Thank you @jenovateurs

**Pull request merged**
