### PR TITLE
Phalcon\Tag::getTitle() shows a title depending on prependTitle and appendTitle

### PR DESCRIPTION
**Pull request by googlle**

### CODE REVIEW

**Comment by Green-Cat** [comment]
Please only include commits related to this pull request.

**Comment by googlle** [comment]
@Green-Cat, could you describe how to do it?

**Comment by D-side** [comment]
Your PR targets `phalcon:2.0.x` when your commit is made on top of `master`. Edit our PR and select a correct branch.

<sub>Привет с ruSO :)</sub>

**Comment by Jurigag** [comment]
Master repo is only snapshot of current released version i guess ?

**Comment by D-side** [comment]
Well, then this branch needs to be rebased onto a correct one. I don't know the author's original intent, but we'll get this sorted out, stand by.

**Comment by sergeyklay** [comment]
1. As you can see tests fails
2. The `2.1.x` branch is best place for this
3. Update CHANGELOG.md please

**Comment by googlle** [comment]
An error occurred because testAppendTitle() method is called before testPrependTitle() - which were set values
```php
$append = ' - Welcome!';
PhTTag::appendTitle($append);
```
The values of the variables were not reset.
Maybe in the method PhTTag::resetInput() - resets the?
```php
let self::_documentTitle = null;
let self::_documentAppendTitle = null;
let self::_documentPrependTitle = null;
let self::_documentTitleSeparator = null;
```


1) Phalcon\Tests\unit\Phalcon\Tag\TagTitleTest::testPrependTitle | prependTitle returns incorrect result
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<title>PhalconPHP -This is my title</title>
+'<title>PhalconPHP -This is my title - Welcome!</title>

It came from the method appendTitle()
```php
public function testAppendTitle()
    {
        $this->specify(
            "appendTitle returns incorrect result",
            function () {

                PhTTag::resetInput();
                $value = 'This is my title';

                PhTTag::setTitle($value);

                $append = ' - Welcome!';

                PhTTag::appendTitle($append);

                $expected = "<title>{$value}{$append}</title>" . PHP_EOL;
                $actual   = PhTTag::getTitle();

                expect($actual)->equals($expected);
            }
        );
    }
```

There is no such variable in the method testPrependTitle()
```php
public function testPrependTitle()
    {
        $this->specify(
            "prependTitle returns incorrect result",
            function () {

                PhTTag::resetInput();
                $value = 'This is my title';

                PhTTag::setTitle($value);

                $prepend = 'PhalconPHP -';

                PhTTag::prependTitle($prepend);

                $expected = "<title>{$prepend}{$value}</title>" . PHP_EOL;
                $actual   = PhTTag::getTitle();

                expect($actual)->equals($expected);
            }
        );
    }
```

**Comment by sergeyklay** [comment]
For example you can use Reflection for testing purposes to reset necessary values

**Comment by sergeyklay** [comment]
Recreated here #11573

**Pull request closed without merging**
