### PR TITLE
[2.0.0] Validation refactoring, double array initialization fix

### PR DESCRIPTION
**Pull request by arius86**
## Major changes
- added abstract `validate()` method to `Phalcon\Validation\Validator` class, made this class abstract
- `Phalcon\Validator` class now implements `Phalcon\Validation\ValidatorInterface`
- changed "keys" array initialization in `Phalcon\Cache\Backend\Memory`
- added #10021 fix to make build possible
## Minor changes
- removed `implements Phalcon\Validation\ValidatorInterface` from all `Phalcon\Validation\Validator\*` classes because parent class (`Phalcon\Validation\Validator`) is implementing it right now
- added "use" statements to  `Phalcon\Validation\Validator\*` instead using fully qualified names

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by arius86** [comment]
I merged your current head. Cheers!

**Comment by andresgutierrez** [comment]
Could you please remove the commits that contains C code? Maybe a new PR would be fine

**Comment by arius86** [comment]
What? Did you check changed files? There is no C code at all...

**Comment by andresgutierrez** [comment]
https://github.com/arius86/cphalcon/commit/fd7a63fc0dabc38a38ef981c59448e1a35f95c5c

**Comment by arius86** [comment]
This merge of your head to my PR..

**Comment by andresgutierrez** [comment]
Branch 2.0.0 was renamed to 2.0.x, could you please submit this change to that branch?

**Pull request closed without merging**
