### PR TITLE
[2.0.x] Improvements Phalcon\Text and tests

### PR DESCRIPTION
**Pull request by KorsaR-ZN**

### CODE REVIEW

**Comment by sergeyklay** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Tests for this component must be placed here: https://github.com/phalcon/cphalcon/tree/master/tests/unit/Phalcon/Text

**Comment by KorsaR-ZN** [comment]
@andresgutierrez Why tests should be placed there ?, how does this differ from the PHPUnit?

**Comment by andresgutierrez** [comment]
tests/ is the main test suite based on Codeception, we are working currently to move all the tests from unit-tests/ to tests/

**Comment by sergeyklay** [comment]
+1 for Codeception :+1:

**Comment by KorsaR-ZN** [comment]
@andresgutierrez  I've moved tests

**Comment by KorsaR-ZN** [comment]
@sergeyklay Yes :)
But I'm waiting for a response from @andresgutierrez for 916c671

**Comment by andresgutierrez** [comment]
PR needs rebase

**Comment by KorsaR-ZN** [comment]
@andresgutierrez Rebased

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
