### PR TITLE
[2.0.x] Readded Http\Request::hasPut() (#10283)

### PR DESCRIPTION
**Pull request by SidRoberts**
See #10283 and https://github.com/phalcon/cphalcon/blob/1.3.4/ext/http/request.c#L692

### CODE REVIEW

**Comment by Green-Cat** [comment]
:+1:

**Comment by sergeyklay** [comment]
@SidRoberts Can you please provide small test like https://github.com/phalcon/cphalcon/blob/master/tests/unit/Phalcon/Http/Request/HttpRequestTest.php#L401 ?

**Comment by SidRoberts** [comment]
@sergeyklay I've tried to write tests but as PUT data is taken from `php://input`, I can't think of a feasible way to test it. On the plus side, attempting to write tests made me realise `$_PUT` doesn't exist. :stuck_out_tongue:

**Comment by sergeyklay** [comment]
Another plus of testing

**Comment by andresgutierrez** [comment]
The contents of file_get_contents("php://input") must be cached in a property, because if you call it twice the second will return null

**Comment by sergeyklay** [comment]
Why not use `define('PHP_INPUT', 'php://input')` or something like that at start (bootstrap) time? :)

**Comment by andresgutierrez** [comment]
Could you please update the CHANGELOG?

**Comment by SidRoberts** [comment]
@andresgutierrez Done.

**Comment by andresgutierrez** [comment]
Thanks

**Comment by sergeyklay** [comment]
@SidRoberts 

>  I can't think of a feasible way to test it. 

```php
stream_wrapper_unregister("php");
stream_wrapper_register("php", "your_awesome_stream_mock_class");
// ...
// tests
// ...
stream_wrapper_restore("php");
```

**Pull request merged**
