### PR TITLE
Added Column::TYPE_TIME

### PR DESCRIPTION
**Pull request by ruudboon**
Adding this type solves #12223

### CODE REVIEW

**Comment by sergeyklay** [comment]
What about https://www.sqlite.org/datatype3.html

**Comment by ruudboon** [comment]
As far as I understand there isn't a real time datatype for sqlite. Only datetime with fuction to extract time.

**Comment by ruudboon** [comment]
@sergeyklay Looking at the other milestones for 3.1.0 I'm expecting a conflict with #11368 that uses 18 also for the const (TYPE_ENUM = 18;). Can you fix this in the merge or should I commit a change to use 19?

**Comment by sergeyklay** [comment]
@ruudboon ofcourse

**Comment by sergeyklay** [comment]
@ruudboon  Could you please rebase, update CHANGELOG.md and ammend tests

**Comment by ruudboon** [comment]
@sergeyklay I'll give it a try. Not really and expert with git, rebasing etc.

**Comment by sergeyklay** [comment]
Close in favor of https://github.com/phalcon/cphalcon/pull/12471

**Pull request closed without merging**
