### PR TITLE
Updated CFLAG default build param

### PR DESCRIPTION
**Pull request by ruudboon**
As requested in phalcon/phalcon-devtools#1301 the build changes that are now part of 4.0.x

### CODE REVIEW

**Review by ruudboon — COMMENTED** [review]
Thnx for cleaning up. I just cherry picked the commit.

**Comment by sergeyklay** [comment]
Well, I'm don't mind make the same cleaning up in the 4.x branch

**Review by sergeyklay — DISMISSED** [review]

**Comment by sergeyklay** [comment]
@ruudboon Could you please update change log?

**Comment by ruudboon** [comment]
> @ruudboon Could you please update change log?

Done

**Review by sergeyklay — APPROVED** [review]

**Comment by niden** [comment]
Thank you @ruudboon

**Pull request merged**
