### PR TITLE
Removed cookie binding to session

### PR DESCRIPTION
**Pull request by ekmst**
Hello!

* Type: improvement
* Link to issue: https://github.com/phalcon/cphalcon/issues/11770

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:
Removed cookie binding to session
`Phalcon\Http\Cookie` no longer depends on the session service and data will not be duplicated in the session. This made it difficult to use cookies in stateless applications (SPA).

Thanks

### CODE REVIEW

**Comment by niden** [comment]
@ekmst can you rebase and send this to the `4.1.x` branch please?

**Review by sergeyklay — CHANGES_REQUESTED** [review]
I'm not opposed to this change, but I would like to see a more detailed description of these changes. Not just "fixed issue XXX".  What suggested in return? Does it breaks backward compatibility? If so, what are workarounds? Why can't we go further with this? 

Regarding change log: why you put these changes in the "Changed" but not in the "Removed" section? Also move please this to the 4.1.x version in the change log.

**Comment by niden** [comment]
This will definitely break BC not by means of interfaces but by functionality itself. For instance right now I set my cookies and I know they will go in the session. With this change they will not so I will need to write that code myself. 

There are plans to completely rewrite the HTTP layer and offer cookie management with different storage engines i.e. files, session etc. but we are not there yet.

@ruudboon @sergeyklay Thoughts on this? If we are to use this we will need to introduce also some sort of a storage i.e. take the session storage from where it was (see this PR) and put it somewhere else so that people can use it at least for now.

**Comment by ekmst** [comment]
I am currently developing a SPA application where sessions are not used at all. But I need to work with cookies. But since the session is not used, I get errors that the session service was not found. And now I have to use a stub to avoid this.

I do not quite understand why cookies are also stored in sessions?

**Comment by niden** [comment]
@ekmst storing cookies in files or the session are the most common storage engines. 

This code is really _ancient_ and has never seen much love - we just let it be. Definitely needs to be reworked so what you did I would say is step 1 and we need step 2 to at least have the option to store the cookies in the session (current functionality)

I will see what I can come up with in the next few days and will ping you so that we can align efforts.

**Comment by ekmst** [comment]
@niden  
Can we save cookies in the session only if the `session` service is defined in the DI container? If the `session` service is not defined, then we work with cookies and we will not throw an exception.

Or we can enter a flag to explicitly indicate that you want to save cookies in the session.

**Comment by niden** [comment]
> @niden
> Can we save cookies in the session only if the `session` service is defined in the DI container? If the `session` service is not defined, then we work with cookies and we will not throw an exception.
> 
> Or we can enter a flag to explicitly indicate that you want to save cookies in the session.

That is actually a great idea. If we mention this in the documentation it should be fine and most people would not be affected if they already have the `session` service registered.

@ekmst can you make the adjustments? 

The above will definitely help and give us time until we redesign the http layer.

**Comment by ekmst** [comment]
@niden 
Yes, I will try to do it soon.

**Comment by niden** [comment]
@ekmst looking good so far. Once you are done make sure the changelog is updated and ping me so that I can merge this

**Comment by ekmst** [comment]
@niden 

Done

**Comment by ruudboon** [comment]
With these changes I wouldn't mind to push this into 4.0.x. Don't think we're breaking anything

**Comment by niden** [comment]
> With these changes I wouldn't mind to push this into 4.0.x. Don't think we're breaking anything
> Thnx ekmst

We will have to cherry pick them because this is a different branch. We can talk about this in TG.

**Comment by niden** [comment]
Thank you @ekmst

**Pull request merged**
