### PR TITLE
Fixes Array to string conversion notice

### PR DESCRIPTION
**Pull request by jimjim2a**
Restore v1.3.x behavior

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please remove this commit https://github.com/jimjim2a/cphalcon/commit/110249557db2e05e3725de40049d38f62fd40299 ? It does not belong to your PR

**Comment by jimjim2a** [comment]
Done !

**Comment by andresgutierrez** [comment]
Could you please don't submit changes to C files?

https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md#pull-request-checklist

**Comment by jimjim2a** [comment]
I didn't commit the C file on purpose, it was a mistake.

I thought doing a revert of this commit and then commit the only debug.zep would be enough.

I close this PR and open a new one if you prefer

**Pull request closed without merging**
