### PR TITLE
Added support for sql relay

### PR DESCRIPTION
**Pull request by jaskaransingh156**
It is related to the NFR mentioned in the following link:

https://github.com/phalcon/cphalcon/issues/11275

Sample code to use this is following:

``` php
$config = [
    'host'        => 'localhost',
    'port'        => 9000,
    'username'    => 'mysqltest',
    'password'    => 'mysqltest',
    'backendType' => 'mysql'
];

$connection = new Phalcon\Db\Adapter\Pdo\Sqlrelay($config);
```

Here, `backendType` is the DBMS to which Sqlrelay connects to. Sample sqlrelay.conf is:

``` xml
<?xml version="1.0"?>
<!DOCTYPE instances SYSTEM "sqlrelay.dtd">
<instances>
    <instance id="mysqltest" dbase="mysql" connections="5" cursors="50">
        <users>
            <user user="mysqltest" password="mysqltest"/>
        </users>
        <connections>
            <connection string="user=test;password=test;db=testing;host=localhost"/>
        </connections>
    </instance>
</instances>
```

### CODE REVIEW

**Comment by sergeyklay** [comment]
Here is many things that need discussion. But first need to fix the code so the test passed

**Comment by jaskaransingh156** [comment]
@sergeyklay I have fixed the code.

**Comment by jaskaransingh156** [comment]
I have changed the code to remove sqlrelay dialect. Now, dialect used in sqlrelay would any one out of mysql, oracle, postgresql and sqlite. It would be taken as input from user in the `backendType` parameter.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises. So far no one has been able to understand why this feature is needed in the framework' core.

**Pull request closed without merging**
