### PR TITLE
Update ini.zep

### PR DESCRIPTION
**Pull request by dred86**
Add "INI_SCANNER_TYPED" in parse_ini_file

### CODE REVIEW

**Comment by Jurigag** [comment]
Update `CHANGELOG.md` here too.

**Comment by dred86** [comment]
Sorry i made a mistake

**Comment by sergeyklay** [comment]
Could you please submit just the commits that belong to the PR?

**Comment by sergeyklay** [comment]
@dred86 Could you please submit just the commits that belong to the PR? Just exclude all Msgpack related stuff and don't add Msgpack to the `CHANGELOG.md` (it already here https://github.com/phalcon/cphalcon/blob/f5543ca20e1c17ce161ff56e2c3752853a352d1b/CHANGELOG.md).

**Comment by sergeyklay** [comment]
@dred86 Also see please @mruz comment at https://github.com/phalcon/cphalcon/issues/11863#issuecomment-224816375

**Comment by dred86** [comment]
@mruz It was updated

**Comment by Jurigag** [comment]
Submit commits related only to this PR.

**Pull request closed without merging**
