### PR TITLE
Fixed incorrect return value when set value to non-existing property

### PR DESCRIPTION
**Pull request by tembem**

### CODE REVIEW

**Comment by Jurigag** [comment]
As you see tests are failing beacause of this change.

**Comment by tembem** [comment]
Well, if this is the correct design from beginning, I will close the PR

**Comment by Jurigag** [comment]
Actually the tests are failing beacause it's beacause of this change and it's logical, for me it could be really good change, beacause most of people NOW are using private/protected property to set anything even if they don't have setter which is so bad behaviour and should never happen. With this change they would need to create setter at least, and then why use protected/private property when you have setter. Just tests needs to be changed as well(model classes need setters).

But this change can break a lot of apps.

**Comment by tembem** [comment]
@Jurigag couldn't agree more.

Any suggestions @sergeyklay @andresgutierrez ?

**Comment by sergeyklay** [comment]
Refs #11286, #11427

**Pull request closed without merging**
