### PR TITLE
Fix getReservedAttributes

### PR DESCRIPTION
**Pull request by Jurigag**
Hello!

* Type: bug fix
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: On php 7/7.1 when extending internal class with null static it's value in C code is returned as `&NULL` causing condition if reserver === null to be false and breaking collections for php 7. This is workaround for this.

Link to bug in php - https://bugs.php.net/bug.php?id=74648

Thanks

@sergeyklay @sjinks if you have other idea which condition could be used and still fixing this let me know

### CODE REVIEW

**Comment by sergeyklay** [comment]
@Jurigag Could you please cherry pick from https://github.com/phalcon/cphalcon/pull/12861

**Comment by sergeyklay** [comment]
@Jurigag I've updated tests-related stuff https://github.com/phalcon/cphalcon/pull/12861. Could you please rebase onto 3.2.x?

**Comment by sergeyklay** [comment]
@Jurigag Could you please rebase

**Comment by runphp** [comment]
why not?
```
let reserved = static::_reserved;
```

**Comment by sergeyklay** [comment]
@runphp Could you please explain a bit more?

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you

**Comment by runphp** [comment]
@sergeyklay 
when override Phalcon\Mvc\Collection likethis
```php
abstract class MongoCollection extends \Phalcon\Mvc\Collection
{
   
    static protected $_reserved = [
        '_connection' => true,
        '_dependencyInjector' => true,
        '_source' => true,
        '_operationMade' => true,
        '_errorMessages' => true,
        '_dirtyState' => true,
        '_modelsManager' => true,
        '_skipped' => true,
    ];
```

the getReservedAttributes() still return parent content

**Comment by sergeyklay** [comment]
Hmm.. @Jurigag could you please take a look?

**Comment by Jurigag** [comment]
Hmmm i don't know why this happens, will check when i will can.

**Pull request merged**
