### PR TITLE
Update changelog.md v3

### PR DESCRIPTION
**Pull request by Arhell**
Hello!

* Change changelog.md

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [ ] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Thanks

### CODE REVIEW

**Review by ruudboon — DISMISSED** [review]
We're not really updating v3 but makes sense to me to merge this. Looks good

**Comment by sergeyklay** [comment]
@Arhell Could you send this PR to the 4.0.x branch?

**Comment by Arhell** [comment]
@sergeyklay done

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
