### PR TITLE
Phalcon\Session\Bag: add of initialization for remove()

### PR DESCRIPTION
**Pull request by morafabio**
* Type: bug fix
* Issue: when `Phalcon\Session\Bag` is restored by the session handler, the `_data` property results not initialized and `remove()` won't work properly.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.  

Small description of change:  Initialization steps in `remove()` have been added.

Steps to reproduce:

       <?php
       
        // debug with reflection
        $reflectionClass = new \ReflectionClass(get_class($this->bag));
        $_data = $reflectionClass->getProperty('_data');
        $_data->setAccessible(true);
        $_initialized = $reflectionClass->getProperty('_initialized');
        $_initialized->setAccessible(true);

        // create a Bag with one value
        $bag = new \Phalcon\Session\Bag('fruit');
        $bag->set('apples', 10);
        var_dump($bag->get('apples')); // int(10)
        var_dump($_data->getValue($bag)); // array(1) { ["apples"]=> int(10) }
        var_dump($_initialized->getValue($bag)); // bool(true)

        // save and cleanup
        $serializedBag = serialize($bag);
        unset($bag);

        // emulate restore in the same way it would be done
        // any PHP session handler, e.g.: `session.save_handler => redis => redis`
        $bag = unserialize($serializedBag);
        $_data->setValue($bag, NULL);
        $_initialized->setValue($bag, false);

        // remove attempt fails because `_data` is NULL
        var_dump($bag->remove('apples')); // bool(false) // EXPECTED: bool(true)
        var_dump($bag->get('apples')); // int(10) // EXPECTED: NULL

        // get performs _initialize under the hood, so now it works
        var_dump($bag->remove('apples')); // bool(true)
        var_dump($bag->get('apples')); // NULL

this calls initialize also on `Bag::remove`.

Run tests: `vagrant@phalcon:~/cphalcon$ vendor/bin/codecept run tests/unit/Session/BagTest`

Thanks

### CODE REVIEW

**Comment by gabrieledarrigo** [comment]
👍

**Comment by sergeyklay** [comment]
@morafabio Could you please update CHANGELOG.md and cover your changes by small test?

**Comment by morafabio** [comment]
@sergeyklay sure for the `CHANGELOG.md` file, but can you please give me an hint on how to test the change? The best thing would be test in with an unit test. Thanks

**Comment by sergeyklay** [comment]
For example see: https://github.com/phalcon/cphalcon/tree/master/tests/unit/Session

**Comment by Jurigag** [comment]
Just add new method here - https://github.com/phalcon/cphalcon/blob/master/tests/unit/Session/BagTest.php

**Comment by morafabio** [comment]
Hum, got it, but in this way is a functional test, you're running PHP against the Zephir codebase. If this is the right way, ok!

Would be ok if I reuse a small part of the example above ("Steps to reproduce") adapting it and introducing proper assertions?

**Comment by sergeyklay** [comment]
Yes, I think so

**Comment by morafabio** [comment]
@sergeyklay Test added :)

**Comment by morafabio** [comment]
Should I rebase to which branch? Add something to `CHANGELOG.md`?

**Comment by sergeyklay** [comment]
@morafabio Could you please submit this PR to the 3.1.x branch. And yes, update please CHANGELOG.md

Refs:

* https://blog.phalconphp.com/post/phalcon-3-0-4-released

**Comment by morafabio** [comment]
@sergeyklay Ok, for `CHANGELOG.md` the comment is supposed to be on top of the file (line 0)?

**Comment by morafabio** [comment]
Done, https://github.com/phalcon/cphalcon/pull/12647

**Pull request closed without merging**
