### PR TITLE
T13648 firewall

### PR DESCRIPTION
**Pull request by niden**
Hello!

* Type: new feature
* Link to issue: #13648 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

this pr is adding Firewall component, way to protect routes against unauthorized roles to access certain routes. It's done using listener on dispatcher/micro on beforeExecute/afterBinding event.

In dispatcher you can either use Annotations or Acl based firewall. In micro there is only Acl based firewall.

Would appreciate any comments etc.

This PR is commits/changes from other PRs etc stuff so don't bother them, i will rebase everything if all will be merged.
Thanks

Related:
#11389
#582

Based on work from @Jurigag https://github.com/phalcon/cphalcon/pull/12561

Thanks

### CODE REVIEW

**Comment by niden** [comment]
cc @sergeyklay

**Review by sergeyklay — DISMISSED** [review]

**Comment by Jurigag** [comment]
Looks good to me, but since it's a big feature we better implement those tests you added.

**Review by Jurigag — DISMISSED** [review]
Looks fine, needs to implement all those added tests which my branch didn't cover.

**Comment by ruudboon** [comment]
Awesome!!

**Pull request merged**
