### PR TITLE
#11042 - Fix setting relation should not always cause dirty state change

### LINKED ISSUE #11042: Accessing relation in model causes dirty state to change to transient
Code:

```php
  class Parent extends \Phalcon\Mvc\Model {
    public $id;
    public function initialize() {
      $this->hasMany('id', 'Child', 'parent', array(
        'foreignKey' => array('action' => Relation::ACTION_RESTRICT),
        'alias'  => 'relatedchilds'));
    }
  }
  class Child extends \Phalcon\Mvc\Model {
    public $parent;
    public $id;
    public function initialize() {
      $this->belongsTo('parent', 'Parent', 'id', array(
          'alias' => 'relatedparent',
          'foreignKey' => array('message' => 'Must have parent')
      ));
    }
  }

  $children = Child::find(); // get all child records
  foreach ($children as $child) {
    echo "Initial state: {$child ->getDirtyState()} <br />";
    $parent = $child ->relatedparent;
    echo "After accessing parent - state: {$child ->getDirtyState()} <br />";
  }
```

Is this by design? If so, why? This is causing us big headaches in our application, so any help would be appreciated.

### PR DESCRIPTION
**Pull request by nsossonko**
This should fix #11042 although I have no real way of testing it. Hope my style follows conventions. This time for 2.0.x branch

### CODE REVIEW

**Comment by sergeyklay** [comment]
@nsossonko Can you please provide a small test case?

**Comment by nsossonko** [comment]
You mean an automated test for this fix?

**Comment by nsossonko** [comment]
Unit test added for this bug

**Comment by nsossonko** [comment]
How can I get this merged?

**Comment by nsossonko** [comment]
If I can get some help getting this merged in I'd really appreciate it. This bug is really biting us now...

**Comment by sergeyklay** [comment]
@andresgutierrez

**Comment by nsossonko** [comment]
@andresgutierrez can you merge this patch? Is there anything further necessary to get this in?

**Comment by andresgutierrez** [comment]
Thanks

**Comment by nsossonko** [comment]
Thanks much!

**Pull request merged**
