### PR TITLE
Implements support for Collection Behaviors

### PR DESCRIPTION
**Pull request by Green-Cat**
Steps:
- [x] Add support for Collection Behaviors
- [x] Implement SoftDelete and Timestampable behaviors
- [x] Add tests
- [x] Add to changelog

related issue #1336

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please update the CHANGELOG and add tests?

**Comment by sergeyklay** [comment]
:+1:

**Comment by Green-Cat** [comment]
@andresgutierrez Done, I've edited the changelog and added tests for both behaviors.
Also squashed the commits into one.

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
