### PR TITLE
Added Redis Session class.

### PR DESCRIPTION
**Pull request by SidRoberts**

### CODE REVIEW

**Comment by sergeyklay** [comment]
:+1:

**Comment by broklyngagah** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Could you please add unit-tests?

**Comment by SidRoberts** [comment]
Don't merge just yet, I want to add test classes for all the Session classes. :smile:

**Comment by sergeyklay** [comment]
:+1: :+1:

**Comment by andresgutierrez** [comment]
@SidRoberts Could you please rebase?

**Comment by SidRoberts** [comment]
@andresgutierrez Done.

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
