### PR TITLE
Method to check if relationship was loaded

### PR DESCRIPTION
**Pull request by Surt**
Hello!

* Type: new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Method to check if a relationship was loaded. So we can check it without invoking the lazy loading.

Thanks

### CODE REVIEW

**Comment by grigoriygithub** [comment]
```_related ``` used in the EagerLoading (and somewhere else). If you use phalcon relations they will be store in modelsManager.

**Comment by sergeyklay** [comment]
@Surt Could you please cover your additions by small test?

@grigoriygithub Can you please explain your comment a bit more?

**Comment by Jurigag** [comment]
Also update changelog.

**Comment by grigoriygithub** [comment]
@sergeyklay 
Models:
```php
class Pages extends Model
{
    protected $id;
    protected $section_id;

    public function initialize()
    {
        $this->belongsTo('section_id', Sections::class, 'id', [
            'alias' => 'Section',
            'reusable' => true
        ]);
    }
// getters-setters
}
class Sections extends Model
{
    protected $id;
// getters-setters
}
```
Case: 1 Phalcon Relations
```php
 $Page = Pages::findFirst();
 $PageSection = $Page->getSection();
/*
in Page Model:
protected '_related' => null
*/
 var_dump($Page); // page
/*
in Models Manager: 
  protected '_reusable' => 
    array (size=2)
      'Sections[[[id] = :APR0:,[0],]]' => object(Section)
*/
 var_dump($this->modelsManager);
```
Case: 2 Eager Loading from Incubator
```php
 $Page = Pages::findFirstWith('Section');
/*
in Page Model:
protected '_related'  => 
    array (size=1)
      'section' => object(Section)
public 'section' => object(Section)
*/
 var_dump($Page); // page
/*
in Models Manager: 
  protected '_reusable' => null
*/
 var_dump($this->modelsManager);
```

**Comment by Surt** [comment]
Anyway this would not work. The `_related` property is filled just for `belongs-to` as pointed in https://github.com/phalcon/cphalcon/pull/12772

**Comment by Surt** [comment]
I wrote a wall of text about this issue.
https://forum.phalconphp.com/discussion/15981/relationships-getrelated-getrelatedrecords-get

**Comment by sergeyklay** [comment]
@Surt Could you please only submit commits relevant to the PR.

**Comment by Surt** [comment]
Would be great if someone have the time to finish it.  
Last time I checked there was a problem where _related does not contain all the relationship types, but now when I checked again it seems that already has been changed.

The old code only setted _related on belongs-to relationships
> Anyway this would not work. The _related property is filled just for belongs-to as pointed in https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L4355

**Comment by niden** [comment]
@Surt I am happy to help with this but I am having trouble identifying the changes. Also it took me a while to get to this so this one points to 3.2 vs the current 3.4.x branch.

I will try and address this as soon as I can.

**Comment by CameronHall** [comment]
I've [redone this for the 4.0.x branch](https://github.com/phalcon/cphalcon/pull/13616). @Surt I tried to cherry-pick the commits but my git kept wigging out, so I've made sure you're noted as a co-author.

**Comment by sergeyklay** [comment]
Closed in favor of #13616

**Pull request closed without merging**
