### PR TITLE
[2.0.0] Validation refactoring, double array initialization fix, #10021 fix included

### PR DESCRIPTION
**Pull request by arius86**
## Major changes
- added abstract `validate()` method to `Phalcon\Validation\Validator` class, made this class abstract
- `Phalcon\Validator` class now implements `Phalcon\Validation\ValidatorInterface`
- changed "keys" array initialization in `Phalcon\Cache\Backend\Memory`
- added #10021 fix to make build possible
## Minor changes
- removed `implements Phalcon\Validation\ValidatorInterface` from all `Phalcon\Validation\Validator\*` classes because parent class (`Phalcon\Validation\Validator`) is implementing it right now
- added "use" statements to  `Phalcon\Validation\Validator\*` instead using fully qualified names

### CODE REVIEW

**Comment by arius86** [comment]
@phalcon - lot of files changed because of my build, most of them are just comment header about Phalcon Framework. Is there an option to build without those to make pull request cleaner?

**Comment by SidRoberts** [comment]
You'll have to rebase them into one commit and then reset `ext/`:

```bash
# Optional
git config --global core.editor "nano"

git rebase --interactive $(git merge-base 2.0.0 upstream/2.0.0)
# pick 40515e3 ...
# squash d2e1374 ...
# squash b674de9 ...

# You'll be able to change the commit message if you want.

# Reset the ext/ folder to the previous commit.
# http://superuser.com/questions/229290/how-to-amend-the-last-commit-to-un-add-a-file/567550#567550
git reset HEAD^ ext/

git commit --amend

# You've rewritten history so you'll need to force it.
git push -f
```

**Comment by Green-Cat** [comment]
Since  #10021 has been merged, you may want to remove that change from the commit (aka rebase).

**Comment by arius86** [comment]
Aka I will rebase and clean directory and then create new pull requests, I would like to run travis on my fork as well.

**Pull request closed without merging**
