### PR TITLE
[NFR] Added json dataType support for MySQL dialect.

### PR DESCRIPTION
**Pull request by zGaron**
Hello!

instead of PR #13216 

* Type: new feature
* Link to issue: #12546, #12985, #13214

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Thanks

### CODE REVIEW

**Comment by zGaron** [comment]
MySQL version >=  5.7.  = =!

**Comment by jellisii** [comment]
Is this expected for 3.3.2, or will it be in 4.x?

**Comment by sergeyklay** [comment]
@virgofx I think so

**Comment by benfavre** [comment]
This should be on the top of all lists.

**Comment by niden** [comment]
@virgofx I don't think that there is an automatic conversion towards a `JSON` column from PHP. 

`JSON` columns in MySQL/MariaDB are pretty much storing text or a string. They do however have an internal mechanism that checks the syntax of the JSON string and throws an exception when you try to update it.

@zGaron would you be so kind as to rebase this and send it to the 4.0.x branch?

Thank you

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/13562

**Pull request closed without merging**
