### PR TITLE
Build Phalcon on AppVeyor using PHP 7.4

### PR DESCRIPTION
**Pull request by sergeyklay**
Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/cphalcon/pull/14611

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

- Build Phalcon on AppVeyor using PHP 7.4
- Correct type definitions for annotations parser
- Use latest stable Zephir

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
Please note: This is Windows only fix. So I don't updated Zephir version for Travis in this PR.

**Review by ruudboon — APPROVED** [review]

**Comment by ruudboon** [comment]
@sergeyklay is there still things need to be done in Zephir to use this on travis as well? Should we log an issue in that case?

**Comment by sergeyklay** [comment]
No, you can safely upgrade Zephir for Travis as well.

**Comment by ruudboon** [comment]
Haha sorry. On my phone. Only thumbs up!

**Pull request merged**
