### PR TITLE
Adding Passback To DIC

### PR DESCRIPTION
**Pull request by Fenikkusu**
Hello!

* Type: new feature

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

I often find myself having to do the following:

```php
use Phalcon\Di;
use Other;
use Another;

$di = new Di();

$di->set('name', function () {
   return $this->get(Other::class);
});

if (true) {
     $di->set(Other::class, Another::class);
}

```

This PR eliminates the extra steps by letting the service class instantiate through the DIC. I can now right the code as:

```php

use Phalcon\Di;
use Other;
use Another;

$di = new Di();

$di->set('name', Other::class);
if (true) {
     $di->set(Other::class, Another::class);
}

```

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
Related to https://github.com/phalcon/cphalcon/issues/13042

**Review by niden — DISMISSED** [review]

**Comment by niden** [comment]
@Fenikkusu could you please add an entry in the CHANGELOG-4.0 please?

**Comment by niden** [comment]
and rebase

**Comment by Fenikkusu** [comment]
Done

**Review by sergeyklay — DISMISSED** [review]

**Review by ruudboon — DISMISSED** [review]

**Review by Jeckerson — DISMISSED** [review]

**Review by sergeyklay — APPROVED** [review]

**Review by ruudboon — APPROVED** [review]

**Pull request merged**
