### PR TITLE
onUncaughtException should accept \Throwable instead of \Exception

### PR DESCRIPTION
**Pull request by janisbiz**
Hello!

* Type: bug fix

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

As of support for php 7.x and introduction of \Throwable, Phalcon Debug method of `onUncaughtException` should accept `\Throwable` instead of `\Exception`

Thanks

### CODE REVIEW

**Review by niden — DISMISSED** [review]

**Comment by niden** [comment]
@janisbiz can you rebase your branch please. It seems the checks did not pass also.

**Comment by janisbiz** [comment]
@niden thanks for noting. As it turns out my local fork was from 2017, so everything was really outdated. Should be fine now.

**Comment by niden** [comment]
Thank you @janisbiz Once the tests are done I will merge this. Could you also be so kind as to update the changelog ? This will be in the 4.0.3 section

**Review by ruudboon — APPROVED** [review]

**Review by niden — APPROVED** [review]

**Comment by niden** [comment]
Thank you @janisbiz

**Pull request merged**
