### PR TITLE
Feature/dialect support comment

### PR DESCRIPTION
**Pull request by cq-z**
Hello!

* Type: bug fix | new feature | code quality | documentation
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Thanks

### CODE REVIEW

**Comment by ruudboon** [comment]
@cq-z Thnx for the pull! Looks like a nice addition to me but would like to check with the rest of the @phalcon/core-team as well. Maybe you can explain the use-case for this in the pull. If we accept this NFR we need to have the following things in place.

- target branch should be 4.1.x
- changelog should be updated as well
- tests/tocheck-database/* must be refactored to tests/database with new structure

The target branch and changelog is something you can fix. Test tocheck-database tests aren't currently running on our CI, we are in the process of refactoring them. Before we merge this I want them in place. Would be great if you can refactor those tests as well, but we also keep this pull pending and wait for the refactoring (when it's in you should adjust some tests before merging).

**Comment by Jeckerson** [comment]
This is what phalcon migrations is lacking atm... 

Good addition, but please fix action points in comment of Ruud. This feature is required good dedication.

**Comment by cq-z** [comment]
Ok! At night I merged to 4.1.x

**Comment by ruudboon** [comment]
@cq-z You can change your target branch in the pull and just rebase you local branch. That way you can keep your pull open.

**Pull request closed without merging**
