### PR TITLE
[2.0.0] Fixed #3190

### LINKED ISSUE #3190: Developer Tools IDE stubs
Hi!

Please add to `/phalcon-devtools/ide/2.0.0/Phalcon/Http/Request.php`:

```php
		/**
		 * Gets HTTP URI which request has been made
		 *
		 * @return string
		 */
		final public function getURI() {}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7548737-developer-tools-ide-stubs?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sergeyklay**
The #3190 issue fixed fully **here** and in this PR https://github.com/phalcon/zephir/pull/718

### CODE REVIEW

**Comment by akaNightmare** [comment]
for me better use ```null === some_variable```

**Comment by 7thcubic** [comment]
u can also just remove the doc and let zeph stubs handle it

**Comment by sergeyklay** [comment]
@7thcubic No

> `var type, var message = null, var context = null`
How Zephir generate doc here?

**Comment by 7thcubic** [comment]
var will be mixed no? i am under the assumption that var = mixed, array = array etc etc =d

**Comment by sergeyklay** [comment]
It seems about var my PhpStorm disagree with you =d

**Comment by andresgutierrez** [comment]
Could you please rebase against 2.0.0?

**Comment by sergeyklay** [comment]
@andresgutierrez Done

**Comment by andresgutierrez** [comment]
It can't be merged, there seem to be conflicts

**Comment by sergeyklay** [comment]
Sorry, my mistake. Try again please

**Pull request merged**
