### PR TITLE
Updated volt parser

### PR DESCRIPTION
**Pull request by dreamsxin**
Hello!

* Type: bug fix
* Link to issue:

**In raising this pull request, I confirm the following:**

- [ ] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [ ] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Thanks

### CODE REVIEW

**Comment by ruudboon** [comment]
Thnx for working on this @dreamsxin

**Comment by dreamsxin** [comment]
Only 7.4 failed @niden

**Review by ruudboon — APPROVED** [review]

**Comment by ruudboon** [comment]
> Only 7.4 failed @niden
7.4 was already failing on Phalcon.

**Comment by dreamsxin** [comment]
@ruudboon Thank you

**Comment by sergeyklay** [comment]
Thank you!

**Pull request merged**
