### PR TITLE
3.1.x check if before error,before throwable works in php5

### PR DESCRIPTION
**Pull request by Jurigag**

### CODE REVIEW

**Comment by virgofx** [comment]
The dispatcher changes will not be compatible with this. Don't merge.

**Comment by Jurigag** [comment]
Compiling fine, tests for php 5.5 and 5.6 passing, but better keep talking, yea.

**Comment by virgofx** [comment]
Introducing throwables will not be done on a small use case like this. It requires change globally as I have said before, including documentation changes as well

**Comment by Jurigag** [comment]
I will include documentation changes as well, what globally ? When 3.1.x repo will be here i will create final PR. But now there must be multicatching in zephir fixed because right now it doesn't work for some reason.

**Comment by virgofx** [comment]
There needs to be a strategy involved in handling the transition to PHP7 with respect to exceptions globally in the code base, documentation, backwards compatibility, and other concerns.  It will involve more discussion in future.

So for now, this is a bigger project than a simple hook for dispatcher.

**Comment by Jurigag** [comment]
What you mean globally in the code ? In php7 all exceptions implements throwable, nothing fancy here. Just write code which will be breaking this stuff after i will do PR to 3.1.x and then we can start discussion.

**Pull request closed without merging**
