### PR TITLE
T13915 coding standard

### PR DESCRIPTION
**Pull request by niden**
Hello!

* Type: code quality
* Link to issue: #13915 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Applying the new coding standard for Phalcon. Certain files have been left untouched intentionally - they will be replaced./refactored later on

Thanks

### CODE REVIEW

**Comment by niden** [comment]
cc @sergeyklay

**Review by sergeyklay — APPROVED** [review]

**Comment by SidRoberts** [comment]
Is there a reason why Phalcon\Application, Phalcon\Cache\* didn't get renamed?

**Comment by sergeyklay** [comment]
I have no idea :) Well, PRs are always welcome!

**Comment by niden** [comment]
@SidRoberts Application it was most likely a mishap. 

Cache is going to be rewritten for PSR-16 so no point in renaming it.

**Comment by SidRoberts** [comment]
Fixed in #13920

**Pull request merged**
