### PR TITLE
T13114 message interfaces

### PR DESCRIPTION
**Pull request by niden**
Hello!

* Type: enhancement
* Link to issue: #13114 

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Removed the `Message` interfaces in validation and model. Added a new component/interface  `Phalcon\Messages\MessageInterface` that both model and validation use now. Did the same for the collection of messages.

Thanks

### CODE REVIEW

**Comment by grigoriy-ivanov** [comment]
How about #13113 ?

**Comment by niden** [comment]
@grigoriy-ivanov Missed that. I will update the PR accordingly today

**Comment by niden** [comment]
cc @sergeyklay

**Comment by niden** [comment]
@grigoriy-ivanov Just added the JsonSerializable

**Comment by grigoriy-ivanov** [comment]
Thank you, @niden

**Pull request merged**
