### PR TITLE
Add late state binding on model

### PR DESCRIPTION
**Pull request by ogarbe**
Conflicts:
phalcon/mvc/model/resultset/simple.zep

cf #3107

### CODE REVIEW

**Comment by KorsaR-ZN** [comment]
:+1:

**Comment by Green-Cat** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Could you please rebase this to latest 2.0.x?

**Comment by Green-Cat** [comment]
@ogarbe Quick question, why is the setting even necessary? Are there any situations when someone would not want this behaviour? oO

**Comment by andresgutierrez** [comment]
@Green-Cat I asked him to implement it that way, dynamic calls are slower compared to methods well known at compile time, as this implementation is key when hydrating records this allows to reduce the overhead if someone is not using that feature.

**Comment by sergeyklay** [comment]
@Green-Cat `"default": true` is enough :)

**Comment by andresgutierrez** [comment]
@ogarbe it should be `"default": false`

**Comment by ogarbe** [comment]
@andresgutierrez  @sergeyklay it's done

**Comment by andresgutierrez** [comment]
Sorry :'(, could you please rebase again?

**Comment by ogarbe** [comment]
@andresgutierrez done :-)

**Comment by Green-Cat** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Thanks

**Comment by KorsaR-ZN** [comment]
@ogarbe Your PR broke build. Please fix it

**Comment by vitaliy-w** [comment]
@ogarbe Is there any reason why `orm.late_state_binding` is defaulted to `false` in this PR, but was originally defaulted to `true` in https://github.com/phalcon/cphalcon/pull/3107?

**Comment by ogarbe** [comment]
yes, it's a request from @andresgutierrez who though this functionality should be disabled by default because of the extra operations it request.

You can enable it globally in php.ini

``ìni
extension=phalcon.so
phalcon.orm.late_state_binding=1
```

**Comment by vitaliy-w** [comment]
@ogarbe Thank you for explaining. This is a very useful feature to have.

**Pull request merged**
