### PR TITLE
[2.0.x] Mvc\Model::findFirst() now allows hydration

### PR DESCRIPTION
**Pull request by SidRoberts**
See #10259

### CODE REVIEW

**Comment by KorsaR-ZN** [comment]
:+1:

**Comment by Green-Cat** [comment]
:+1:

**Comment by andresgutierrez** [comment]
Could you please update the CHANGELOG?

**Comment by SidRoberts** [comment]
@andresgutierrez, I've updated the CHANGELOG but Travis will likely fail due to https://travis-ci.org/phalcon/cphalcon/jobs/61474693#L975

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
