### PR TITLE
Proxies fix

### PR DESCRIPTION
**Pull request by Jurigag**
If someone wonder how i found broken classes:

``` php
$path = "_proxies/";
$fqcns = array();

$allFiles = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
$phpFiles = new RegexIterator($allFiles, '/\.php$/');
foreach ($phpFiles as $phpFile) {
    $content = file_get_contents($phpFile->getRealPath());
    $tokens = token_get_all($content);
    $namespace = '';
    for ($index = 0; isset($tokens[$index]); $index++) {
        if (!isset($tokens[$index][0])) {
            continue;
        }
        if (T_NAMESPACE === $tokens[$index][0]) {
            $index += 2; // Skip namespace keyword and whitespace
            while (isset($tokens[$index]) && is_array($tokens[$index])) {
                $namespace .= $tokens[$index++][1];
            }
        }
        if (T_CLASS === $tokens[$index][0]) {
            $index += 2; // Skip class keyword and whitespace
            $fqcns[] = $namespace.'\\'.$tokens[$index][1];
        }
    }
}

foreach($fqcns as $class)
{
    $reflection = new ReflectionClass($class);
    if ($reflection->isInstantiable()){
        try {
            $reflection->newInstanceWithoutConstructor();
        }
        catch(Exception $e){
            var_dump($e->getMessage());
        }
    }
}
```

### CODE REVIEW

**Comment by Jurigag** [comment]
[Codeception\Exception\ConfigurationException]  
 Module Phalcon2 could not be found and loaded  

Wtf this random errors xD

**Comment by sergeyklay** [comment]
@Jurigag Could you please change Phalcon2 to Phalcon ?

**Comment by sergeyklay** [comment]
Codeception 2.2.0-beta is released right now

**Comment by sergeyklay** [comment]
@Jurigag 
See https://github.com/Codeception/Codeception/commit/0a078a25f1582888b59747e2175a663179808c08

I've merged `Phalcon1` and `Phalcon2` modules into one `Phalcon` due the fact that Phalcon Framework v1.3.x no longer supported at all

**Comment by Jurigag** [comment]
Nice timing.

I hope that i made it right. Now i go sleeping.

**Comment by sergeyklay** [comment]
Thanks

**Comment by Jurigag** [comment]
Also you could add some phpdoc on $I(tester) beacause i don't know from where exactly this object is received and phpstorm is telling that method dont exist(i have codeception, specify and verify as libraries).

@sergeyklay

**Comment by sergeyklay** [comment]
Create separated issue. Just so I don't forget

**Pull request merged**
